const combinePairIds = [
  'custom4_r01_g01',
  'custom5_r01_g01',
  'custom11_r01_g01',
  'custom13_r01_g01',
  'custom14_r01_g01',
  'custom15_r01_g01',
  'custom16_r01_g01',
  'custom17_r01_g01',
  'custom18_r01_g01',
  'custom19_r01_g01',
  'custom20_r01_g01',
  'custom24_r01_g01',
  'custom26_r01_g01',
  'custom29_r01_g01',
  'custom31_r01_g01',
  'custom33_r01_g01',
  'custom34_r01_g01',
  'custom35_r01_g01',
  'custom38_r01_g01',
  'custom39_r01_g01',
  'custom40_r01_g01',
  'custom41_r01_g01',
  'custom42_r01_g01',
  'custom43_r01_g01',
  'custom44_r01_g01',
  'custom45_r01_g01',
  'custom46_r01_g01',
  'custom47_r01_g01',
  'custom48_r01_g01',
  'custom49_r01_g01',
  'custom50_r01_g01',
  'custom51_r01_g01',
  'custom52_r01_g01',
  'custom53_r01_g01',
  'custom54_r01_g01',
  'custom55_r01_g01',
  'custom56_r01_g01',
  'custom57_r01_g01',
  'custom58_r01_g01',
  'custom59_r01_g01',
  'custom60_r01_g01',
  'custom61_r01_g01',
  'custom62_r01_g01',
  'custom63_r01_g01',
  'custom64_r01_g01',
  'custom65_r01_g01',
  'custom66_r01_g01',
  'custom67_r01_g01',
  'custom68_r01_g01',
  'custom69_r01_g01',
  'custom70_r01_g01',
  'custom71_r01_g01',
  'custom72_r01_g01',
  'custom73_r01_g01',
  'custom74_r01_g01',
  'custom75_r01_g01',
  'custom76_r01_g01',
  'custom77_r01_g01',
  'custom78_r01_g01',
  'custom79_r01_g01',
  'custom80_r01_g01',
  'custom81_r01_g01',
  'custom82_r01_g01',
  'custom83_r01_g01',
  'custom84_r01_g01',
  'custom85_r01_g01',
  'custom86_r01_g01',
  'custom87_r01_g01',
  'custom88_r01_g01',
  'custom89_r01_g01',
  'custom90_r01_g01',
  'custom91_r01_g01',
  'custom92_r01_g01',
  'custom93_r01_g01',
  'custom94_r01_g01',
  'custom95_r01_g01',
  'custom96_r01_g01',
  'custom97_r01_g01',
  'custom98_r01_g01',
  'custom99_r01_g01',
  'custom100_r01_g01',
  'custom101_r01_g01',
  'custom102_r01_g01',
  'custom103_r01_g01',
  'custom104_r01_g01',
  'custom105_r01_g01'
]

const poseMetadataOverrides = {
  custom1_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '温柔侧身半身',
    tip: '推荐日常写真、半身照、侧身显瘦',
    description: '身体微微转向左侧，头部自然回正，视线轻看镜头斜上方；一手垂放、一手轻搭腰间，适合拍随性温柔的半身侧身照。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f7f1ec 0%, #8a7468 100%)'
  },
  custom2_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '侧光撩发半身',
    tip: '推荐日常写真、互动感半身、温柔光影照',
    description: '正面偏侧站立，头部微微向右倾，一手轻抚耳侧发丝，另一手自然垂放；直视镜头配合浅笑，适合拍自然亲和的侧光半身照。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f5efe8 0%, #816d60 100%)'
  },
  custom3_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '一字肩托腮',
    tip: '推荐知性半身、锁骨肩线、故事感写真',
    description: '半身正面姿态，一手轻托下巴作思考状，另一手自然环抱身前；头部微倾、眼神低垂，适合拍温柔沉静的知性氛围照。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f5f3ef 0%, #7f7a73 100%)'
  },
  custom4_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '野餐垫托腮趴姿',
    tip: '推荐湖岸野餐、趴姿托腮、慵懒少女感照片',
    description: '趴在湖岸草地的格纹野餐垫上，双肘撑地、双手托腮，双腿在身后屈膝翘起并交叉脚踝；面前摆着书、法棍和葡萄，适合拍慵懒午后的野餐氛围照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom4/custom4_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c0df 0%, #6f7d58 100%)'
  },
  custom5_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '侧身撩发抬眸',
    tip: '推荐温柔毛衣照、撩发半身、灵动眼神照',
    description: '半身侧身站立，一手轻撩耳侧发丝，头部微倾；从低垂视线到抬眸看向镜头，配合侧光和浅笑，适合拍温柔甜美的自然半身照。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f7f0e7 0%, #8b7664 100%)'
  },
  custom6_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '回眸显腿长',
    tip: '推荐全身穿搭、逆光街拍、显比例站姿',
    description: '全身微侧站立，一脚前伸点地拉长腿部线条，一手叉腰、一手自然下垂；头部回眸看向镜头，适合拍自信温柔的高腰穿搭照。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #f6eadc 0%, #8a6d55 100%)'
  },
  custom7_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '咖啡街拍行走',
    tip: '推荐都市街拍、行走抓拍、休闲通勤穿搭',
    description: '全身自然行走姿态，一手握咖啡杯垂于身侧，另一手随步伐轻摆；低眸再抬眸看向镜头，适合拍随性自在的都市街拍感。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #eef0ed 0%, #5f6760 100%)'
  },
  custom8_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '户外自然站姿',
    tip: '推荐户外人像、日常全身照、亲和站姿',
    description: '全身自然站立，重心均匀、身形挺拔舒展，一手自然垂放身侧；面向镜头温和微笑，适合作为亲切自信的户外日常站姿参考。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #f2eadf 0%, #6f655a 100%)'
  },
  custom9_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '西装咖啡街拍',
    tip: '推荐都市街拍、通勤全身照、咖啡随拍',
    description: '身体微侧，重心落于后腿，前腿微屈放松；左手插在阔腿裤口袋，右手自然垂放轻握咖啡，适合拍干练利落又闲适从容的都市全身照。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #eee7dc 0%, #7b6d60 100%)'
  },
  custom10_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '山顶背影跃动',
    tip: '推荐创意背影、旅行全身照、活力动态照',
    description: '背影站立于山顶，重心落于左腿，右腿向后踢起；右臂高举、左臂向侧方舒展，适合拍青春自由、开放有表现力的旅行背影照。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #f2ddbf 0%, #66725b 100%)'
  },
  custom11_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '回眸撩发背影',
    tip: '推荐户外背影、长裙写真、温柔抓拍',
    description: '背影微侧站立，头部轻柔回眸望向镜头方向；右手抬起轻触耳侧发丝，左手自然垂放，适合拍不经意抓拍感的温柔户外人像。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #efe4d4 0%, #6f725d 100%)'
  },
  custom12_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '短发逆光回眸',
    tip: '推荐都市街拍、逆光背影、松弛感全身照',
    description: '背对镜头站在暖调街道中，身体微侧、头部回眸微笑；右手轻触衣领，左手自然垂放，适合拍松弛优雅的都市逆光背影照。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #f1dfc4 0%, #806f5e 100%)'
  },
  custom13_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '湖畔草帽回眸',
    tip: '推荐湖畔日落、长裙背影、旅行氛围照',
    description: '背对镜头站在湖心栈桥上，身体微侧、头部轻柔回眸；双手在身后握着宽檐草帽，适合拍自然舒展的湖畔日落背影照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom13/custom13_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f2c7a4 0%, #4e5363 100%)'
  },
  custom14_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '山海遮阳回眸',
    tip: '推荐山海旅行、黄金时段、草坡背影照',
    description: '背对镜头站在俯瞰大海的草坡山丘上，身体微侧、头部回眸微笑；一手抬起搭在眉间遮挡阳光，适合拍随性优雅的山海旅行背影照。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #f1c6b6 0%, #6f7f79 100%)'
  },
  custom15_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '古巷提篮回眸',
    tip: '推荐古镇旅行、清晨街拍、松弛背影照',
    description: '背对镜头漫步在古镇鹅卵石小巷中，身体微侧、头部回眸微笑；一手提着编织小篮，另一手轻拢耳畔碎发，适合拍闲适从容的旅行街拍照。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #d6d7bd 0%, #6d7466 100%)'
  },
  custom16_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '露台披肩回眸',
    tip: '推荐屋顶露台、都市夜景、冷暖氛围照',
    description: '背对镜头站在暮色屋顶露台上，身体微侧、头部轻柔回眸；一手搭在栏杆上，另一手挽着披肩自然垂落，适合拍优雅从容的都市夜景人像。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #d8c2b2 0%, #2e3d5f 100%)'
  },
  custom17_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '海边提鞋回眸',
    tip: '推荐海边日出、长裙背影、梦幻旅行照',
    description: '背对镜头站在清晨沙滩上，身体微侧、头部轻柔回眸；一手提着平底凉鞋，另一手提起裙角避开浅浪，适合拍轻盈自然的海边日出人像。',
    badge: '全身',
    gradient: 'linear-gradient(150deg, #f3b7aa 0%, #6fa6b4 100%)'
  },
  custom18_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '自拍侧身撩发',
    tip: '推荐半身自拍、撩发动作、柔和侧光照',
    description: '半身自拍构图，身体微侧、头部自然倾斜；一手轻触耳侧发丝，肘部展开形成柔和三角构图，适合拍松弛自然的撩发半身照。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f2ddd3 0%, #7d6d68 100%)'
  },
  custom19_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '侧身远眺撩发',
    tip: '推荐半身写真、侧身撩发、随性抓拍感',
    description: '半身构图中身体向左微侧约30度，右手抬起轻搭耳侧发丝，面部朝向镜头左前方、目光柔和望向远处，适合拍松弛不刻意的侧身撩发照。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f0e0d5 0%, #7b6f68 100%)'
  },
  custom20_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '窗光浅笑撩发',
    tip: '推荐半身自拍、室内窗光、自然浅笑照',
    description: '半身自拍构图，身体微侧、头部自然倾斜约15度；一手轻触耳侧发丝，眼神柔和直视镜头，适合拍室内窗光下松弛自然的撩发半身照。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f1ddd4 0%, #7a6d66 100%)'
  },
  custom21_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '午后窗边撩发',
    tip: '推荐半身自拍、午后窗光、明亮笑意照',
    description: '半身自拍构图，身体微侧、头部自然倾斜；一手轻触耳侧发丝，面向镜头露出明亮放松的笑意，适合拍午后窗边自然光下的生动抓拍感。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f4dfd4 0%, #806f66 100%)'
  },
  custom22_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '咖啡馆端杯撩发',
    tip: '推荐咖啡馆写真、端杯道具、生活感半身照',
    description: '半身构图中身体微侧面向镜头，左手端着咖啡置于胸前，右手将发丝别到耳后；柔和直视配合温暖微笑，适合拍随性有生活气息的咖啡馆人像。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #d7e2ec 0%, #8b6f58 100%)'
  },
  custom23_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '夕阳胸上自拍',
    tip: '推荐胸上自拍、夕阳逆光、自然笑容照',
    description: '紧凑胸上自拍构图，画面不出现手部或手机，仅通过肩膀微抬暗示自拍；头部微偏、长发垂落肩头，适合拍夕阳逆光下自然真诚的半身自拍感。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #f2c49b 0%, #7e6659 100%)'
  },
  custom24_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '百叶窗触脸自拍',
    tip: '推荐胸上自拍、触脸手势、百叶窗光影照',
    description: '紧凑胸上自拍构图，持机手和手机不入镜；另一只手指尖轻触下颌线，头部向手侧微倾，适合拍午后百叶窗光影下自信明亮的自然自拍感。',
    badge: '半身',
    gradient: 'linear-gradient(150deg, #ead7c5 0%, #715f58 100%)'
  },
  custom25_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '绿裙草帽比耶',
    tip: '推荐连衣裙全身照、正面笑容、活力旅行照',
    description: '身体正对镜头，一脚微微前伸并让重心落在一侧髋部；右手在脸颊旁比出小V手势，左手提着草编遮阳帽，适合拍活泼明亮的正面全身照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom25/custom25_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #c7d8b7 0%, #607858 100%)'
  },
  custom26_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '溪涧提裤行走',
    tip: '推荐森林溪涧、背影行走、自然旅行照',
    description: '背对镜头赤足走在森林浅溪中，头部微低看向水流；一手伸展轻触枝叶，另一手提起阔腿裤脚，适合拍自然灵动的溪涧旅行背影照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom26/custom26_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #e8dcc9 0%, #52654b 100%)'
  },
  custom27_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '海滨墨镜托特包',
    tip: '推荐夏日海滨、正面活力、配饰全身照',
    description: '身体正对镜头，一只膝盖微弯、脚轻快抬起；左手调整头顶墨镜，右手勾着彩色托特包肩带，适合拍明亮爽朗的夏日海滨全身照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom27/custom27_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8ecf2 0%, #315d8a 100%)'
  },
  custom28_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '惊讶捂嘴自拍',
    tip: '推荐胸上自拍、夸张表情、元气手势照',
    description: '紧凑胸上自拍构图，持机手和手机不入镜；另一只手五指张开贴近脸颊，配合圆睁双眼和微启嘴唇，适合拍甜美元气的惊讶抓拍自拍感。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom28/custom28_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f4cbd9 0%, #7e6578 100%)'
  },
  custom29_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '湖畔码头整理辫',
    tip: '推荐湖畔黄昏、码头坐姿、闲适背影照',
    description: '背对镜头坐在木质码头边，赤足悬于湖面；一手撑在身旁木板上，另一手抬起整理辫子，脚尖轻点水面，适合拍慵懒闲适的湖畔黄昏背影照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom29/custom29_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #e9ad74 0%, #5c6d73 100%)'
  },
  custom30_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '珍珠折扇知性',
    tip: '推荐室内正面、折扇道具、优雅知性照',
    description: '身体正对镜头，双腿微交叉站立；右手执半开折扇轻置下颌附近，左手自然搭在腰间，适合拍沉静自信、带配饰层次的优雅正面照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom30/custom30_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #efd2ce 0%, #81706c 100%)'
  },
  custom31_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '庭园踮脚展臂',
    tip: '推荐日式庭园、背影动态、意境全身照',
    description: '背对镜头踮脚站在枯山水庭园踏石上，头部微低保持平衡；双臂向两侧展开，一脚踩稳、一脚向后抬起，适合拍轻盈有韵律感的庭园意境照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom31/custom31_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #c8d1d4 0%, #5d5f5b 100%)'
  },
  custom32_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '相机爱心街头',
    tip: '推荐涂鸦墙街拍、相机道具、创意正面照',
    description: '身体正对镜头自然站立，一手在胸前比出爱心手势，另一手举复古胶片相机凑到眼前；配合眨眼和明亮笑容，适合拍个性活力的街头全身照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom32/custom32_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d7c7a8 0%, #5a5f71 100%)'
  },
  custom33_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '山脊望远镜眺望',
    tip: '推荐徒步登山、背影探索、山谷旅行照',
    description: '背对镜头站在山脊岩石上，一脚踩高屈膝、一脚站稳；一手举望远镜远眺，另一手叉腰勾住裤袢，适合拍干练有探索感的户外登山背影照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom33/custom33_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d6b15a 0%, #4f655b 100%)'
  },
  custom34_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '机车墨镜自拍',
    tip: '推荐街头自拍、墨镜道具、酷飒半身照',
    description: '紧凑胸上自拍构图，持机手和手机不入镜；另一只手轻扶头顶圆形复古墨镜，配合微嘟嘴和冷淡自信眼神，适合拍酷飒俏皮的街头自拍感。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom34/custom34_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #4c5365 0%, #15181f 100%)'
  },
  custom35_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '草甸野餐取物',
    tip: '推荐田园野餐、背影坐姿、温馨生活照',
    description: '背对镜头跪坐在野花草甸的野餐毯上，头部微低整理藤编野餐篮；一手取出法棍，另一手举起草莓端详，适合拍温馨自然的田园野餐背影照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom35/custom35_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c5ef 0%, #8e6a4f 100%)'
  },
  custom36_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '紫衫交扣许愿',
    tip: '推荐正面温柔照、交扣手势、浪漫花景',
    description: '身体正对镜头，一脚尖微微外展、重心偏向一侧；双手举至胸前十指轻轻交扣，配合银色配饰和柔和笑容，适合拍温柔浪漫的正面全身照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom36/custom36_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c4ef 0%, #c98f9d 100%)'
  },
  custom37_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '运动自拍点赞',
    tip: '推荐运动活力、台阶站姿、自拍道具照',
    description: '身体正对镜头，一脚踏上台阶形成不对称动感站姿；右手举手机自拍，左手在腰间竖起大拇指，适合拍青春自信的运动活力全身照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom37/custom37_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f0f3f8 0%, #2d3038 100%)'
  },
  custom38_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '锁骨草帽侧站',
    tip: '推荐全身穿搭、自然站姿、草帽道具照',
    description: '全身入镜自然松弛站立，身体微微侧向一方，重心落于后脚、前脚轻点地面；一手轻触锁骨附近，另一手垂于身侧持握草帽，适合拍柔美从容的全身站姿照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom38/custom38_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #efe2c8 0%, #7a6658 100%)'
  },
  custom39_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '翡翠折扇提裙',
    tip: '推荐轻奢写真、折扇道具、优雅全身照',
    description: '全身入镜优雅站立，一手持闭合复古折扇轻置下颌附近，另一手轻提裙摆露出脚踝；双脚芭蕾式交叉、前脚脚尖点地，适合拍典雅精致的室内轻奢风写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom39/custom39_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #0f5f4d 0%, #c7b08b 100%)'
  },
  custom40_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '牛仔咖啡台阶',
    tip: '推荐都市街拍、咖啡道具、休闲穿搭照',
    description: '全身入镜随性站立，一手持外带咖啡杯靠近胸前，另一手拇指勾入牛仔裤前口袋；一腿承重、一腿屈膝搭在身后低矮台阶上，适合拍休闲时髦的都市街拍照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom40/custom40_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8dee7 0%, #31445d 100%)'
  },
  custom41_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '画笔贝雷舞姿',
    tip: '推荐艺术馆写真、画笔道具、文艺动态照',
    description: '全身入镜呈艺术感动态姿态，一手高举画笔如指挥棒，另一手搭于腰间；上半身微微后仰向上凝望，一腿承重、一腿屈膝向后抬起脚尖绷直，适合拍文艺别致的创意写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom41/custom41_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #efe8dc 0%, #2f2c2a 100%)'
  },
  custom42_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '羽毛球挥拍弓步',
    tip: '推荐运动风写真、户外活力、挥拍动态照',
    description: '全身入镜呈运动发力姿态，一手高举羽毛球拍挥拍，另一手向前伸展追踪球路；前腿屈膝跨出、后腿蹬直脚尖点地，适合拍动感利落的户外运动写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom42/custom42_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f6f8fb 0%, #1f3d68 100%)'
  },
  custom43_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '蕾丝阳伞花园',
    tip: '推荐少女风写真、花园阳伞、浪漫全身照',
    description: '全身入镜浪漫站立，双手轻抬至胸前共持蕾丝阳伞搭于肩头，双眼微闭；一腿承重，另一腿屈膝向后轻抬、脚尖似触非触地面，适合拍诗意梦幻的花园少女风写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom43/custom43_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8b5c0 0%, #8d6b78 100%)'
  },
  custom44_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '海边草帽白裙',
    tip: '推荐海边度假、长裙穿搭、松弛全身照',
    description: '站在海边沙滩上，重心落在右腿，左腿微弯向前点地形成 S 型曲线；左手扶宽檐草帽，右手轻触锁骨附近发丝，适合拍松弛自然的度假氛围全身照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom44/custom44_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f4efe4 0%, #6ca5b8 100%)'
  },
  custom45_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '草地草帽锁骨',
    tip: '推荐草地自然光、草帽道具、松弛全身照',
    description: '站在草地上呈自然 S 形站姿，重心落在后腿、前脚微微向前点地；左手握草帽垂在身侧，右手指尖轻触锁骨，适合拍温暖自然的松弛全身照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom45/custom45_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #efe4c9 0%, #6f8f56 100%)'
  },
  custom46_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '职场西装领口',
    tip: '推荐职场写真、杂志风、力量感站姿',
    description: '全身入镜呈干练力量感站姿，一手整理西装领口，另一手背于身后持黑色文件夹；前腿微屈跨出、后腿蹬直脚跟离地，适合拍利落大气的职场杂志风写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom46/custom46_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #5a5b60 0%, #7d2336 100%)'
  },
  custom47_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '草地盘坐晒太阳',
    tip: '推荐草地坐姿、松弛感写真、温暖逆光照',
    description: '坐在草地上双腿交叉盘坐，身体微微后仰，双手撑在身后草地上；头部微仰、双眼轻闭，适合拍温暖惬意的户外松弛感坐姿照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom47/custom47_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #ece2d2 0%, #4f6f43 100%)'
  },
  custom48_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '礁石粉裙侧坐',
    tip: '推荐海边度假、礁石坐姿、柔美长裙照',
    description: '侧身坐在海边礁石上，双腿并拢向一侧延伸、脚尖微绷；一手撑在身后保持平衡，另一手搭在膝上扶宽檐草帽，适合拍慵懒优雅的海边度假坐姿照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom48/custom48_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #efb7ac 0%, #6ca1b5 100%)'
  },
  custom49_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '风衣拢发行走',
    tip: '推荐通勤街拍、行走抓拍、风衣穿搭照',
    description: '捕捉行走中的动态瞬间，一手随步伐自然前摆，另一手抬起轻拢耳后发丝；前腿迈出脚跟落地、后腿蹬地脚尖将离地，适合拍洒脱利落的通勤街拍照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom49/custom49_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #c7945e 0%, #314b67 100%)'
  },
  custom50_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '草地相机迈步',
    tip: '推荐草地行走、相机道具、生活感抓拍',
    description: '草地上大步行走的瞬间，一脚踩稳、一脚轻盈抬起，身体微微前倾；左手随步伐前摆，右手举复古胶片相机靠近胸前，适合拍活力自然的生活感抓拍。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom50/custom50_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #e8dfcf 0%, #b5673e 100%)'
  },
  custom51_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '木凳相机休闲',
    tip: '推荐咖啡馆写真、相机道具、松弛坐姿',
    description: '坐在低矮木凳上，一手轻搭膝头，另一手举复古胶片相机凑近眼前；一腿屈膝踩地，另一腿前伸脚踝交叠，适合拍慵懒舒适的日常休闲写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom51/custom51_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d9c8ae 0%, #6b7453 100%)'
  },
  custom52_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '海边蹲姿拾贝',
    tip: '推荐海边旅行、蹲姿互动、自然探索感',
    description: '蹲在海水与沙滩交界处，一腿膝盖轻触湿沙，另一腿弯曲支撑；一手在沙面划出纹路，另一手捏着小贝壳低头端详，适合拍灵动静谧的海边探索感写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom52/custom52_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #eee4d2 0%, #6aa5b8 100%)'
  },
  custom53_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '晚霞海滩拎鞋',
    tip: '推荐海边日落、行走抓拍、松弛度假照',
    description: '日落海滩上悠然漫步，一脚向前迈出陷入细沙、后脚刚离地；一手插在裤袋中，另一手拎着人字拖自然垂落，适合拍静谧诗意的海边行走照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom53/custom53_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #1d365a 0%, #e58a74 100%)'
  },
  custom54_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '跑动挥手活力',
    tip: '推荐运动风写真、跑动抓拍、户外活力照',
    description: '全身入镜捕捉轻快跑动瞬间，一手高举向镜头挥舞，另一臂自然屈肘摆动；一腿高抬屈膝腾空，另一腿蹬地将离地，适合拍灿烂有感染力的运动活力照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom54/custom54_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #ff8a8f 0%, #252a32 100%)'
  },
  custom55_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '草地蹲姿看花',
    tip: '推荐草地自然光、蹲姿互动、生活感写真',
    description: '蹲在草地上双膝弯曲、身体低伏，一手伸向前方触碰雏菊，另一手自然搭在膝盖上；头部微侧、目光低垂看向花朵，适合拍宁静温柔的自然生活感写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom55/custom55_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8b2bb 0%, #6d8f55 100%)'
  },
  custom56_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '蹲姿撸猫互动',
    tip: '推荐宠物互动、日系休闲、低伏蹲姿照',
    description: '全身入镜低伏蹲姿，一手撑地五指张开保持平衡，另一手轻抚身旁白色小猫；双腿深屈膝蹲低、脚跟微抬，适合拍生动温馨的宠物互动写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom56/custom56_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #b9d7e8 0%, #b85b4b 100%)'
  },
  custom57_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '海水踢浪嬉戏',
    tip: '推荐夏日海边、踢水动态、活力旅行照',
    description: '站在齐踝深海水中嬉戏，一腿向前踢起水花，双臂向两侧张开保持平衡；一手弹起水花、另一手高举张开，适合拍自由欢快的夏日海边动态照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom57/custom57_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #ffd13d 0%, #40a9cf 100%)'
  },
  custom58_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '草地慢跑腾空',
    tip: '推荐草地跑步、运动活力、腾空抓拍',
    description: '草地上轻盈慢跑的瞬间，双脚同时离地形成腾空姿态；双臂自然弯曲随节奏摆动，高马尾向后飞扬，适合拍青春自由的户外运动抓拍。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom58/custom58_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #9fbf9a 0%, #41474d 100%)'
  },
  custom59_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '栈道相机侧站',
    tip: '推荐旅行抓拍、相机道具、自然侧站照',
    description: '自然放松地站在木质栈道上，身体重心偏向一侧形成 S 形曲线；一手将复古胶片相机举至胸前，另一手随意插入口袋，双脚前后错落站立，适合拍从容松弛的旅行抓拍照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom59/custom59_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d4b98a 0%, #536c78 100%)'
  },
  custom60_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '公路草帽行走',
    tip: '推荐公路旅行、行走抓拍、草帽道具照',
    description: '轻快行走在空旷公路上，一腿向前跨出、对侧手臂顺势后摆；右手垂于身侧轻握编织草帽，左手抬起将发丝拢至耳后，适合拍松弛愉悦的旅行动态照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom60/custom60_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d9b16f 0%, #65747b 100%)'
  },
  custom61_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '石桥相机侧站',
    tip: '推荐旅行抓拍、相机道具、桥上自然站姿',
    description: '自然站在石桥上，身体微微侧向镜头；左手轻搭桥栏，右手持复古相机垂于身前，右腿微屈脚尖点地，头部略转向远方，适合拍不经意的旅行抓拍照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom61/custom61_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #c8b08a 0%, #586b73 100%)'
  },
  custom62_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '台阶拍立得坐姿',
    tip: '推荐户外街拍、台阶坐姿、拍立得道具照',
    description: '随性坐在户外石阶上，一腿向前伸展搭在下方台阶，另一腿屈膝撑起并将手肘搭在膝盖上；左手举拍立得相机，右手撩拨头发，适合拍酷感十足的街头坐姿写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom62/custom62_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #22262f 0%, #c77b4d 100%)'
  },
  custom63_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '站台行李箱坐姿',
    tip: '推荐复古旅行、站台场景、行李箱坐姿照',
    description: '悠然坐在火车站台的复古行李箱上，身体微微侧转，一条腿搭在另一条腿脚踝处；双手轻搭行李箱边缘，微微回头望向铁轨远方，适合拍带有旅途期待感的复古写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom63/custom63_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #c28d5a 0%, #5b5f68 100%)'
  },
  custom64_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '台阶雨伞咖啡',
    tip: '推荐城市台阶、咖啡雨伞道具、知性街拍',
    description: '以对角线站姿立于现代城市石阶上，右脚踩高一级台阶、左脚落低一级台阶；左手端外带咖啡，右手握透明雨伞轻搭肩头，适合拍优雅知性的情绪感街拍。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom64/custom64_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c0a1 0%, #75846f 100%)'
  },
  custom65_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '石桥读书侧坐',
    tip: '推荐石桥场景、读书道具、慵懒文艺坐姿',
    description: '侧身坐在石桥栏杆边缘，一腿自然垂落悬空，另一腿屈膝踩在栏杆边沿；一手捧着翻开的平装书搁在膝上，另一手抬起调整头顶墨镜，适合拍慵懒午后的文艺旅行照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom65/custom65_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #9eb09a 0%, #5c6b78 100%)'
  },
  custom66_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '石桥系鞋带蹲姿',
    tip: '推荐石桥场景、运动街拍、蹲姿系鞋带动作',
    description: '活泼地蹲在石桥上，一脚屈膝跪地、另一脚踩实桥面；一手向下系白色运动鞋鞋带，另一手撑在膝上保持平衡，适合拍青春动感的街头运动风写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom66/custom66_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8d1bd 0%, #66714d 100%)'
  },
  custom67_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '站台立柱读书',
    tip: '推荐复古站台、靠柱站姿、书本咖啡道具',
    description: '斜倚在火车站台复古立柱旁，一侧肩膀轻靠柱面，同侧腿屈膝脚底贴柱；一手举翻开的书至胸前，另一手握热咖啡垂于腰际，适合拍沉静知性的候车街拍。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom67/custom67_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #b8a27b 0%, #32353a 100%)'
  },
  custom68_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '蓝调台阶靠墙',
    tip: '推荐夜景人像、台阶靠墙、仙女棒氛围照',
    description: '倚靠在幽静小巷老石阶旁，背部轻贴侧墙，一脚平踩台阶、另一脚屈膝蹬在身后墙壁；左手高举燃烧的仙女棒，右手将复古手账本按在胸前，适合拍蓝调时刻的电影感夜景人像。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom68/custom68_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #1d2b45 0%, #d6a344 100%)'
  },
  custom69_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '湖边提鞋踢水',
    tip: '推荐湖边浅水、提鞋道具、度假感动态照',
    description: '赤足踏入清澈湖水中，一手提着脱下的白色帆布鞋，另一手轻提长裙裙摆至脚踝上方；一只脚俏皮轻踢水面，适合拍明亮治愈的夏日湖畔度假照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom69/custom69_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d7b6b2 0%, #7fa0a2 100%)'
  },
  custom70_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '古树咖啡靠站',
    tip: '推荐秋日森林、古树倚靠、咖啡道具照',
    description: '斜倚在粗壮古树旁，一侧肩膀轻靠树干，双腿交叉靴尖点地；一手插在毛衣口袋中，另一手捧着热咖啡贴近胸前，适合拍深秋森林的温暖静谧写真。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom70/custom70_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #9a4a32 0%, #3e2d25 100%)'
  },
  custom71_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '栈桥写生盘坐',
    tip: '推荐湖边栈桥、盘腿坐姿、写生苹果道具',
    description: '盘腿坐在延伸至湖心的木质栈桥上，速写本摊开放在膝上；一手握铅笔勾勒线条，另一手举着咬过的苹果停在嘴边，适合拍安静专注的湖边写生氛围照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom71/custom71_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #c4b79a 0%, #596b61 100%)'
  },
  custom72_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '森林树枝侧坐',
    tip: '推荐春日森林、树枝坐姿、清新俏皮写真',
    description: '侧身坐在森林中粗壮的横向树枝上，双腿自然垂落轻晃；一手扶着树枝保持平衡，另一手向上探出轻触头顶叶片，适合拍清新灵动的春日森林照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom72/custom72_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #b9d7c5 0%, #4d6b45 100%)'
  },
  custom73_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '芦苇浅滩漫步',
    tip: '推荐湖边浅滩、芦苇互动、手杖道具照',
    description: '赤足行走在湖边浅滩，一手拄长木质手杖保持平衡，另一手向外伸展轻拂岸边芦苇顶端；一脚踏入浅水荡开涟漪，适合拍静谧自然的湖畔漫步照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom73/custom73_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #e5dfcf 0%, #9b6c4b 100%)'
  },
  custom74_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '野餐垫托腮趴姿',
    tip: '推荐湖岸野餐、趴姿托腮、慵懒少女感照片',
    description: '趴在湖岸草地的格纹野餐垫上，双肘撑地、双手托腮，双腿在身后屈膝翘起并交叉脚踝；面前摆着书、法棍和葡萄，适合拍慵懒午后的野餐氛围照。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom74/custom74_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c0df 0%, #6f7d58 100%)'
  },
  custom75_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '前置自拍撩发',
    tip: '推荐居家日常、咖啡厅窗边、卧室暖光、朋友圈氛围感自拍',
    description: '模拟前置摄像头自拍视角的半身照：一手持手机伸向画框外，画面中不出现手机，另一只手轻触耳侧发丝，眼神柔和直视镜头，嘴唇微启，整体氛围慵懒而有故事感。适合场景：居家日常、咖啡厅窗边、卧室暖光环境、朋友圈氛围感照片、小红书生活分享。关键动作：持手机的手臂向斜上方 45° 自然伸展出画框，另一只手用指尖轻触耳侧或撩发，手指自然微张不要并拢，肩膀微微下沉放松。角度要点：手机略高于眼睛水平线，俯拍约 30°~45°，下巴微收，眼睛看向手机屏幕中的自己而非镜头外。注意事项：避免手臂完全伸直导致僵硬，肘部保持自然微弯；触发的手不要用力抓头发，指尖轻搭即可；光线尽量从侧前方来，避免顶光在眼下形成阴影；背景简洁有层次感即可，不要太杂乱抢镜。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom75/custom75_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #ead7c8 0%, #7c6256 100%)'
  },
  custom76_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '侧身相机锁骨',
    tip: '推荐咖啡馆靠窗、书店、艺术街区、室内窗边文艺半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微微侧转约 30°，面部朝向镜头斜侧方，眼神不直视镜头，表情松弛自然、略带若有所思的神态。左手轻触锁骨下方，手指自然微曲不并拢；右手持一台复古胶片相机置于胸前，手腕放松，手肘自然下垂。长发自然垂落于肩侧，身着米色针织毛衣，靠近镜头一侧的肩膀微微下沉，整体富有故事感和文艺气息。适合场景与拍摄要点：最适合在咖啡馆靠窗位置、书店、艺术街区或室内窗边等有自然侧光的环境拍摄，整体走文艺氛围路线。拍摄时身体不要正对镜头，微侧 30° 到 45° 让肩膀形成自然斜线；脸转向光源一侧、下巴微收、眼神看向镜头外的侧下方或远方，避免直视镜头。手不知道放哪就给它一个道具，相机、咖啡杯、书或手机都可以，一只手拿道具置于胸前，另一只手轻触锁骨或领口，手指自然弯曲不要绷直。表情不刻意笑，嘴唇微闭或轻启，眼神放空带一点故事感。光线优先选择侧光或侧逆光，让面部有明暗层次，避免正面平光。构图用 3:4 竖幅，头顶适当留白，下方裁切到胸部以下，背景虚化突出人物主体。核心口诀：侧身、不看镜头、手上有事做、侧光。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom76/custom76_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #e2d4bf 0%, #6d6259 100%)'
  },
  custom77_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '冷淡半心自拍',
    tip: '推荐夜晚卧室暖光、清吧角落、情绪感朋友圈、冷淡风半身自拍',
    description: '模拟前置摄像头自拍视角的半身照：一手持手机伸向画框外，另一只手在脸颊旁比出慵懒的半心手势，手指优雅微曲。眼神半阖直视镜头，嘴唇自然闭合带一点微嘟感，眉梢轻挑，整体气质清冷又带一丝慵懒的疏离感。适合场景：夜晚卧室暖光氛围照、酒吧或清吧角落、情绪感朋友圈、小红书冷淡风人像。关键动作：持手机手臂向斜上方自然伸展出画框；另一只手在脸颊旁比半心手势，手指不要完全伸直，保持自然弧度；肩膀放松下沉，锁骨自然露出。角度要点：手机略高于眼睛，俯拍约 30°~45°，下巴微收，眼神看向屏幕中的自己，半阖的眼睑是关键，不要瞪眼。注意事项：半心手势不要贴脸太紧，留一点空隙更自然；低发髻搭配几缕碎发增加慵懒感；暖色侧光从一侧打来，营造明暗对比；配饰如细链项链和小耳环点到为止，不抢镜。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom77/custom77_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #2d2628 0%, #b58a68 100%)'
  },
  custom78_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '耳环墨镜低眸',
    tip: '推荐咖啡馆窗边、美术馆、书店、午后室内情绪半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微侧，面部朝向镜头斜下方，眼神低垂不直视镜头，表情沉静内敛、带一丝若有所思的疏离感。右手抬起轻触耳畔，手指自然微曲做调整耳环的动作，手腕放松不僵硬；左手持一副圆形墨镜松松地搭在胸前，手指自然弯曲不并拢。佩戴金色细项链和小巧耳环，身着米色亚麻衬衫，长发自然垂落，双手各有独立动作、互不重复，整体姿态松弛而有层次。适合场景与拍摄要点：最适合在咖啡馆窗边、美术馆、书店或午后阳光斜照的室内角落拍摄，整体走安静文艺、带一点疏离感的情绪风。拍摄时身体微侧不正向镜头，脸转向光源一侧、下巴微收、眼神低垂看向侧下方或手中的道具，避免直视镜头。手部是这张照片的灵魂，两只手各做不同的事，一只手调整耳环或撩头发，另一只手松松拿着墨镜、书或咖啡杯置于胸前，手指自然弯曲不要用力握紧。配饰方面细项链和小耳环增加精致感，墨镜作为道具丰富手部层次。表情不笑，嘴唇微闭或轻启，眼神放空或低垂，带一点在想事情的状态。光线优先选择柔和侧光或窗光，避免正面强光。构图 3:4 竖幅，头顶留白，下方裁切到胸部以下，背景虚化突出人物。核心口诀：双手各忙各的、眼神低垂不看镜头、配饰点睛、柔光侧打。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom78/custom78_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #dfd0bd 0%, #7c7268 100%)'
  },
  custom79_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '领口惊喜自拍',
    tip: '推荐阳台露台午后阳光、户外咖啡座、旅行随拍、生活感自拍',
    description: '模拟前置摄像头自拍视角的半身照：一手持手机伸向画框外，另一只手轻捏锁骨附近的衬衫领口，手指自然放松。眼睛睁大直视镜头，嘴唇微张呈轻柔的 o 形，眉梢轻抬，表情带一点惊喜和好奇感，生动不死板。适合场景：阳台或露台午后阳光、户外咖啡座、旅行随拍、朋友圈日常分享、小红书生活感照片。关键动作：持手机手臂向斜上方自然伸展出画框；另一只手轻捏领口靠近锁骨处，手指微曲不并拢，手腕放松；一侧头发别到耳后露出耳饰。角度要点：手机略高于眼睛，俯拍约 30°，下巴微收，眼睛睁大看向屏幕中的自己，嘴唇微张是关键，不要太刻意，自然放松即可。注意事项：捏领口的手不要用力抓，指尖轻触即可；叠戴项链增加层次感但不要太繁复；午后侧光让肤色通透，背景绿植虚化营造景深；宽松衬衫不扣满，露出内搭白背心，随性又得体。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom79/custom79_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c7ad 0%, #6f7f62 100%)'
  },
  custom80_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '撩发触链情绪',
    tip: '推荐黄昏窗边、金色暖光、户外逆光、温柔电影感半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微侧，面部微微上扬朝向镜头左上方，眼神迷离放空、嘴唇微启，表情带一丝淡淡的忧郁和出神感，不刻意微笑。左手抬起至太阳穴附近，手指自然张开穿插于发丝之间做撩发动作，手腕柔软放松；右手轻搭在锁骨处，指尖轻轻触碰颈间的银色细项链，手指优雅微曲。佩戴双层银色细项链和左手腕细手链，身着奶油色真丝衬衫，袖口微蓬松，双手一高一低各做不同动作，姿态层次丰富。适合场景与拍摄要点：最适合在黄昏时分的窗边、有金色暖光的室内角落、或者户外逆光场景下拍摄，整体走温柔情绪风，带一点电影感的忧郁氛围。拍摄时身体微侧不正向镜头，面部微微上扬、眼神看向斜上方光源处，嘴唇微启不要紧闭，营造出神或发呆的状态。手部是核心亮点，两只手一高一低各做不同的事，高处的手穿插在发丝间做撩发或整理头发，手指自然张开、手腕柔软；低处的手轻搭在锁骨或触碰项链，指尖微曲。配饰方面，细项链和手链在光线照射下会产生微妙反光，增加画面精致度。光线优先选择黄昏时分的金色侧光或逆光，让发丝边缘产生轮廓光，面部有柔和暖调过渡。表情不笑，嘴唇微启、眼神放空，带一点在想心事的疏离感。构图 3:4 竖幅，头顶适当留白，下方裁切到胸部以下，背景虚化突出人物。核心口诀：一手撩发一手触链、眼神上扬放空、金色暖光侧打、嘴唇微启不笑。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom80/custom80_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f0ddbd 0%, #8c7660 100%)'
  },
  custom81_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '闭眼拈花静谧',
    tip: '推荐清晨窗边、安静卧室、花房、日系治愈情绪半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微侧，面部正对镜头但双眼轻闭，表情宁静平和、带一种向内沉浸的冥想感，不刻意微笑。左手抬起轻贴脸颊，指尖若即若离地触碰下颌线，手指自然微曲、手腕柔软；右手持一小束干花满天星松松地捏在指间置于胸前，手指优雅弯曲不并拢。佩戴珍珠项链和小巧珍珠耳钉，身着灰粉色羊绒开衫内搭白色真丝吊带，长发自然垂落，双手一高一低、一触一持各做不同动作，闭眼神态让画面充满静谧的情绪张力。适合场景与拍摄要点：最适合在清晨窗边、安静卧室、花房或阳光柔和的室内角落拍摄，整体走温柔静谧的情绪风，带一点日系治愈感。拍摄时身体微侧不正向镜头，面部正对光源但双眼轻闭，营造沉浸在自己世界里的氛围，嘴唇自然闭合不要用力抿紧。高处的手轻贴脸颊或下颌线，指尖若即若离不要压实；低处的手松松捏一小束干花、一封信或一片叶子置于胸前。珍珠项链和耳钉在柔光下泛出温润光泽，干花道具增加自然清新气息。光线优先选择清晨柔和的正面偏侧光，让闭眼面部有均匀柔光包裹，避免强烈阴影。核心口诀：闭眼不笑、一手贴脸一手拈花、柔光正面打、珍珠点缀。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom81/custom81_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #e3c7c8 0%, #8d7b78 100%)'
  },
  custom82_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '雨窗托下巴自拍',
    tip: '推荐雨天窗边、独处时光、情绪感朋友圈、音乐封面风自拍',
    description: '模拟前置摄像头自拍视角的半身照：一手持手机伸向画框外，另一只手托在下巴下方，食指轻触下唇，拇指抵住下颌线，手指优雅散开，充满情绪感的杂志风姿势。眼神略微越过镜头望向远方，嘴唇自然放松微微向下，眉头轻蹙，整体氛围沉静而略带忧郁。适合场景：雨天窗边、独处时光、情绪感朋友圈、小红书氛围感人像、音乐封面风照片。关键动作：持手机手臂向斜上方自然伸展出画框；另一只手托下巴，食指轻触下唇，其余手指自然散开不并拢，手腕放松；下巴微收，眼神不直视镜头而是略偏上方或远方。角度要点：手机略高于眼睛，俯拍约 30°，眼神焦点偏离镜头是关键，看向屏幕边缘或窗外，营造被偷拍的叙事感。注意事项：托下巴的手不要用力挤压脸部，轻触即可；齐颌短发一侧别耳后露出耳饰和下颌线；雨窗水珠作为背景增加故事感和氛围；淡紫色羊绒衫柔和温暖，与阴雨天冷调形成对比；银质项圈和食指戒指点缀细节但不喧宾夺主。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom82/custom82_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #9aa2b1 0%, #6f657c 100%)'
  },
  custom83_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '点额抓领高冷',
    tip: '推荐摄影棚、暗调空间、工业风建筑、杂志封面风半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微侧但面部正对镜头，眼神直视镜头，嘴唇微启，表情冷峻自信、带一丝不羁的时尚杂志感，不刻意微笑。左手抬起至太阳穴旁，食指轻点太阳穴，其余四指自然张开呈扇形散开，手腕放松；右手抓住衬衫领口边缘置于胸前，手指微曲带一点张力，像在整理衣领又像在宣示态度。佩戴黑色天鹅绒颈链和银色几何耳坠，身着深酒红色缎面衬衫，V 领微敞，双手一高一低、一松一紧各做不同动作，直视镜头的眼神让画面充满强烈存在感和时尚张力。适合场景与拍摄要点：最适合在摄影棚、暗调空间、工业风建筑或有戏剧性光影的室内场景拍摄，整体走高冷时尚风，带一点杂志封面的气场。拍摄时身体微侧但面部正对镜头，眼神直视镜头不要闪躲，嘴唇微启不要紧闭，营造自信甚至带一点挑衅感的氛围。高处的手食指轻点太阳穴，其余手指自然张开呈扇形，低处的手抓住衣领边缘，手指微曲带一点张力。黑色颈链和几何耳坠增加暗黑时尚感，与深酒红衬衫形成色彩对比。光线优先选择单侧戏剧性强光，让面部产生明显明暗分割，暗色背景让主体更加突出。核心口诀：直视镜头不闪躲、一手点额一手抓领、单侧强光暗背景、颈链耳坠点睛。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom83/custom83_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #4b2028 0%, #161317 100%)'
  },
  custom84_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '触唇捧杯抓拍',
    tip: '推荐咖啡馆、家中沙发角落、书店窗边、日系生活感抓拍',
    description: '人物呈上半身 3:4 竖幅构图，身体微微前倾，面部朝向镜头斜侧方，眉毛轻扬、嘴唇微启，表情带着一丝好奇和刚刚注意到什么的抓拍感，自然不刻意。左手抬起靠近唇边，食指轻触下唇，其余手指自然蜷曲，像在想事情时被叫住的瞬间；右手双手捧着冒热气的白色陶瓷咖啡杯置于胸前，手指自然包裹杯身取暖。佩戴细金链项链和小金圈耳环，身着燕麦色宽松高领针织毛衣，长发随意垂落，双手一上一下、一触一捧各做不同动作，前倾的身体姿态让画面充满生活气息和真实抓拍感。适合场景与拍摄要点：最适合在咖啡馆、家中沙发角落、书店窗边或任何有温暖生活气息的室内场景拍摄，整体走日系生活感抓拍风，带一点被偷拍的日常瞬间真实感。拍摄时身体微微前倾靠近镜头，营造亲近感和代入感，面部朝向斜侧方但眼神可以看向镜头或侧方，眉毛轻扬、嘴唇微启，像刚好注意到有人在拍你的自然反应。高处的手食指轻触下唇，像在想事情被打断的瞬间，手指自然蜷曲不要刻意摆造型；低处的手双手捧一杯热咖啡或热茶杯置于胸前，手指自然包裹杯身，既能取暖又能让手有自然着力点。冒热气的咖啡杯是生活感的核心道具，热气让画面更有温度和动态感。光线优先选择柔和晨光或窗光，暖调为主，让画面有被阳光包裹的温馨感。构图 3:4 竖幅，头顶适当留白，下方裁切到胸部以下，背景虚化但保留一点书架或窗景暗示。核心口诀：身体前倾靠近镜头、一手触唇一手捧杯、热咖啡冒热气、眉毛轻扬嘴唇微启。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom84/custom84_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d7c0a1 0%, #7d6a54 100%)'
  },
  custom85_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '扎发贴心诗意',
    tip: '推荐黄昏金色窗边、户外逆光草地、海边日落、浪漫诗意半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微侧，面部微微上扬、眼神温柔地望向远方斜上方，嘴唇轻闭带一丝若有若无的忧郁弧度，表情充满诗意和出神感，不刻意微笑。左手抬起至脑后，手指松散地穿插在发丝间，像正在扎头发的中途动作，手肘优雅外展；右手平贴在锁骨下方的胸口，掌心贴胸、五指自然微张，像在感受自己的心跳。佩戴银色小盒吊坠项链和淡水珍珠耳坠，身着浅薰衣草紫羊绒高领毛衣，长发松散垂落，双手一高一低、一后一前各做不同动作，金色逆光在发丝边缘形成轮廓光。适合场景与拍摄要点：最适合在黄昏金色时刻的窗边、户外逆光草地、海边日落时分或有温暖逆光的室内场景拍摄，整体走浪漫诗意风，带一点电影镜头般的柔美感。拍摄时身体微侧不正向镜头，面部微微上扬、眼神温柔望向远方斜上方，嘴唇轻闭不要抿紧，营造出神或思念的浪漫氛围。高处的手伸到脑后松散穿插在发丝间，像正在扎头发或整理发型的自然中途动作，手肘外展形成优美三角形构图；低处的手平贴胸口，掌心贴胸、五指微张，像感受心跳或许愿。光线优先选择黄昏金色时刻的逆光或侧逆光，让发丝边缘形成金色轮廓光，面部用柔和反光或补光避免过暗。核心口诀：一手扎发一手贴心、眼神望远嘴唇轻闭、金色逆光打轮廓、珍珠银链点缀。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom85/custom85_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d4c0dc 0%, #7a6b86 100%)'
  },
  custom86_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '苹果眨眼自拍',
    tip: '推荐厨房日常、健康饮食记录、俏皮朋友圈、水果主题创意自拍',
    description: '模拟前置摄像头自拍视角的半身照：一手持手机伸向画框外，另一只手举着一颗红苹果贴近脸颊，手指优雅包裹苹果，像在俏皮地对比苹果肌。一只眼微眯做眨眼状，另一只眼睁大，嘴唇歪歪地勾起一边，表情狡黠又灵动。适合场景：厨房日常、健康饮食记录、俏皮风朋友圈、小红书生活碎片分享、水果主题创意自拍。关键动作：持手机手臂向斜上方自然伸展出画框；另一只手举苹果贴近脸颊，手指自然包裹果实，手腕微转展示手表和拇指戒；歪嘴笑只抬一边嘴角，配合单眼微眨，俏皮不刻意。角度要点：手机略高于眼睛，俯拍约 30°，苹果与脸同框形成趣味对比；眨眼和歪嘴笑要自然，不要用力挤眼或过度拉扯嘴角。注意事项：苹果选红色与白衬衫形成鲜明色彩对比；袖子卷到肘部露出手腕配饰增加细节；厨房白瓷砖和木砧板背景干净明亮；低马尾中分利落不拖沓；整体风格轻松俏皮，适合展现活泼个性。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom86/custom86_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f4f0e7 0%, #c84035 100%)'
  },
  custom87_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '皮衣抓领酷感',
    tip: '推荐城市天台日落、音乐节现场、街头穿搭、酷女孩杂志硬照',
    description: '模拟前置摄像头自拍视角的半身照：一手持手机伸向画框外，另一只手抓住黑色皮衣领口拉至下巴处，手指弯曲扣住翻领，指节分明，多枚银戒清晰可见，整体是酷感十足的硬朗姿态。眼神凌厉眯起直视镜头，嘴唇紧抿，下颌咬紧，鼻翼微张，像一场充满力量感的对视。适合场景：城市天台日落时分、音乐节或演唱会现场、街头风穿搭记录、小红书酷女孩风格照、杂志风硬照。关键动作：持手机手臂向斜上方自然伸展出画框；另一只手抓住皮衣领口上拉至下巴高度，手指弯曲扣住翻领边缘，展示指间银戒；湿发后梳露出完整面部，强化凌厉感。角度要点：手机略高于眼睛，俯拍约 25°~30°，眼神眯起聚焦于屏幕，下颌微抬增加气场；嘴唇紧抿不笑，配合咬紧的下颌线传递力量感。注意事项：抓领口的手不要握拳，手指自然弯曲扣住翻领即可；湿发造型搭配皮衣统一酷感调性；黄昏城市天际线的暖橙光与黑色皮衣形成冷暖对比；银链和银戒增加细节层次，整体风格硬朗不刻板。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom87/custom87_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #1f1f22 0%, #c06c3d 100%)'
  },
  custom88_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '托腮持本思考',
    tip: '推荐工作室、图书馆、咖啡馆靠窗、书房、创意思考抓拍',
    description: '人物呈上半身 3:4 竖幅构图，身体微侧，面部微微上扬、眼神望向斜上方，嘴唇微启，表情带着思考中的出神感，像在寻找灵感，不刻意微笑。左手托在下巴下方，食指沿下颌线伸展、拇指轻托下巴、其余手指自然蜷曲，是经典的思考者手势；右手持一本摊开的小笔记本贴在胸前，拇指压住内页，其余手指自然散开覆在封面上。佩戴细皮绳绿松石吊坠项链和素银耳钉，身着鼠尾草绿亚麻衬衫，袖口随意卷起，双手一托一持、一静一动各做不同动作，画面充满创意工作者沉浸思考的真实氛围。适合场景与拍摄要点：最适合在工作室、图书馆、咖啡馆靠窗座位、书房或任何有自然光和创作氛围的室内场景拍摄，整体走创意思考风，带一点灵感来了的抓拍感。拍摄时身体微侧不正向镜头，面部微微上扬、眼神望向斜上方，像在脑海中搜寻某个想法，嘴唇微启不要紧闭。高处的手托下巴，食指沿下颌线自然伸展、拇指轻托下巴，手指不要用力握拳，保持松弛支撑感；低处的手持一本摊开的笔记本或速写本贴在胸前，拇指压住内页像刚写完或正要写什么，手指自然散开。光线优先选择柔和自然日光，正面偏侧，干净通透，避免强烈阴影。核心口诀：一手托腮一手持本、眼神向上嘴唇微启、自然光通透、亚麻绿松石点缀。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom88/custom88_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #b8c4a7 0%, #6f7964 100%)'
  },
  custom89_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '斜睨撩发抓领',
    tip: '推荐摄影棚、暗调工业空间、夜晚城市街头、高定时尚戏剧光半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微侧，下巴微抬，眼神锐利地斜睨左方，嘴唇微启，表情冷峻强势、带一种不怒自威的时尚气场，不刻意微笑。左手抓住露肩黑色针织衫的领口边缘靠近锁骨处，手指用力、指节微显张力；右手大幅度向后撩拨长发，五指张开穿插在发丝间，动作充满动态感和力量感。佩戴银色宽手镯和层叠银色链式颈链，身着黑色露肩针织衫，长发在撩拨中飞扬。双手一抓一撩、一紧一张各做不同动作，单侧戏剧性强光在面部形成大胆明暗分割，画面充满高定时装大片的力量感和视觉冲击力。适合场景与拍摄要点：最适合在摄影棚、暗调工业空间、夜晚城市街头或有戏剧性灯光的室内场景拍摄，整体走高定时尚风，带一点别惹我的强大气场。拍摄时身体微侧但下巴微抬，眼神锐利地斜睨一侧不要直视镜头，嘴唇微启，营造冷峻自信甚至带一点攻击性的氛围。高处的手大幅度向后撩拨长发，五指张开、动作幅度要大，让头发产生飞扬的动态感，手腕用力但手指保持舒展；低处的手抓住领口边缘，手指用力、指节微显张力，像在掌控自己的姿态。银色宽手镯在撩发时若隐若现，层叠银色颈链增加暗黑高级感，与黑色露肩衫形成统一冷调质感。光线优先选择单侧戏剧性强光，让面部一半亮一半暗形成强烈 chiaroscuro 效果，暗色背景让主体更加突出。核心口诀：斜睨不直视、一手撩发一手抓领、单侧强光半面暗、银饰黑衫冷调。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom89/custom89_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #111217 0%, #73707a 100%)'
  },
  custom90_r01_g01: {
    categoryId: 'portrait-half',
    categoryName: '半身写真',
    name: '半闭接光触心',
    tip: '推荐清晨柔光窗边、花园逆光、白纱窗帘旁、空灵梦幻半身照',
    description: '人物呈上半身 3:4 竖幅构图，身体微微倾斜，头部轻靠向一侧，双眼半闭、眼神温柔低垂，嘴唇微启，表情空灵静谧、带一种漂浮在空气中的轻盈感，不刻意微笑。左手抬起靠近面庞，掌心朝外、五指轻柔张开，像在触碰看不见的薄纱或接住飘落的光；右手轻搭在胸口，指尖若即若离地触碰金色星星吊坠，手指优雅放松。佩戴金色星星吊坠项链和不对称珍珠金耳环，身着象牙白蕾丝领雪纺衬衫，长发松散垂落。双手一高一低、一外一内各做不同动作，柔和逆光在人物轮廓形成光晕，画面充满梦幻空灵的诗意和轻盈的情绪张力。适合场景与拍摄要点：最适合在清晨柔光窗边、花园逆光处、白纱窗帘旁或有梦幻光晕的室内场景拍摄，整体走空灵梦幻风，带一点不食人间烟火的轻盈感。拍摄时身体微微倾斜、头部轻靠向一侧，双眼半闭、眼神温柔低垂，嘴唇微启，营造沉浸在自己世界里的空灵氛围。高处的手掌心朝外、五指轻柔张开靠近面庞，像在触碰光或接住飘落花瓣，手指不要并拢也不要用力，保持羽毛般的轻盈感；低处的手轻搭胸口触碰吊坠，指尖若即若离不要压实，像在感受心跳或许愿。星星吊坠和不对称耳环增加梦幻童话感，蕾丝领雪纺衬衫的轻盈材质与整体空灵气质呼应。光线优先选择柔和逆光或侧逆光，让人物轮廓形成一圈光晕，面部用反光或自然补光保持柔和通透。核心口诀：双眼半闭头微倾、一手接光一手触心、逆光光晕轮廓、星星蕾丝点缀。',
    badge: '半身',
    guideImage: '/static/pose_guides/custom90/custom90_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f4eee3 0%, #d6b36a 100%)'
  },
  custom91_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '秋日接叶行走',
    tip: '推荐秋日公园、林荫道、校园文艺街区、落叶抓拍全身照',
    description: '画面中一位亚洲年轻女性在秋日公园中自然行走，呈现抓拍式的动态瞬间：她正迈步向前，左手向上伸展去接一片飘落的秋叶，右手随步伐自然后摆，身体重心落在前脚掌上，整体姿态轻盈流畅、充满生活气息。拍照指导：适合公园或林荫道，午后阳光透过树叶形成斑驳光影，最适合拍出温暖柔和的氛围；也适合校园、文艺街区等有树木和自然元素的户外环境，能衬托清新文艺风格；秋季外景的落叶和暖色调光线是天然氛围加分项。关键动作角度：机位平视或略低角度拍摄，确保全身入镜，脚部不要被裁切；身体侧对镜头约 30-45 度，脸转向镜头方向，比正面站立更显修长；前脚脚跟微抬、后脚脚尖点地，制造正在行走的动态感，避免僵硬站桩。注意事项：手部不要空着，一手做接落叶、撩头发或扶帽子等动作，另一手自然摆动或拿道具，避免双手下垂显得呆板；表情抓拍优于摆拍，不看镜头或眼神略带故事感，嘴唇微启比刻意微笑更有电影感；落叶、书本、相机、咖啡杯等小道具能丰富画面层次，也给手部提供自然摆放理由；穿搭选择奶油色、卡其色、橄榄绿等低饱和度色系，与自然环境融合，画面更高级。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom91/custom91_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #efe2c9 0%, #9b6f3b 100%)'
  },
  custom92_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '天台倚栏墨镜',
    tip: '推荐天台露台、黄昏城市天际线、咖啡馆户外座位、都市街拍',
    description: '画面中一位年轻亚洲女性站在天台露台边，黄昏时分城市天际线在身后虚化成柔和光斑。她侧身倚靠金属栏杆，右手肘搭在栏杆上随意捏着一副圆形墨镜，左手拇指勾在裤袋外沿，双腿在脚踝处交叉：右腿直立承重、左腿从前方绕过以脚尖轻点地面。整体姿态慵懒松弛又带着一丝酷感，眼神直视镜头，嘴角微扬似笑非笑，充满都市摩登气息。拍照指导：适合天台、露台、高楼层观景台，黄昏金色光线加城市天际线背景天然有高级感；也适合咖啡馆户外座位、街拍、现代建筑、玻璃幕墙或工业风楼梯。机位平视或略低角度，确保全身入镜，脚踝交叉处不要裁切；身体侧对镜头约 45 度，上半身微向后靠栏杆，形成自然 S 形曲线；主力腿伸直承重，另一条腿从前方交叉脚尖点地，显腿长且不死板。手部要有事做，一手拿墨镜搭在栏杆上，一手插兜露拇指；利用栏杆、墙壁、柱子等支撑物让姿态自然放松；金色项链、细戒指、皮质手表和冰咖啡杯能增加都市傍晚故事感；表情用微挑眉加嘴角微扬的似笑非笑，眼神有力度地看向镜头。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom92/custom92_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #e2d0b4 0%, #46515f 100%)'
  },
  custom93_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '高举自拍翘腿背影',
    tip: '推荐旅行街拍、欧洲小镇、OOTD 穿搭记录、背影自拍',
    description: '这是一张从背后拍摄的全身自拍照，人物一手高举手机过头顶，画面中不出现手机；另一只手随意插在牛仔裤后袋里，肘部微弯，手腕放松。站姿采用俏皮的火烈鸟式：一条腿微屈膝盖，脚掌离地向后翘起，露出运动鞋底。长发披散在背后，部分用爪夹挽起，帆布托特包斜挎在肩上。适合旅行街拍、欧洲小镇漫步、OOTD 穿搭记录、朋友圈旅行大片、小红书背影杀分享。关键动作：持手机手臂高举过头顶，向后倾斜约 45 度俯拍全身；另一只手插后袋，手指自然弯曲不外翻；一条腿微屈向后翘起，脚尖轻点或悬空，增加动态感。角度要点：手机举得越高，拍到的全身越完整，建议手臂尽量伸直举高；身体微微侧转 5-10 度，比完全正背面更有线条感；翘腿幅度不要太大，自然微屈即可。注意插后袋的手不要握拳，手指放松半插；帆布包自然斜挎增加生活气息；鹅卵石街道和彩色建筑作为背景丰富层次；短款针织开衫搭配高腰直筒牛仔裤拉长比例；厚底小白鞋与翘起鞋底形成趣味细节。',
    badge: '背影',
    guideImage: '/static/pose_guides/custom93/custom93_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #ead9c2 0%, #6f7f8d 100%)'
  },
  custom94_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '画廊扶帽回眸',
    tip: '推荐美术馆画廊、展览、书店图书馆、知性文艺全身照',
    description: '画面中一位年轻亚洲女性置身于明亮的艺术画廊中，背对镜头约 60 度侧身站立，回眸望向画外上方的展品。她右手抬起轻扶头顶的贝雷帽，手指自然弯曲呈优雅弧度；左手垂于身侧握着一卷艺术杂志，指尖放松。站姿采用经典的 contrapposto 对立式平衡：重心落在右腿，左膝微弯、前脚掌轻抬仅脚跟触地，形成自然身体曲线。整体姿态沉静内敛，仿佛正沉浸在艺术氛围中，充满知性文艺气息。拍照指导：适合美术馆、画廊、展览，白墙与画作构成干净背景，柔和顶光自带氛围；书店、图书馆、咖啡厅靠窗位也适合这种安静有故事感的照片。机位平视或略偏侧后方拍摄，回眸角度让画面更有被捕捉的故事感；身体背对镜头 60 度加回眸，比正面直对镜头更有层次也更显瘦；主力腿伸直承重，另一腿微弯脚尖轻抬，让身体自然形成 S 形曲线。回眸要有落点，眼神看向画作、窗外或书架；手部一高一低，一手扶帽子或撩头发，一手拿杂志或拎包；贝雷帽、几何耳环、丝巾、斜挎包能强化文艺风格；表情以凝视画作的沉浸感为主，嘴唇微启、眼神专注。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom94/custom94_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f4eee5 0%, #7b6a58 100%)'
  },
  custom95_r01_g01: {
    categoryId: 'seated-pose',
    categoryName: '坐姿参考',
    name: '植物园长椅触叶',
    tip: '推荐植物园花园、公园长椅、度假庭院、慵懒舒展坐姿',
    description: '画面中一位年轻亚洲女性侧身坐在植物园的木制长椅上，热带阔叶植物在身后投下斑驳光影。她身体微转向镜头方向，右手撑在身后椅面上支撑上半身，手指自然张开；左手向前伸出，指尖轻触一片巨大的龟背竹叶。双腿呈对角线延伸：右腿向前伸直、脚尖绷直，左腿屈膝收于椅上、脚掌平踏椅面。她头戴宽檐草帽，眼神半闭低垂，嘴唇微启，仿佛在午后的绿意中放空出神，整体姿态慵懒舒展又充满诗意。拍照指导：适合植物园、花园、公园长椅，绿植背景加斑驳光影是天然氛围滤镜；度假酒店、民宿庭院、咖啡馆户外座位也适合。机位略侧前方平视拍摄，让腿部对角线延伸完整入镜；身体侧坐，上半身微扭向镜头形成螺旋线条，比正坐更有层次；一腿伸直一腿弯曲的对角线布局是坐姿中显修长的经典构图。坐姿不要坐满，只坐椅面前 1/3，身体自然挺直；手部一撑一探，一手后撑提供支撑，一手前伸触碰叶子、花或书；伸直的腿脚尖要绷直以拉长腿部线条；宽檐草帽、脚踝链、细手镯、藤编包能增加层次；表情用半闭眼加微启唇的放空状态，比看镜头微笑更有沉浸自然的氛围感。',
    badge: '坐姿',
    guideImage: '/static/pose_guides/custom95/custom95_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8d0a5 0%, #4f6f48 100%)'
  },
  custom96_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '海边举机调鞋带',
    tip: '推荐海边度假、日落海滨步道、旅行大片、背影杀高级感',
    description: '这是一张从背后拍摄的全身自拍照，人物一手高举手机过头顶，另一只手向后探去调整凉鞋的踝带，手指优雅地勾住带子，形成优美的身体弧线。单腿直立，另一条腿屈膝向后抬起，脚踝悬空正在被调整。赤陶色露背吊带中长裙随海风微微飘动，细带在腰后系成蝴蝶结，金色脚链和手链在夕阳下若隐若现。适合海边度假、日落时分海滨步道、旅行大片、蜜月或纪念日照、小红书背影杀高级感分享。关键动作：持手机手臂高举过头顶向后俯拍；另一只手向后探摸脚踝或鞋带，手指自然勾住带子，手臂形成优雅弧线；单腿直立保持平衡，另一条腿屈膝向后抬起，脚尖朝下。角度要点：手机举得越高全身越完整，建议手臂伸直举到最高；身体微微侧转 5-10 度展示露背裙背部细节；抬腿高度适中，以手能自然够到脚踝为准。注意调整鞋带的手不要用力拉扯，指尖轻勾即可；露背裙蝴蝶结系带是视觉焦点，确保不被手臂遮挡；金色时刻暖光从背后打来形成轮廓光；赤陶色裙摆与蓝色海面形成冷暖对比；低发髻搭配几缕碎发，随海风自然飘动增加灵动感。',
    badge: '背影',
    guideImage: '/static/pose_guides/custom96/custom96_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d48a5d 0%, #5e8fb0 100%)'
  },
  custom97_r01_g01: {
    categoryId: 'street-dynamic',
    categoryName: '街拍动态',
    name: '老城地图跨步',
    tip: '推荐欧洲老城、古镇石板路、旅行街拍、城市漫步探索感全身照',
    description: '画面中一位年轻亚洲女性行走在欧洲老城的鹅卵石街道上，被定格在迈步的瞬间：左腿高抬屈膝向前跨出，右脚在后仅前脚掌着地、脚跟离地，整个身体呈大幅度跨步姿态。她双手在胸前展开一张复古纸质地图，左手食指伸出指向地图上的某个位置，仿佛正在辨认方向。她抬头望向高处，眼神充满好奇与惊叹，嘴唇微张，完全沉浸在探索陌生城市的兴奋中，充满旅行途中的故事感与活力。拍照指导：适合欧洲老城、古镇石板路、旅行街拍、城市漫步，也适合机场或火车站出发层，地图和背包能强化旅途感。机位采用正面略低角度仰拍，突出跨步幅度和人物活力，同时把建筑背景收进画面；身体正面朝向镜头，但眼神看向画外上方，制造被某物吸引的故事感；前腿膝盖抬高、后腿蹬直，跨步要比正常走路大 1.5 倍，动态感才足。地图是关键道具，双手展开地图让手部有明确落点，并赋予画面旅行叙事；食指指向地图某处，让静态照片有下一秒要去哪里的悬念；眼神要有明确目标，可以抬头看建筑、路牌或天空；墨镜推上头、方巾系颈、复古背包、相机带能把出门逛街升级成旅行博主氛围；芥末黄、藏蓝、白色等高饱和配色在欧式建筑背景下更出挑。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom97/custom97_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d9b45f 0%, #5e6980 100%)'
  },
  custom98_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '金草理鬓捏裙',
    tip: '推荐黄昏草地、海边沙滩、山顶旷野、电影感裸背长裙背影',
    description: '人物呈全身背影 3:4 竖幅构图，背对镜头站立于金色草丛中，身着奶油色细吊带露背长裙，裙摆被微风轻轻扬起，一条金色细链垂落在裸露的背部。头发松松地挽成低发髻，几缕碎发散落。左手抬起至脑后，手指轻柔地整理发髻旁的碎发，手肘优雅外展；右手向后下方延伸，手指松松地捏住飞扬的裙摆边缘，像在旋转中被定格的中途动作。双脚赤裸，一只脚平踩地面，另一只脚微微踮起、脚尖轻点地面，营造轻盈的动感。金色逆光在人物轮廓形成温暖光晕，整个背影充满诗意和故事感。适合场景与拍摄要点：最适合黄昏金色时刻的旷野草地、海边沙滩、山顶或开阔自然场景，整体走电影感背影风。拍摄时人物完全背对镜头，身体微侧让脊柱形成自然 S 形曲线，肩膀放松下沉。高处的手伸到脑后整理发髻或碎发，手肘外展形成优美三角形，手指轻柔不要用力抓头发；低处的手向后下方延伸捏住裙摆，像在旋转或行走中被风扬起的瞬间，手指松松地捏不要握拳。脚部一只平踩作为重心支撑，另一只微微踮起脚尖轻点地面，制造正在行走或旋转中的动态感；裸足增加自然和自由气息。垂落在裸背上的金色细链是点睛之笔，在逆光下微微反光。光线优先选择黄昏低角度逆光，让人物轮廓、裙摆和发丝边缘被光打透。核心口诀：背对镜头脊柱微曲、一手理鬓一手捏裙、一脚平踩一脚踮起、金色逆光打轮廓、裸背金链点睛。',
    badge: '背影',
    guideImage: '/static/pose_guides/custom98/custom98_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #ead7a3 0%, #9a7440 100%)'
  },
  custom99_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '海滩按帽迎风',
    tip: '推荐海滩湖边日落、浅水湿沙、无边泳池、开阔自然逆光照',
    description: '画面中一位年轻亚洲女性赤脚站在黄昏海滩的浅水中，夕阳将湿润沙滩染成金色。她双眼闭合、脸庞微仰朝向暖阳，神情宁静而沉浸。右手高高举起按住头顶的宽檐草帽抵御海风，手指优雅弯曲；左臂向身侧水平展开与肩同高，掌心向上摊开仿佛在感受海风拂过指尖。双脚在浅水中微微分开：右脚平踏、左脚跟离地仅脚趾压入湿沙，白色亚麻长裙的裙摆被海水微微浸湿贴在小腿边。整个姿态舒展自由，充满与自然融为一体的诗意。拍照指导：适合海滩或湖边日落时分，金色光线加水面反光是拍逆光剪影和氛围感照片的好时机；无边泳池、温泉池边、草原、花海等开阔自然场景也适合。机位略侧前方平视或微仰，让天空和夕阳入镜，人物放在画面下 2/3；光线用侧逆光或正逆光，让光线穿透裙摆和发丝形成金色轮廓光；身体微侧，脸仰起朝向光源方向，闭眼享受比看镜头更有氛围。闭眼是高级表情，传达的是感受而非被看；手臂一上一下形成对角线，一手高举按帽子，一手水平展开；展开的手掌心朝上，更显开放和接纳；赤脚踩水和湿沙是灵魂，裙摆微湿增加真实感；宽檐草帽既是配饰也是动作支点；贝壳项链、脚链、串珠手镯等自然材质配饰更适配海滩场景。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom99/custom99_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #f3e7cf 0%, #d29a55 100%)'
  },
  custom100_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '日落举手自由背影',
    tip: '推荐日落海滩、湖边、沙漠、水天线自然场景、自由电影感背影',
    description: '人物呈全身背影 3:4 竖幅构图，背对镜头行走在日落时分的湿沙滩上，身着深海军蓝垂坠露背吊带长裙，裙摆微湿贴肤，右脚踝佩戴一条带小吊坠的银色脚链。长发完全散开，波浪卷发在海风中肆意飞扬。左手高高举过头顶，五指张开伸向天空，像在释放和拥抱自由；右手自然垂在身后髋部高度，手指松散地划过空气，像在放下什么。双脚赤裸，捕捉在行走的中途：左脚平踩湿润沙滩，右脚从身后抬起、脚尖自然朝下轻点，形成流畅的行走动态。身体直立但肩膀舒展打开，金色夕阳从前方偏左洒来，在身后投下长长的影子，背景是无尽海平线和温暖发光的天空。适合场景与拍摄要点：最适合日落海滩、湖边、沙漠或有开阔水天线的自然场景，整体走自由奔放的电影感背影风，用肢体语言传递放下一切、拥抱自由的情绪。拍摄时人物完全背对镜头向前行走，身体直立但肩膀打开不要含胸，脊柱自然挺直。高处的手高高举过头顶、五指用力张开伸向天空，关键是手指张开不要并拢；低处的手自然垂在身后，手指松散地划过空气，手腕放松。脚部捕捉行走中途，前脚平踩作为重心支撑，后脚从身后抬起、脚尖自然朝下，双脚赤裸增加与自然的连接感。脚踝银色吊坠脚链是精致细节。光线优先选择日落金色时刻的低角度顺光或侧顺光，让人物正面被暖光包裹、身后投下长影。核心口诀：背对镜头向前走、一手举天一手垂后、一脚平踩一脚抬起、金色夕阳长影子、散发飞扬脚链点缀。',
    badge: '背影',
    guideImage: '/static/pose_guides/custom100/custom100_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #23345f 0%, #d99b55 100%)'
  },
  custom101_r01_g01: {
    categoryId: 'outfit-standing',
    categoryName: '全身穿搭',
    name: '楼梯扶手沉思',
    tip: '推荐现代建筑、美术馆楼梯、写字楼创意园、职场精英风全身照',
    description: '画面中一位年轻亚洲女性站在现代建筑的螺旋楼梯中段，几何窗户投下戏剧性的光影切割空间。她侧身而立，右脚踩在比左脚高两级的台阶上，形成强烈的斜线构图。右手紧握肩部高度的金属扶手，指节分明；左手抬起至下颌，食指轻触下巴仿佛在沉思，其余手指自然蜷曲。她身着炭灰色西装外套内搭黑色丝质吊带，黑色九分西装裤配尖头细高跟，眼神锐利直视镜头，双唇紧抿，整个人散发出冷静、果决的强大气场。拍照指导：适合现代建筑、美术馆楼梯、写字楼、创意园区、工业风楼梯、玻璃幕墙走廊、停车场或地下通道，几何线条和光影对比天然有高级感。机位略低角度仰拍，利用楼梯斜线延伸拉长身形并强化气场；身体侧身站立但正面看镜头，身体侧对显瘦，眼神正对有力；一脚高一脚低踩在不同台阶上，天然制造身高差和动态斜线。楼梯是天然构图工具，台阶高低差比平地站立更有层次，螺旋楼梯曲线还能引导视线。手部一刚一柔，一手紧握扶手传递力量感，一手轻触下巴传递思考感；直视镜头加嘴唇紧抿，传达我知道我在做什么的笃定；尖头高跟鞋和绷直脚尖能拉长腿部线条；配饰做减法，用银色宽手镯、小耳环、简约手表和黑色托特包即可；优先选择几何窗户或百叶窗位置，让光影条纹落在身上和墙上。',
    badge: '全身',
    guideImage: '/static/pose_guides/custom101/custom101_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #3a3a3d 0%, #b8aa96 100%)'
  },
  custom102_r01_g01: {
    categoryId: 'seated-pose',
    categoryName: '坐姿参考',
    name: '湖边拉衣坐背影',
    tip: '推荐湖边栈道、河边码头、山顶观景台、安静内省背影坐姿',
    description: '人物呈全身背影 3:4 竖幅构图，背对镜头坐在湖面木栈道边缘，双腿悬空垂在栈道外，身着燕麦色宽松针织毛衣从一侧肩膀微微滑落，搭配白色亚麻阔腿裤，裤脚卷起露出脚踝，左手腕佩戴一条编织皮革细手链。长发松松地扎成低马尾搭在一侧肩上。左手撑在身旁的木栈道上，掌心平贴、五指自然微张，支撑着微微倾斜的身体；右手抬起搭在对侧肩膀上，手指轻轻抓住滑落的毛衣边缘，像在漫不经心地往上拉。双脚赤裸，脚踝松松交叉，脚尖微微朝下指向水面，一只脚后跟轻敲着栈道木板。身体微微前倾含胸，姿态松弛而沉浸在自己的思绪中。柔和逆光从身后洒来，在平静湖面上反射出粼粼波光，背景是宁静湖面和远处朦胧山峦。适合场景与拍摄要点：最适合湖边栈道、河边码头、山顶观景台或任何有水面和远山的静谧自然场景，整体走安静内省的背影风。拍摄时人物背对镜头坐在边缘，身体微微前倾含胸，肩膀放松不要挺直。低处的手撑在身旁地面，掌心平贴、五指微张，支撑身体的同时传递安静力量；高处的手搭在对侧肩膀抓住滑落毛衣边缘，像漫不经心整理衣服，手指轻抓不要用力。双腿悬空垂在边缘，脚踝松松交叉，脚尖朝下指向水面，一只脚后跟轻敲木板，制造发呆时无意识的小动作；赤脚增加与自然的亲近感。编织皮革手链在撑地时若隐若现，是低调细节。光线优先选择柔和逆光或侧逆光，让水面反射光斑成为氛围加分项。核心口诀：背对镜头坐边缘、一手撑地一手拉衣、双腿悬空脚踝交叉、逆光湖面远山背景、赤脚手链细节。',
    badge: '坐姿',
    guideImage: '/static/pose_guides/custom102/custom102_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c7ad 0%, #6f837c 100%)'
  },
  custom103_r01_g01: {
    categoryId: 'seated-pose',
    categoryName: '坐姿参考',
    name: '晨雾码头捻花',
    tip: '推荐湖边河边码头、水库栈桥、黎明晨雾、静谧情绪坐姿',
    description: '画面中一位年轻亚洲女性坐在黎明时分的木码头边缘，双腿悬空垂向湖面，晨雾从水面升起，粉蓝渐变的天空倒映在平静的湖中。她眼神悠远地望向湖对岸的远方，嘴唇微微下垂，神情带着一丝淡淡的忧郁与沉思。右手撑在身侧码头上支撑身体，左手拇指与食指间轻捻一朵雏菊在膝旁缓缓转动。双脚赤裸，脚踝松散交叉：右脚自然垂悬，左脚脚尖轻掠水面荡起细小涟漪。燕麦色粗针织开衫从一侧肩膀滑落，露出内搭的白色棉质吊带裙，身旁放着旧皮面笔记本和一双帆布鞋，整个画面安静而富有诗意。拍照指导：适合湖边、河边码头、水库、池塘栈桥、海边礁石或堤坝，水面倒影加晨雾是天然情绪片场景。机位侧面或侧后方平视拍摄，把人物放在画面一侧，留出大面积水面和天空，强化孤独感和空间感；光线选择逆光或侧逆光，黎明或黄昏柔光让皮肤通透，水面反光形成天然补光；人物偏左或偏右，视线方向留白，让望向远方有空间延伸。坐在码头最边缘、腿悬空，比坐在中间更有悬于天地之间的意境；一只脚轻触水面制造涟漪，让静态画面有动的细节；一朵雏菊、一本旧笔记本承载情绪，捻花是心事，笔记本是想说未说的话；开衫从一侧肩膀滑落，露出锁骨和肩线，增加不在意的松弛美；眼神望向画面外远方而非镜头；鞋子整齐放在一旁，赤脚垂向水面，传达卸下防备、回归本真的情绪。',
    badge: '坐姿',
    guideImage: '/static/pose_guides/custom103/custom103_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d9d3c1 0%, #8aa6b4 100%)'
  },
  custom104_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '古镇展臂蹦跳',
    tip: '推荐欧洲古镇小巷、海边步道、花田小径、快乐自由旅行背影',
    description: '人物呈全身背影 3:4 竖幅构图，背对镜头站在欧洲古镇的鹅卵石窄巷中，双臂向两侧水平张开如飞机展翅，身着芥末黄中长裙搭配短蓬袖，裙摆被风扬起，腰间系一条棕色细皮带，右手腕叠戴多圈细金镯在阳光下闪烁。头发扎成凌乱的高马尾甩向一侧。左手水平伸展、五指张开放松；右手同样水平伸展、掌心打开、手指自然微曲。双脚穿着棕色平底皮凉鞋，捕捉在跳跃或小跑的中途：左脚稳稳踩在鹅卵石上，右腿从身后弯膝抬起、脚尖朝下轻点，像在跳舞或蹦跳。身体直立、头微微歪向一侧，肩膀舒展打开，午后暖阳从身后洒来，在身前鹅卵石地面上投下俏皮长影，背景是粉彩色调老建筑、窗台花箱和湛蓝天空。适合场景与拍摄要点：最适合旅行中的欧洲古镇小巷、海边步道、花田小径或任何有纵深感的有趣街道，整体走快乐自由的旅行背影风。拍摄时人物背对镜头站在有纵深感的街道中央，双臂向两侧水平张开如飞机展翅，手指张开放松不要并拢，传递毫无保留的快乐和自由。双手对称张开但不要僵硬，手指自然舒展微曲，像在拥抱整个世界，金镯在阳光下闪烁是加分细节。脚部捕捉跳跃或小跑中途，前脚稳稳踩地作为重心，后腿弯膝抬起、脚尖朝下，制造在路上蹦蹦跳跳的快乐动态，平底凉鞋比赤脚更适合旅行街拍真实感。高马尾甩向一侧增加动感，芥末黄裙子在阳光下格外明媚。光线优先选择午后顺光或侧顺光，让人物正面被暖光照亮、身后投下长影，影子本身也是构图的一部分。核心口诀：背对镜头站街中央、双臂张开如展翅、一脚踩地一脚弯膝抬起、午后暖阳长影子、黄裙金镯高马尾。',
    badge: '背影',
    guideImage: '/static/pose_guides/custom104/custom104_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8a339 0%, #83a6c7 100%)'
  },
  custom105_r01_g01: {
    categoryId: 'travel-back',
    categoryName: '旅行背影',
    name: '薰衣草持帽背影',
    tip: '推荐薰衣草田、向日葵花海、麦田、浪漫田园背影全身照',
    description: '人物呈全身背影 3:4 竖幅构图，背对镜头站在薰衣草田边缘，双手在背后持一顶宽檐草帽，身着白色镂空蕾丝长裙，深 V 露背设计，腰间系着细缎带，一条银色细链带小月牙吊坠垂落在裸露的背部。长发编成松散侧辫搭在右肩，辫间点缀几朵小野花。左手在背后下方握住草帽帽檐，手指轻轻蜷曲；右手同样握住帽檐，手指与左手交叠，双手自然垂在腰后。双脚赤裸，微微分开站立，左脚平踩地面，右脚跟微微抬起、仅前脚掌轻触泥土，脚尖轻轻陷入土壤，像正要迈步走进花田。身体直立优雅，肩膀微微后展，头轻转向右侧露出一点下颌线。金色夕阳从右前方洒来，照亮薰衣草田的紫色花垄，在人物轮廓形成柔光，背景是无尽的薰衣草花海延伸到天际。适合场景与拍摄要点：最适合薰衣草田、向日葵花海、麦田或任何有纵深感的花田场景，整体走浪漫田园背影风，用优雅站姿和道具传递置身花海的静谧美好。拍摄时人物背对镜头站在花田边缘或花垄之间，身体直立、肩膀微微后展，头轻转向一侧露出一点下颌线，让背影不单调。手部是优雅来源，双手在背后持宽檐草帽，手指轻轻握住帽檐、自然交叠垂在腰后，既解决手部摆放问题，又增加田园浪漫道具感。脚部是全身背影照的细节亮点，双脚赤裸微微分开，一只脚平踩地面，另一只脚跟微微抬起、仅前脚掌触地，像正要迈步走进花田，脚尖轻陷泥土增加与自然的连接感。垂落在裸背上的月牙吊坠银链是露背裙的点睛之笔，侧辫小野花与花田呼应，镂空蕾丝裙纹理在逆光下格外精致。光线优先选择金色时刻低角度顺光或侧顺光，让花田紫色被暖光照亮，人物正面受光、轮廓柔和。核心口诀：背对镜头站花田、双手背后持草帽、一脚平踩一脚踮起、金色夕阳照花垄、露背银链侧辫野花。',
    badge: '背影',
    guideImage: '/static/pose_guides/custom105/custom105_r01_g01_contour.png',
    gradient: 'linear-gradient(150deg, #d8c6ee 0%, #9b7a4d 100%)'
  }
}

const poseSearchKeywordOverrides = {
  custom1_r01_g01: ['侧身照', '半身侧身', '显瘦', '温柔写真', '日常照', '腰间搭手', '自然看镜头', '不尴尬半身'],
  custom2_r01_g01: ['撩头发', '摸头发', '侧光', '浅笑', '亲和', '温柔半身', '互动感', '自然笑'],
  custom3_r01_g01: ['托腮', '托下巴', '锁骨', '肩线', '知性', '思考感', '安静', '一字肩', '抱臂'],
  custom4_r01_g01: ['野餐', '趴着拍', '趴姿', '草地', '双手托腮', '少女感', '慵懒', '法棍', '格纹垫'],
  custom5_r01_g01: ['撩头发', '抬眸', '毛衣照', '甜美', '侧身半身', '低头抬眼', '温柔笑', '自然半身'],
  custom6_r01_g01: ['显高', '显腿长', '回头看', '叉腰', '高腰穿搭', '逆光', '全身站姿', '拉长比例'],
  custom7_r01_g01: ['拿咖啡', '走路拍', '行走照', '抓拍', '街头', '通勤', '低头走路', '都市感'],
  custom8_r01_g01: ['自然站立', '不会摆姿势', '日常站姿', '户外', '微笑', '亲和', '全身照', '简单站姿'],
  custom9_r01_g01: ['西装', '通勤', '咖啡', '插兜', '阔腿裤', '干练', '都市街拍', '上班穿搭'],
  custom10_r01_g01: ['背影', '不露脸', '跳跃', '山顶', '举手', '旅行照', '活力', '自由感', '踢腿'],
  custom11_r01_g01: ['背影', '不露脸', '回头', '回眸', '撩发', '长裙', '户外', '温柔抓拍'],
  custom12_r01_g01: ['背影', '不露脸', '回眸', '逆光', '短发', '城市街道', '松弛感', '微笑'],
  custom13_r01_g01: ['湖边', '湖畔', '背影', '不露脸', '草帽', '长裙', '日落', '栈桥', '旅行氛围'],
  custom14_r01_g01: ['海边', '山海', '背影', '不露脸', '遮阳', '回头', '草坡', '黄金时刻', '旅行打卡'],
  custom15_r01_g01: ['古镇', '小巷', '背影', '不露脸', '提篮', '回眸', '清晨', '旅行街拍', '古风氛围'],
  custom16_r01_g01: ['露台', '夜景', '背影', '不露脸', '栏杆', '披肩', '都市夜景', '优雅', '氛围感'],
  custom17_r01_g01: ['海边', '沙滩', '背影', '不露脸', '提鞋', '裙摆', '日出', '长裙', '度假'],
  custom18_r01_g01: ['自拍', '撩头发', '侧身自拍', '半身自拍', '三角构图', '自然自拍', '松弛', '不尴尬'],
  custom19_r01_g01: ['侧身', '远眺', '撩发', '看远处', '抓拍感', '不看镜头', '半身写真', '松弛'],
  custom20_r01_g01: ['窗边', '窗光', '自拍', '撩发', '浅笑', '室内', '自然光', '半身自拍'],
  custom21_r01_g01: ['窗边', '午后', '自拍', '撩发', '笑容', '明亮', '自然光', '抓拍'],
  custom22_r01_g01: ['咖啡馆', '端杯', '拿咖啡', '撩发', '生活感', '半身照', '温暖', '道具互动'],
  custom23_r01_g01: ['自拍', '胸上自拍', '逆光', '夕阳', '自然笑', '近景', '头像', '半身自拍'],
  custom24_r01_g01: ['自拍', '触脸', '摸脸', '下颌线', '百叶窗', '光影', '近景', '头像', '自信'],
  custom25_r01_g01: ['连衣裙', '草帽', '比耶', '剪刀手', '显高', '旅行', '正面照', '活力', '甜美'],
  custom26_r01_g01: ['溪流', '森林', '背影', '不露脸', '行走', '赤脚', '提裤脚', '自然旅行'],
  custom27_r01_g01: ['海边', '墨镜', '托特包', '包包', '夏天', '抬脚', '正面照', '配饰', '度假'],
  custom28_r01_g01: ['自拍', '捂嘴', '惊讶表情', '夸张表情', '元气', '可爱', '近景', '头像'],
  custom29_r01_g01: ['湖边', '码头', '坐姿', '背影', '不露脸', '整理辫子', '黄昏', '赤脚', '脚踩水'],
  custom30_r01_g01: ['折扇', '扇子', '珍珠', '知性', '优雅', '室内', '交叉腿', '正面照', '轻奢'],
  custom31_r01_g01: ['庭园', '日式', '背影', '不露脸', '踮脚', '展臂', '平衡', '轻盈', '动态'],
  custom32_r01_g01: ['相机', '爱心手势', '比心', '涂鸦墙', '街头', '眨眼', '创意', '活力'],
  custom33_r01_g01: ['登山', '徒步', '望远镜', '山脊', '背影', '不露脸', '探索感', '户外'],
  custom34_r01_g01: ['自拍', '墨镜', '机车', '酷飒', '街头', '嘟嘴', '近景', '头像', '酷一点'],
  custom35_r01_g01: ['野餐', '草甸', '背影', '不露脸', '坐姿', '野餐篮', '法棍', '草莓', '生活感'],
  custom36_r01_g01: ['花景', '许愿', '交扣手', '温柔', '浪漫', '正面照', '全身照', '甜美'],
  custom37_r01_g01: ['运动', '自拍', '点赞', '台阶', '活力', '手机自拍', '青春', '全身照'],
  custom38_r01_g01: ['草帽', '锁骨', '侧站', '自然站姿', '松弛', '全身穿搭', '显瘦', '温柔'],
  custom39_r01_g01: ['折扇', '扇子', '提裙', '轻奢', '优雅', '芭蕾脚', '室内写真', '复古'],
  custom40_r01_g01: ['咖啡', '台阶', '牛仔裤', '插兜', '休闲', '都市街拍', '通勤', '外带杯'],
  custom41_r01_g01: ['画笔', '贝雷帽', '艺术馆', '文艺', '舞姿', '创意写真', '动态', '抬腿'],
  custom42_r01_g01: ['羽毛球', '挥拍', '运动', '弓步', '户外活力', '动感', '运动风', '抓拍'],
  custom43_r01_g01: ['阳伞', '花园', '蕾丝伞', '少女感', '浪漫', '闭眼', '梦幻', '抬腿'],
  custom44_r01_g01: ['海边', '白裙', '草帽', '度假', '长裙', 'S形站姿', '沙滩', '松弛'],
  custom45_r01_g01: ['草地', '草帽', '锁骨', '自然光', 'S形站姿', '松弛', '温暖', '全身照'],
  custom46_r01_g01: ['职场', '西装', '领口', '文件夹', '杂志风', '干练', '力量感', '通勤'],
  custom47_r01_g01: ['草地', '盘坐', '坐姿', '晒太阳', '闭眼', '逆光', '松弛感', '户外'],
  custom48_r01_g01: ['海边', '礁石', '侧坐', '粉裙', '长裙', '度假', '草帽', '优雅坐姿'],
  custom49_r01_g01: ['风衣', '行走', '走路拍', '拢发', '通勤', '街拍', '抓拍', '利落'],
  custom50_r01_g01: ['草地', '相机', '行走', '走路拍', '抓拍', '生活感', '大步走', '活力'],
  custom51_r01_g01: ['木凳', '相机', '坐姿', '咖啡馆', '休闲', '慵懒', '脚踝交叠', '日常写真'],
  custom52_r01_g01: ['海边', '蹲姿', '拾贝壳', '贝壳', '沙滩', '探索感', '互动', '低头'],
  custom53_r01_g01: ['海滩', '晚霞', '日落', '拎鞋', '行走', '走路拍', '度假', '松弛'],
  custom54_r01_g01: ['跑步', '跑动', '挥手', '运动', '活力', '腾空', '抓拍', '户外'],
  custom55_r01_g01: ['草地', '蹲姿', '看花', '雏菊', '自然光', '生活感', '温柔', '低头'],
  custom56_r01_g01: ['蹲姿', '宠物', '撸猫', '猫咪', '互动', '日系', '低伏', '温馨'],
  custom57_r01_g01: ['海边', '踢水', '玩水', '水花', '夏天', '动态', '活力', '旅行'],
  custom58_r01_g01: ['草地', '慢跑', '跑步', '腾空', '运动', '马尾', '青春', '抓拍'],
  custom59_r01_g01: ['栈道', '相机', '侧站', '旅行', '插兜', 'S形曲线', '自然站姿', '松弛'],
  custom60_r01_g01: ['公路', '草帽', '行走', '走路拍', '旅行', '拢发', '动态', '空旷'],
  custom61_r01_g01: ['石桥', '相机', '侧站', '桥上', '旅行', '自然站姿', '不看镜头', '抓拍'],
  custom62_r01_g01: ['台阶', '坐姿', '拍立得', '相机', '街头', '酷感', '撩发', '户外街拍'],
  custom63_r01_g01: ['站台', '行李箱', '坐姿', '复古旅行', '火车站', '候车', '回头', '旅途感'],
  custom64_r01_g01: ['台阶', '雨伞', '咖啡', '城市', '知性', '街拍', '情绪感', '透明伞'],
  custom65_r01_g01: ['石桥', '读书', '书本', '侧坐', '墨镜', '文艺', '旅行', '慵懒'],
  custom66_r01_g01: ['石桥', '系鞋带', '蹲姿', '运动鞋', '运动街拍', '青春', '蹲下', '动感'],
  custom67_r01_g01: ['站台', '靠柱', '读书', '书本', '咖啡', '候车', '复古', '知性'],
  custom68_r01_g01: ['夜景', '台阶', '靠墙', '仙女棒', '蓝调', '电影感', '手账本', '小巷'],
  custom69_r01_g01: ['湖边', '提鞋', '踢水', '玩水', '长裙', '赤脚', '度假', '夏天'],
  custom70_r01_g01: ['森林', '古树', '咖啡', '靠站', '秋天', '毛衣', '静谧', '温暖'],
  custom71_r01_g01: ['栈桥', '写生', '盘坐', '苹果', '画画', '湖边', '安静', '专注'],
  custom72_r01_g01: ['森林', '树枝', '侧坐', '春天', '清新', '俏皮', '坐姿', '摸叶子'],
  custom73_r01_g01: ['芦苇', '浅滩', '湖边', '漫步', '手杖', '赤脚', '自然', '静谧'],
  custom74_r01_g01: ['野餐', '趴着拍', '趴姿', '草地', '双手托腮', '少女感', '慵懒', '法棍', '格纹垫'],
  custom75_r01_g01: ['自拍', '前置自拍', '半身自拍', '撩发', '摸头发', '手机自拍', '俯拍', '45度', '下巴微收', '眼神柔和', '嘴唇微启', '朋友圈', '小红书', '氛围感'],
  custom76_r01_g01: ['半身照', '侧身', '不看镜头', '复古相机', '胶片相机', '锁骨', '触锁骨', '文艺', '故事感', '针织毛衣', '侧光', '侧逆光', '3:4构图', '下巴微收'],
  custom77_r01_g01: ['自拍', '前置自拍', '半心手势', '半心', '冷淡风', '清冷', '慵懒', '微嘟', '半阖眼', '锁骨', '暖光', '情绪感', '小红书', '朋友圈'],
  custom78_r01_g01: ['半身照', '低眸', '不看镜头', '调整耳环', '耳环', '墨镜', '圆形墨镜', '亚麻衬衫', '疏离感', '文艺', '双手各忙各的', '窗光', '柔光侧打'],
  custom79_r01_g01: ['自拍', '前置自拍', '领口', '捏领口', '锁骨', '惊喜感', '好奇感', '嘴唇微张', 'o形嘴', '睁大眼睛', '午后阳光', '生活感', '旅行随拍'],
  custom80_r01_g01: ['半身照', '撩发', '触碰项链', '项链', '锁骨', '眼神上扬', '放空', '嘴唇微启', '不笑', '黄昏', '逆光', '电影感', '温柔情绪', '金色暖光'],
  custom81_r01_g01: ['半身照', '闭眼', '不笑', '贴脸', '下颌线', '干花', '满天星', '拈花', '珍珠项链', '珍珠耳钉', '静谧', '治愈感', '日系'],
  custom82_r01_g01: ['自拍', '前置自拍', '托下巴', '触下唇', '雨窗', '雨天', '忧郁', '杂志风', '音乐封面', '不看镜头', '独处', '氛围感'],
  custom83_r01_g01: ['半身照', '直视镜头', '点额', '太阳穴', '抓领', '衣领', '高冷', '时尚杂志', '暗黑时尚', '颈链', '几何耳坠', '戏剧光', '单侧强光'],
  custom84_r01_g01: ['半身照', '生活感', '抓拍', '日系', '前倾', '触唇', '食指触唇', '捧杯', '咖啡杯', '热咖啡', '热茶', '眉毛轻扬', '嘴唇微启', '窗光'],
  custom85_r01_g01: ['半身照', '扎发', '贴心', '胸口', '望远', '嘴唇轻闭', '金色逆光', '轮廓光', '珍珠耳坠', '银链', '浪漫', '诗意'],
  custom86_r01_g01: ['自拍', '前置自拍', '苹果', '红苹果', '眨眼', '单眼微眨', '歪嘴笑', '苹果肌', '俏皮', '厨房', '生活碎片', '水果主题'],
  custom87_r01_g01: ['自拍', '前置自拍', '皮衣', '抓领', '领口', '银戒', '湿发', '凌厉', '酷女孩', '街头风', '杂志硬照', '力量感', '紧抿'],
  custom88_r01_g01: ['半身照', '托腮', '托下巴', '笔记本', '速写本', '思考者', '灵感', '创意思考', '绿松石', '亚麻衬衫', '眼神向上', '自然光'],
  custom89_r01_g01: ['半身照', '斜睨', '撩发', '抓领', '露肩', '黑色针织衫', '银色宽手镯', '银链', '高定时尚', '戏剧光', '明暗分割', '强势', '力量感'],
  custom90_r01_g01: ['半身照', '半闭眼', '低垂眼神', '接光', '触心', '胸口', '星星吊坠', '蕾丝领', '雪纺衬衫', '空灵', '梦幻', '逆光光晕', '光斑'],
  custom91_r01_g01: ['全身照', '秋日', '公园', '林荫道', '行走', '走路拍', '接落叶', '落叶', '抓拍', '动态', '侧身', '斑驳光影', '低饱和穿搭', '电影感'],
  custom92_r01_g01: ['全身照', '天台', '露台', '栏杆', '倚靠', '墨镜', '脚踝交叉', '都市摩登', '黄昏', '城市天际线', '似笑非笑', '酷感'],
  custom93_r01_g01: ['背影', '自拍', '全身自拍', '高举手机', '火烈鸟站姿', '翘腿', '后袋插手', '旅行街拍', 'OOTD', '托特包', '爪夹'],
  custom94_r01_g01: ['全身照', '画廊', '美术馆', '回眸', '扶帽子', '贝雷帽', '艺术杂志', 'contrapposto', '对立式平衡', '知性', '文艺'],
  custom95_r01_g01: ['坐姿', '植物园', '长椅', '触叶', '龟背竹', '草帽', '侧坐', '对角线腿部', '脚尖绷直', '半闭眼', '慵懒', '度假风'],
  custom96_r01_g01: ['背影', '自拍', '全身自拍', '海边', '日落', '高举手机', '调鞋带', '踝带', '露背裙', '蝴蝶结', '金色时刻', '度假'],
  custom97_r01_g01: ['全身照', '旅行街拍', '欧洲老城', '鹅卵石街道', '地图', '展开地图', '指地图', '跨步', '大步走', '探索感', '古镇', '城市漫步'],
  custom98_r01_g01: ['背影', '全身背影', '金色草丛', '裸背长裙', '捏裙摆', '整理发髻', '踮脚', '赤脚', '金色逆光', '电影感', '金色细链'],
  custom99_r01_g01: ['全身照', '海滩', '浅水', '湿沙', '闭眼仰头', '按帽子', '宽檐草帽', '掌心向上', '亚麻长裙', '赤脚', '侧逆光', '度假'],
  custom100_r01_g01: ['背影', '全身背影', '海边', '日落', '湿沙滩', '举手', '拥抱自由', '散发飞扬', '露背吊带裙', '脚链', '赤脚行走', '电影感'],
  custom101_r01_g01: ['全身照', '楼梯', '螺旋楼梯', '现代建筑', '职场', '西装', '扶手', '触下巴', '沉思', '强气场', '几何光影', '高跟鞋'],
  custom102_r01_g01: ['背影', '坐姿', '湖边', '木栈道', '双腿悬空', '脚踝交叉', '拉毛衣', '撑地', '赤脚', '逆光湖面', '远山', '独处'],
  custom103_r01_g01: ['坐姿', '码头', '湖边', '晨雾', '捻花', '雏菊', '脚尖点水', '涟漪', '旧笔记本', '赤脚', '忧郁', '静谧'],
  custom104_r01_g01: ['背影', '旅行背影', '欧洲古镇', '鹅卵石小巷', '展臂', '飞机手', '蹦跳', '小跑', '芥末黄裙', '金镯', '高马尾', '自由'],
  custom105_r01_g01: ['背影', '全身背影', '薰衣草田', '花田', '宽檐草帽', '背后持帽', '露背长裙', '蕾丝长裙', '月牙吊坠', '侧辫', '小野花', '赤脚', '踮脚', '浪漫田园']
}

const poseSceneKeywordOverrides = {
  custom4_r01_g01: ['水边', '湖边', '湖岸', '草地', '户外', '野餐场景', '生活场景', '露营', '露营地'],
  custom7_r01_g01: ['路上', '街上', '街边', '街头', '咖啡店', '咖啡店外', '通勤路上', '城市街道', '店铺', '店门口', '商业街', '商场外'],
  custom9_r01_g01: ['路上', '街上', '街边', '街头', '咖啡店', '咖啡店外', '通勤路上', '城市街道', '店铺', '店门口', '商业街', '商场外'],
  custom10_r01_g01: ['山顶', '山上', '山路', '户外', '旅行景点', '开阔场景'],
  custom11_r01_g01: ['户外', '公园', '草地', '路边', '旅行景点', '自然场景'],
  custom12_r01_g01: ['路上', '街上', '街边', '街头', '城市街道', '马路边', '逆光街道', '商业街', '店铺外'],
  custom13_r01_g01: ['水边', '湖边', '湖畔', '湖上', '河边', '桥上', '栈桥', '码头', '日落景点'],
  custom14_r01_g01: ['海边', '山边', '山海', '水边', '草坡', '户外景点', '旅行景点'],
  custom15_r01_g01: ['古镇', '小巷', '巷子', '路上', '街上', '街边', '旅行景点'],
  custom16_r01_g01: ['露台', '屋顶', '天台', '栏杆边', '城市夜景', '夜景场景'],
  custom17_r01_g01: ['海边', '水边', '沙滩', '海滩', '浅水边', '度假场景'],
  custom20_r01_g01: ['室内', '窗边', '窗前', '家里', '房间', '酒店', '民宿', '居家', '咖啡店窗边'],
  custom21_r01_g01: ['室内', '窗边', '窗前', '家里', '房间', '酒店', '民宿', '居家', '咖啡店窗边'],
  custom22_r01_g01: ['咖啡店', '咖啡馆', '店里', '室内', '窗边', '餐厅', '饭店', '甜品店', '奶茶店', '下午茶'],
  custom24_r01_g01: ['室内', '窗边', '窗前', '家里', '房间', '酒店', '民宿', '居家', '卧室'],
  custom25_r01_g01: ['路上', '街边', '户外', '草地', '旅行景点', '公园'],
  custom26_r01_g01: ['水边', '溪边', '河边', '森林', '树林', '浅水', '自然景点', '旅行景点'],
  custom27_r01_g01: ['海边', '水边', '沙滩', '海滨', '路边', '度假场景'],
  custom29_r01_g01: ['水边', '湖边', '湖畔', '河边', '码头', '桥边', '栈桥', '日落景点'],
  custom31_r01_g01: ['庭园', '园林', '公园', '石板路', '步道', '日式庭院', '旅行景点'],
  custom32_r01_g01: ['路上', '街上', '街边', '街头', '墙边', '涂鸦墙', '城市街道', '商业街', '店铺外', '商场外'],
  custom33_r01_g01: ['山顶', '山上', '山路', '徒步路上', '户外', '旅行景点', '开阔场景'],
  custom35_r01_g01: ['草地', '户外', '公园', '田野', '野餐场景', '生活场景', '露营', '露营地'],
  custom40_r01_g01: ['咖啡店', '咖啡店外', '街边', '街上', '路上', '台阶', '城市街道', '店铺', '店门口', '商业街', '商场外'],
  custom41_r01_g01: ['艺术馆', '展馆', '室内', '画室', '文艺场景'],
  custom42_r01_g01: ['运动场', '球场', '户外', '公园', '草地', '操场', '校园', '学校', '运动场景'],
  custom43_r01_g01: ['花园', '公园', '草地', '户外', '花丛', '庭院'],
  custom44_r01_g01: ['海边', '水边', '沙滩', '海滩', '度假场景', '旅行景点'],
  custom45_r01_g01: ['草地', '公园', '户外', '自然光', '绿地', '旅行景点'],
  custom46_r01_g01: ['办公室', '职场', '公司', '写字楼', '室内', '商务场景'],
  custom47_r01_g01: ['草地', '公园', '户外', '绿地', '校园', '学校', '阳光下', '生活场景'],
  custom48_r01_g01: ['海边', '水边', '礁石', '沙滩', '海滩', '度假场景', '酒店外', '民宿外'],
  custom49_r01_g01: ['路上', '街上', '街边', '街头', '马路边', '通勤路上', '城市街道', '商业街', '店铺外'],
  custom50_r01_g01: ['草地', '公园', '户外', '绿地', '路上', '生活场景'],
  custom51_r01_g01: ['咖啡店', '咖啡馆', '店里', '室内', '木凳', '餐厅', '饭店', '甜品店', '奶茶店', '休闲场景'],
  custom52_r01_g01: ['海边', '水边', '沙滩', '海滩', '浅水边', '度假场景'],
  custom53_r01_g01: ['海边', '水边', '沙滩', '海滩', '路上', '日落景点', '度假场景'],
  custom54_r01_g01: ['路上', '街上', '户外', '公园', '操场', '校园', '学校', '运动场景', '开阔场景'],
  custom55_r01_g01: ['草地', '公园', '户外', '花丛', '绿地', '校园', '学校', '自然场景'],
  custom56_r01_g01: ['路边', '街边', '户外', '宠物店外', '生活场景'],
  custom57_r01_g01: ['海边', '水边', '沙滩', '海滩', '浅水边', '度假场景'],
  custom58_r01_g01: ['草地', '公园', '户外', '绿地', '操场', '校园', '学校', '运动场景', '开阔场景'],
  custom59_r01_g01: ['桥上', '栈道', '栈桥', '木桥', '水边', '旅行景点'],
  custom60_r01_g01: ['路上', '公路', '马路', '街边', '旅行路上', '开阔场景'],
  custom61_r01_g01: ['桥上', '石桥', '桥边', '水边', '旅行景点', '路上'],
  custom62_r01_g01: ['台阶', '楼梯', '街边', '路边', '户外', '城市街道', '校园', '学校', '商场外'],
  custom63_r01_g01: ['站台', '火车站', '车站', '地铁站', '路上', '旅行路上', '复古场景'],
  custom64_r01_g01: ['台阶', '楼梯', '街边', '路边', '咖啡店外', '城市街道', '商业街', '商场外', '雨天'],
  custom65_r01_g01: ['桥上', '石桥', '桥边', '水边', '旅行景点', '读书场景', '书店', '图书馆'],
  custom66_r01_g01: ['桥上', '石桥', '桥边', '路上', '街边', '运动场景'],
  custom67_r01_g01: ['站台', '火车站', '车站', '地铁站', '柱子旁', '咖啡店', '书店', '图书馆', '候车场景'],
  custom68_r01_g01: ['台阶', '楼梯', '小巷', '巷子', '夜景', '路边', '城市夜景'],
  custom69_r01_g01: ['水边', '湖边', '湖畔', '河边', '浅水边', '度假场景', '自然景点'],
  custom70_r01_g01: ['森林', '树林', '树下', '公园', '户外', '秋天场景', '咖啡店外'],
  custom71_r01_g01: ['水边', '湖边', '湖畔', '河边', '桥上', '栈桥', '码头', '写生场景', '书店', '图书馆'],
  custom72_r01_g01: ['森林', '树林', '树下', '公园', '户外', '自然场景'],
  custom73_r01_g01: ['水边', '湖边', '湖畔', '浅滩', '芦苇荡', '自然景点'],
  custom74_r01_g01: ['水边', '湖边', '湖岸', '草地', '户外', '野餐场景', '生活场景'],
  custom75_r01_g01: ['室内', '居家', '家里', '房间', '卧室', '暖光', '咖啡厅', '咖啡店', '窗边', '咖啡厅窗边', '生活场景'],
  custom76_r01_g01: ['咖啡馆', '咖啡厅', '咖啡店', '窗边', '靠窗', '书店', '艺术街区', '室内窗边', '室内', '自然侧光', '文艺场景'],
  custom77_r01_g01: ['室内', '卧室', '夜晚卧室', '暖光', '酒吧', '清吧', '酒吧角落', '清吧角落', '夜景室内', '情绪场景'],
  custom78_r01_g01: ['咖啡馆', '咖啡厅', '咖啡店', '窗边', '咖啡馆窗边', '美术馆', '书店', '室内角落', '午后阳光', '室内窗光', '文艺场景'],
  custom79_r01_g01: ['阳台', '露台', '午后阳光', '户外咖啡座', '咖啡座', '旅行路上', '户外', '绿植背景', '生活场景'],
  custom80_r01_g01: ['黄昏窗边', '窗边', '室内角落', '金色暖光', '户外逆光', '逆光场景', '黄昏', '室内', '电影感场景'],
  custom81_r01_g01: ['清晨窗边', '窗边', '安静卧室', '卧室', '花房', '室内角落', '柔和阳光', '室内', '治愈场景'],
  custom82_r01_g01: ['雨天窗边', '窗边', '雨天', '独处时光', '室内', '雨窗', '音乐封面', '情绪场景'],
  custom83_r01_g01: ['摄影棚', '暗调空间', '工业风建筑', '室内', '暗色背景', '戏剧光影', '杂志封面', '时尚场景'],
  custom84_r01_g01: ['咖啡馆', '咖啡厅', '咖啡店', '家中沙发角落', '沙发角落', '书店窗边', '书店', '窗边', '室内', '晨光', '温暖生活场景'],
  custom85_r01_g01: ['黄昏窗边', '窗边', '户外逆光草地', '草地', '海边日落', '日落', '温暖逆光', '室内逆光', '浪漫场景'],
  custom86_r01_g01: ['厨房', '厨房日常', '健康饮食', '白瓷砖背景', '木砧板', '室内', '生活场景', '水果主题'],
  custom87_r01_g01: ['城市天台', '天台日落', '音乐节', '演唱会现场', '街头', '城市天际线', '黄昏', '酷感场景'],
  custom88_r01_g01: ['工作室', '图书馆', '咖啡馆', '咖啡厅', '咖啡馆靠窗', '书房', '室内', '自然光', '创作场景'],
  custom89_r01_g01: ['摄影棚', '暗调工业空间', '工业空间', '夜晚城市街头', '城市街头', '室内', '戏剧性灯光', '暗色背景', '高定时尚场景'],
  custom90_r01_g01: ['清晨柔光窗边', '窗边', '花园逆光', '花园', '白纱窗帘旁', '白纱窗帘', '室内', '柔和逆光', '侧逆光', '梦幻光晕'],
  custom91_r01_g01: ['秋日公园', '公园', '林荫道', '校园', '文艺街区', '户外', '秋季外景', '落叶场景', '午后阳光', '斑驳光影', '自然场景'],
  custom92_r01_g01: ['天台', '露台', '高楼层观景台', '城市天际线', '黄昏', '咖啡馆户外座位', '街拍', '都市风', '现代建筑', '玻璃幕墙', '工业风楼梯'],
  custom93_r01_g01: ['旅行街拍', '欧洲小镇', '小镇街道', '鹅卵石街道', '彩色建筑', '户外', '旅行路上', 'OOTD场景'],
  custom94_r01_g01: ['美术馆', '画廊', '展览', '展馆', '书店', '图书馆', '咖啡厅靠窗位', '室内', '白墙背景', '艺术场景'],
  custom95_r01_g01: ['植物园', '花园', '公园长椅', '公园', '度假酒店', '民宿庭院', '咖啡馆户外座位', '户外', '绿植背景', '自然场景'],
  custom96_r01_g01: ['海边', '海滨步道', '日落海边', '金色黄昏', '旅行大片', '蜜月', '纪念日', '度假场景', '沙滩', '海面背景'],
  custom97_r01_g01: ['欧洲老城', '古镇石板路', '鹅卵石街道', '彩色建筑', '旅行街拍', '城市漫步', '特色街道', '机场', '火车站出发层', '旅行路上'],
  custom98_r01_g01: ['黄昏草地', '旷野草地', '金色草丛', '海边沙滩', '山顶', '开阔自然场景', '金色逆光', '黄昏', '电影感场景'],
  custom99_r01_g01: ['海滩', '湖边日落', '日落海边', '浅水', '湿沙', '无边泳池', '温泉池边', '草原', '花海', '开阔自然场景'],
  custom100_r01_g01: ['日落海滩', '海边', '湖边', '沙漠', '水天线', '湿沙滩', '海平线', '金色夕阳', '开阔自然场景', '电影感场景'],
  custom101_r01_g01: ['现代建筑', '美术馆楼梯', '楼梯', '写字楼', '创意园区', '工业风楼梯', '玻璃幕墙走廊', '停车场', '地下通道', '几何光影'],
  custom102_r01_g01: ['湖边栈道', '湖边', '河边码头', '码头', '山顶观景台', '水面', '远山', '静谧自然场景', '柔和逆光'],
  custom103_r01_g01: ['湖边', '河边码头', '木码头', '水库', '池塘栈桥', '海边礁石', '堤坝', '晨雾', '黎明', '水面倒影'],
  custom104_r01_g01: ['欧洲古镇小巷', '欧洲古镇', '鹅卵石窄巷', '海边步道', '花田小径', '旅行街道', '有纵深感街道', '午后暖阳', '粉彩建筑'],
  custom105_r01_g01: ['薰衣草田', '薰衣草花海', '花田', '向日葵花海', '麦田', '花垄', '田园', '开阔自然场景', '金色夕阳', '金色时刻']
}

const getPoseSearchKeywords = (pairId) => [
  ...(poseSearchKeywordOverrides[pairId] || []),
  ...(poseSceneKeywordOverrides[pairId] || [])
]

const combinePairPoses = combinePairIds.map((pairId, index) => {
  const folder = pairId.split('_')[0]
  const poseNumber = Number(folder.replace('custom', '')) || index + 1

  return {
    id: `pair-${pairId.replace(/_/g, '-')}`,
    categoryId: 'model-pairs',
    categoryName: '真人示例',
    name: `真人姿势 ${String(poseNumber).padStart(2, '0')}`,
    tip: '先看真人示意，进入相机后按轮廓对齐',
    description: '选择页展示真人模特照片；进入相机后显示对应透明轮廓，用于对齐姿势和构图。',
    badge: '真人',
    accent: '#f4f7ff',
    gradient: 'linear-gradient(150deg, #f7f1e8 0%, #6f665f 100%)',
    guideImage: `/static/pose_pairs/${folder}/${pairId}_contour.png`,
    thumbnailImage: `/static/pose_thumbs/${folder}/${pairId}_thumb.jpg`,
    shareImage: `/static/share_images/${folder}/${pairId}_share.jpg`,
    modelImage: `/static/pose_pairs/${folder}/${pairId}_demo.jpg`,
    detailImage: `/static/pose_pairs/${folder}/${pairId}_demo.jpg`,
    thumbnailMode: 'aspectFill',
    parts: [],
    ...poseMetadataOverrides[pairId],
    searchKeywords: getPoseSearchKeywords(pairId)
  }
})

module.exports = {
  combinePairPoses
}
