// Generated from the two themed HTML imports in /Users/bytedance/Downloads/tobecheck.
const importedPoseRecords = [
  {
    "id": "custom941_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "歪头水瓶",
    "tip": "推荐城市街头、林荫路、歪头水瓶照片",
    "description": "肩线向水瓶反方向轻压，先摆出俏皮歪头。拿水瓶的手离脸侧一点，瓶身露出来更清爽。身体前倾但腰背别塌，另一侧手臂自然打开。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "歪头水瓶",
      "半身",
      "歪头",
      "水瓶",
      "手持饮料",
      "身体前倾",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "歪头水瓶",
      "城市生活街拍场景，拍歪头水瓶照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom942_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "帽檐咬冰",
    "tip": "推荐城市街头、林荫路、帽檐咬冰照片",
    "description": "帽檐压低一点，眼神从帽檐下方看镜头。冰淇淋靠近嘴边，手肘内收形成小巧轮廓。外套袖口保持蓬松，包带自然垂在肩侧。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "帽檐咬冰",
      "半身",
      "扶帽",
      "冰淇淋",
      "帽檐",
      "侧身",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "帽檐咬冰",
      "城市生活街拍场景，拍帽檐咬冰照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom943_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "蹲抱猫猫",
    "tip": "推荐城市街头、林荫路、蹲抱猫猫照片",
    "description": "先蹲稳，双臂叠在膝前形成圆润上半身。猫绳和猫的位置要放在身体前侧，不要挡脸。背包靠侧后方，保留一点体积增强街头感。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "蹲姿",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "蹲抱猫猫",
      "蹲姿",
      "抱膝",
      "猫咪",
      "宠物互动",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "蹲抱猫猫",
      "城市生活街拍场景，拍蹲抱猫猫照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom944_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "举杯兔耳",
    "tip": "推荐城市街头、林荫路、举杯兔耳照片",
    "description": "双手把杯子举到头顶两侧，手腕向外打开。肩膀放松，脸正对镜头，笑容是主表情。帆布包留在身体一侧，裙摆自然垂直。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "举杯兔耳",
      "半身",
      "举杯",
      "兔耳手势",
      "双手抬高",
      "帆布包",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "举杯兔耳",
      "城市生活街拍场景，拍举杯兔耳照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom945_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "回身挥手",
    "tip": "推荐城市街头、林荫路、回身挥手照片",
    "description": "身体向前走，头和上半身回望镜头。一只手向远处伸开，另一侧包带自然下垂。头发可顺风散开，但脸部轮廓要露出来。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "回身挥手",
      "半身",
      "回眸",
      "挥手",
      "行走",
      "背影",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "回身挥手",
      "城市生活街拍场景，拍回身挥手照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom946_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "窗边探身",
    "tip": "推荐城市街头、林荫路、窗边探身照片",
    "description": "身体从窗边向镜头探出，腰部轻轻前折。一只手扶腰或靠桌边，另一侧肩膀自然下沉。饮料放在窗台附近，作为夏日街拍小道具。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "窗边探身",
      "半身",
      "窗边",
      "探身",
      "饮料",
      "身体前倾",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "窗边探身",
      "城市生活街拍场景，拍窗边探身照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom947_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "靠窗吸饮",
    "tip": "推荐城市街头、林荫路、靠窗吸饮照片",
    "description": "背部贴近窗框，身体微侧，头转向镜头。吸管或杯子靠近嘴边，手指动作保持小而清楚。另一只手自然垂下，避免遮住腰线。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "靠窗吸饮",
      "半身",
      "靠窗",
      "吸管",
      "捧杯",
      "侧身",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "靠窗吸饮",
      "城市生活街拍场景，拍靠窗吸饮照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom948_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "树下捧杯",
    "tip": "推荐城市街头、林荫路、树下捧杯照片",
    "description": "身体靠近树干，双手把杯子放在身前。肩颈打开，头微微偏向镜头，表情保持安静。包带沿肩线垂下，别让包身挡住腰部。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "树下捧杯",
      "半身",
      "树下",
      "捧杯",
      "站姿",
      "肩颈",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "树下捧杯",
      "城市生活街拍场景，拍树下捧杯照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom949_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "果汁遮眼",
    "tip": "推荐城市街头、林荫路、果汁遮眼照片",
    "description": "杯子举到一侧眼前，另一只眼看向镜头。手肘向外形成三角形，蓝色开衫自然垂落。站姿保持轻松，包放低一些别抢杯子。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "果汁遮眼",
      "半身",
      "举杯",
      "手臂三角",
      "开衫",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "果汁遮眼",
      "城市生活街拍场景，拍果汁遮眼照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom950_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "回眸拿机",
    "tip": "推荐城市街头、林荫路、回眸拿机照片",
    "description": "身体背向街道，头和肩膀转回来笑。手机拿在胸前偏下，别挡住脸和肩线。上半身微斜，发丝顺着转头方向自然散开。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "回眸拿机",
      "半身",
      "回眸",
      "拿手机",
      "侧身",
      "转肩",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "回眸拿机",
      "城市生活街拍场景，拍回眸拿机照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom951_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "街口回望",
    "tip": "推荐城市街头、林荫路、街口回望照片",
    "description": "身体朝街道前方，头回看镜头，背包在身后。帽檐和脸部都露出来，肩带线条保持清楚。一只手轻拉包带，另一只手自然放松。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "街口回望",
      "半身",
      "街口",
      "回望",
      "背包",
      "扶帽",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "街口回望",
      "城市生活街拍场景，拍街口回望照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom952_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "市集回身",
    "tip": "推荐城市街头、林荫路、市集回身照片",
    "description": "身体侧转，回头看镜头，单肩包甩在身后。一只手带动包带，另一只手轻放身体前侧。长发顺着转身方向铺开，动作会更有速度感。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "市集回身",
      "半身",
      "市集",
      "回身",
      "单肩包",
      "转身",
      "城市街头",
      "林荫路",
      "街边",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "市集回身",
      "城市生活街拍场景，拍市集回身照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom953_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "树旁比耶",
    "tip": "推荐城市街头、林荫路、树旁比耶照片",
    "description": "身体站在树侧，双手比耶放在肩膀两旁。一侧靠近树干但不要被树遮住手势。裙摆保持垂直，脚尖稍微分开站稳。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "树旁比耶",
      "全身",
      "树旁",
      "比耶",
      "双手手势",
      "全身照",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "树旁比耶",
      "城市生活街拍场景，拍树旁比耶照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom954_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "马路双杯",
    "tip": "推荐城市街头、林荫路、马路双杯照片",
    "description": "身体向一侧倾斜，双手分别举起饮料和小物。帽子压低但脸要露出，肩线跟身体倾斜同步。短裙下摆保持蓬松，双腿重心放在一侧。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "马路双杯",
      "全身",
      "马路",
      "双杯",
      "侧倾",
      "全身照",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "马路双杯",
      "城市生活街拍场景，拍马路双杯照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom955_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "光影捧心",
    "tip": "推荐城市街头、林荫路、光影捧心照片",
    "description": "双手靠近胸前，动作要小，突出脸部表情。身体正对镜头，肩膀放平，头发自然包住脸侧。让斑驳光停在肩颈和头发上，脸部不要过曝。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "光影捧心",
      "半身",
      "光影",
      "捧心",
      "近景",
      "半身照",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "光影捧心",
      "城市生活街拍场景，拍光影捧心照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom956_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "果摊托腮",
    "tip": "推荐城市街头、林荫路、果摊托腮照片",
    "description": "坐在果摊前，双手托腮，手肘落在膝前。身体略向镜头靠近，膝盖和脚尖保持正向。水果背景可以丰富，但不要让招牌压住头部。适合街拍、城市漫游和生活感拍照模板。此版按最新裁切边界约束重做，重点是不补画参考图之外的身体部位。",
    "badge": "坐姿",
    "gradient": "linear-gradient(150deg, #315f46 0%, #efc77d 100%)",
    "searchKeywords": [
      "城市生活街拍",
      "果摊托腮",
      "坐姿",
      "果摊",
      "托腮",
      "水果",
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游"
    ],
    "sceneKeywords": [
      "城市街头",
      "林荫路",
      "街边",
      "市集",
      "生活街拍",
      "城市漫游",
      "果摊托腮",
      "城市生活街拍场景，拍果摊托腮照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom957_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "花束抬腿",
    "tip": "推荐新疆、草原、花束抬腿照片",
    "description": "举花那只手要斜冲天空，手腕别塌下去。侧抬腿轻搭木栏，靴尖朝外更显俏皮。平视取景把木栏、牛群和云层一起带进画面。适合在牧场木栏边拍出迎风打招呼的第一眼活力。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "花束抬腿",
      "全身",
      "花束",
      "抬腿",
      "举花",
      "木栏",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "花束抬腿",
      "新疆草原旅拍场景，拍花束抬腿照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom958_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "山丘静立",
    "tip": "推荐新疆、草原、山丘静立照片",
    "description": "肩膀放松垂直站稳，别把身体重心歪向一边。双腿一前一后微叠，裤脚自然落地更显修长。机位略低一点，让起伏草坡从脚边一路抬到天际。适合草坡特别开阔、背景干净的时候拍出安静高级感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "山丘静立",
      "全身",
      "山丘",
      "静立",
      "站姿",
      "草帽",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "山丘静立",
      "新疆草原旅拍场景，拍山丘静立照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom959_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "草帽踢步",
    "tip": "推荐新疆、草原、草帽踢步照片",
    "description": "扶帽那只手别压太低，保持像迎风整理帽檐。前踢腿要伸直，脚尖往前送才有行进中的轻快感。从人物侧前方拍，裙摆和树林深度都会更明显。适合针叶林前的草地边缘，能拍出边走边玩的旅拍感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "草帽踢步",
      "全身",
      "扶帽",
      "踢步",
      "行走",
      "裙摆",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "草帽踢步",
      "新疆草原旅拍场景，拍草帽踢步照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom960_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "溪畔遮阳",
    "tip": "推荐新疆、草原、溪畔遮阳照片",
    "description": "遮阳那只手抬到眉骨上方，眼神顺着手臂看远处。双腿交叉时前脚点地，裙摆自然散开不要夹腿。稍低机位把溪流和雪山压进同一条纵深线上。适合站在山泉边远望雪峰，画面会有清冷又柔和的感觉。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "溪畔遮阳",
      "全身",
      "溪畔",
      "遮阳",
      "交叉腿",
      "远眺",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "溪畔遮阳",
      "新疆草原旅拍场景，拍溪畔遮阳照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom961_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "红裙平衡",
    "tip": "推荐新疆、草原、红裙平衡照片",
    "description": "两臂尽量向两侧拉平，像在横木后轻轻找平衡。侧抬腿往后送，脚尖绷一点，裙摆线条会更漂亮。正面中景拍摄，把倒木和高树当成天然舞台背景。适合森林里有粗木头或栈道的地方，红裙会特别跳出来。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "红裙平衡",
      "全身",
      "红裙",
      "平衡",
      "展臂",
      "侧抬腿",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "红裙平衡",
      "新疆草原旅拍场景，拍红裙平衡照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom962_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "溪石拎包",
    "tip": "推荐新疆、草原、溪石拎包照片",
    "description": "双手在身前轻拎编织包，手臂别贴死在裙摆上。双腿并拢略朝一侧站，人物会显得更温柔秀气。镜头从侧前方拍，让溪流走势自然带出人物位置。适合雪山融水形成的浅溪边，画面会有很干净的清凉感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "溪石拎包",
      "全身",
      "溪石",
      "拎包",
      "站姿",
      "编织包",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "溪石拎包",
      "新疆草原旅拍场景，拍溪石拎包照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom963_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "迎风舒展",
    "tip": "推荐新疆、草原、迎风舒展照片",
    "description": "双臂一高一低向外展开，外套要像被风带起来。双腿分开站稳，胸口向上打开才有拥抱天空的感觉。低角度拍摄，把云和山坡都留足，人物会更有张力。适合站在高处草原迎风伸展，特别能拍出辽阔和自由。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "迎风舒展",
      "全身",
      "迎风",
      "舒展",
      "张臂",
      "低机位",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "迎风舒展",
      "新疆草原旅拍场景，拍迎风舒展照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom964_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "草坡翘腿",
    "tip": "推荐新疆、草原、草坡翘腿照片",
    "description": "拿草帽的手自然垂在身侧，别抢过脸部表情。后翘腿抬到小腿明显离地，裙摆才会显得轻盈。从人物斜前方拍，能同时保住笑脸和远山纵深。适合高山草坡和云雾背景，白裙会显得特别轻巧。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "草坡翘腿",
      "全身",
      "草坡",
      "翘腿",
      "草帽",
      "白裙",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "草坡翘腿",
      "新疆草原旅拍场景，拍草坡翘腿照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom965_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "溪边提篮",
    "tip": "推荐新疆、草原、溪边提篮照片",
    "description": "扶帽那只手停在帽檐侧边，别完全挡住额头。提篮那只手自然下垂，后踢腿角度要轻快不要太高。平视机位抓回头瞬间，最容易拍出俏皮和亲切感。适合清溪和松林同框的位置，像在林间散步忽然回头。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "溪边提篮",
      "全身",
      "溪边",
      "提篮",
      "扶帽",
      "后踢",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "溪边提篮",
      "新疆草原旅拍场景，拍溪边提篮照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom966_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "草原张臂",
    "tip": "推荐新疆、草原、草原张臂照片",
    "description": "双臂向两侧完全打开，手掌略朝前更有拥抱感。双腿分开站稳，身体微微侧转会比正对镜头更自然。中景取景时把牛群和草坡留出来，画面更有牧场气。适合在开阔牧场中央拍出人被风景包围的自由感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "草原张臂",
      "全身",
      "草原",
      "张臂",
      "拥抱",
      "牧场",
      "新疆",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "草原张臂",
      "新疆草原旅拍场景，拍草原张臂照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom967_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "教堂拎包",
    "tip": "推荐新疆、草原、教堂拎包照片",
    "description": "双手交叠握住包链，肩颈挺直才能显出端庄感。双脚安静并拢站稳，别把胯部侧扭得太明显。机位稍远一些，把羊群、小教堂和雪山都完整收入。适合牧场教堂或小木屋附近，画面会有很安静的电影感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "教堂拎包",
      "全身",
      "教堂",
      "拎包",
      "静立",
      "羊群",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "教堂拎包",
      "新疆草原旅拍场景，拍教堂拎包照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom968_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "雪山比耶",
    "tip": "推荐新疆、草原、雪山比耶照片",
    "description": "双手比耶时往镜头前送，手臂交叠会更有冲击力。后翘腿向斜后方抬起，裙摆才会拉出明显动势。机位压低一点，让雪山直接托住人物上半身。适合雪山草坡这种大背景，用夸张动作拍出旅行兴奋感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "雪山比耶",
      "全身",
      "雪山",
      "比耶",
      "后踢",
      "手臂交叠",
      "新疆",
      "草原",
      "牧场",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "雪山比耶",
      "新疆草原旅拍场景，拍雪山比耶照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom969_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "羊群回眸",
    "tip": "推荐新疆、草原、羊群回眸照片",
    "description": "靠脸那只手轻放面侧，别把五官遮得太严。身体保持侧身，提包那侧肩膀略往后收更显线条。利用逆光或侧逆光，把羊群和发丝边缘一起拍亮。适合有羊群慢悠悠吃草的草坪，画面会很温柔治愈。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "羊群回眸",
      "全身",
      "羊群",
      "回眸",
      "侧身",
      "提包",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "羊群回眸",
      "新疆草原旅拍场景，拍羊群回眸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom970_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "湖畔跃拍",
    "tip": "推荐新疆、草原、湖畔跃拍照片",
    "description": "高举相机那只手要完全伸直，跳起时更有冲刺感。腾空腿往上收，另一条腿顺势下压才能形成跳跃层次。快门要抓在最高点，把湖水和松林同时留进背景。适合湖边或山坡这种空间很开的地方，动作一跳就很出片。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "湖畔跃拍",
      "全身",
      "湖畔",
      "跃拍",
      "举相机",
      "跳跃",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "湖畔跃拍",
      "新疆草原旅拍场景，拍湖畔跃拍照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom971_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "红衣展臂",
    "tip": "推荐新疆、草原、红衣展臂照片",
    "description": "双臂左右铺开并微微上托，掌心朝上更显开阔。下盘站稳别晃，长裙自然垂落才能压住画面重心。略低机位拍，把乌云、山体和草地的层次全带出来。适合阴天草原或山前空地，红上衣会成为最醒目的焦点。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "红衣展臂",
      "全身",
      "红衣",
      "展臂",
      "长裙",
      "站姿",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "红衣展臂",
      "新疆草原旅拍场景，拍红衣展臂照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom972_r01_g01",
    "categoryId": "travel-back",
    "categoryName": "旅行打卡",
    "name": "彩虹读书",
    "tip": "推荐新疆、草原、彩虹读书照片",
    "description": "举手那侧手臂要斜向彩虹，手掌自然打开别僵硬。站在横木上时上身保持端正，书本放胸前更显文艺。平视机位保住彩虹弧线和溪流走向，氛围会更完整。适合雨后初晴的溪畔森林，彩虹和倒木会让画面非常梦幻。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #61b6e7 0%, #557c35 100%)",
    "searchKeywords": [
      "新疆草原旅拍",
      "彩虹读书",
      "全身",
      "彩虹",
      "读书",
      "举手",
      "溪畔",
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡"
    ],
    "sceneKeywords": [
      "新疆",
      "草原",
      "牧场",
      "雪山",
      "溪流",
      "森林",
      "旅行打卡",
      "彩虹读书",
      "新疆草原旅拍场景，拍彩虹读书照片"
    ],
    "width": 1536,
    "height": 2048
  }
]

const importedPoseIds = importedPoseRecords.map((record) => record.id)
const importedPoseMetadataOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, {
  categoryId: record.categoryId,
  categoryName: record.categoryName,
  name: record.name,
  tip: record.tip,
  description: record.description,
  badge: record.badge,
  guideImage: `/static/pose_pairs/${record.id.split('_')[0]}/${record.id}_contour.png`,
  gradient: record.gradient
}]))
const importedPoseSearchKeywordOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, record.searchKeywords]))
const importedPoseSceneKeywordOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, record.sceneKeywords]))
const importedGuideImageSizes = Object.fromEntries(importedPoseRecords.map((record) => [
  `/static/pose_pairs/${record.id.split('_')[0]}/${record.id}_contour.png`,
  { width: record.width, height: record.height }
]))

module.exports = {
  importedPoseIds,
  importedPoseMetadataOverrides,
  importedPoseSearchKeywordOverrides,
  importedPoseSceneKeywordOverrides,
  importedGuideImageSizes
}
