// Generated from cafe_daily_pose_guide_final.html.
const importedPoseRecords = [
  {
    "id": "custom1021_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "蛋糕遮脸",
    "tip": "推荐咖啡馆、甜品店场景，拍蛋糕遮脸照片",
    "description": "双手端住小蛋糕托盘杯沿抬到鼻尖位置宽松袖口自然外展适合甜品上桌后的第一张打卡照。用蛋糕遮住表情，画面会更有神秘感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "蛋糕遮脸",
      "半身",
      "遮脸",
      "蛋糕",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "蛋糕遮脸",
      "咖啡馆日常场景，拍蛋糕遮脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1022_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "捧杯低头",
    "tip": "推荐咖啡馆、甜品店场景，拍捧杯低头照片",
    "description": "双手捧杯靠近唇边帽檐压低遮住眼睛手肘轻落桌面保持稳定适合热咖啡或拿铁场景。帽檐和杯子一起遮脸，氛围安静又日常。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "捧杯低头",
      "半身",
      "遮脸",
      "捧杯",
      "低头",
      "帽檐",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "捧杯低头",
      "咖啡馆日常场景，拍捧杯低头照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1023_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "毛帽端杯",
    "tip": "推荐咖啡馆、甜品店场景，拍毛帽端杯照片",
    "description": "双手分握黑色杯身毛帽压住额头制造遮挡肩膀微微内收显得安静适合粗粝墙面或复古咖啡馆。黑杯和毛帽能让姿势更有冬日感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "毛帽端杯",
      "半身",
      "端杯",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "毛帽端杯",
      "咖啡馆日常场景，拍毛帽端杯照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1024_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "黑帽抿饮",
    "tip": "推荐咖啡馆、甜品店场景，拍黑帽抿饮照片",
    "description": "一手拿手机一手抵唇黑帽低垂遮住上半脸身体微向桌面前倾适合一个人坐在角落时拍摄。手机和咖啡杯能自然带出生活记录感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "黑帽抿饮",
      "半身",
      "抿饮",
      "手机",
      "前倾",
      "咖啡杯",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "黑帽抿饮",
      "咖啡馆日常场景，拍黑帽抿饮照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1025_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "手机挡脸",
    "tip": "推荐咖啡馆、甜品店场景，拍手机挡脸照片",
    "description": "手机竖举挡住面部中心另一只手靠近杯口手臂形成斜线更显慵懒适合窗边座位和浅色桌面。手机挡脸能降低表情压力，重点放在手部线条。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "手机挡脸",
      "半身",
      "手机",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "手机挡脸",
      "咖啡馆日常场景，拍手机挡脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1026_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "交手遮脸",
    "tip": "推荐咖啡馆、甜品店场景，拍交手遮脸照片",
    "description": "双手交叠挡住脸部头发垂落在手臂两侧上身靠近桌面保持收拢适合想拍害羞感或慵懒感的时候。交叠手势能让画面更柔软。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "交手遮脸",
      "半身",
      "遮脸",
      "交手",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "交手遮脸",
      "咖啡馆日常场景，拍交手遮脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1027_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "托腮咖啡",
    "tip": "推荐咖啡馆、甜品店场景，拍托腮咖啡照片",
    "description": "单手托腮贴近咖啡杯帽檐斜向镜头一侧杯子贴脸形成核心动作适合小桌咖啡特写。托腮与杯子贴近，容易拍出亲密、松弛的感觉。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "托腮咖啡",
      "半身",
      "托腮",
      "帽檐",
      "咖啡杯",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "托腮咖啡",
      "咖啡馆日常场景，拍托腮咖啡照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1028_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "侧坐举杯",
    "tip": "推荐咖啡馆、甜品店场景，拍侧坐举杯照片",
    "description": "身体侧坐面向黑板墙单手举饮品在胸前长发顺肩自然下垂适合有黑板菜单或吧台背景的座位。侧坐让身体线条更完整，饮品更突出。",
    "badge": "坐姿",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "侧坐举杯",
      "坐姿",
      "侧坐",
      "举杯",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "侧坐举杯",
      "咖啡馆日常场景，拍侧坐举杯照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1029_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "趴桌休息",
    "tip": "推荐咖啡馆、甜品店场景，拍趴桌休息照片",
    "description": "趴在桌面放松肩颈帽子朝向镜头遮脸一手前伸一手自然弯曲适合朋友抓拍和疲惫感氛围。趴桌姿势要保留帽檐和前伸手臂。",
    "badge": "趴姿",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "趴桌休息",
      "趴姿",
      "遮脸",
      "趴桌",
      "帽檐",
      "帽子",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "趴桌休息",
      "咖啡馆日常场景，拍趴桌休息照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1030_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "侧身饮咖",
    "tip": "推荐咖啡馆、甜品店场景，拍侧身饮咖照片",
    "description": "侧头轻靠咖啡杯肩线略斜不要端正站直另一只手自然落在桌面适合复古咖啡馆的半身照。杯子放在脸侧，可以让视线自然集中。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "侧身饮咖",
      "半身",
      "侧身",
      "咖啡杯",
      "半身照",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "侧身饮咖",
      "咖啡馆日常场景，拍侧身饮咖照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1031_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "侧脸甜点",
    "tip": "推荐咖啡馆、甜品店场景，拍侧脸甜点照片",
    "description": "侧脸看向柜台方向手肘撑桌托住脸颊饮品放在身体前侧适合靠近甜品柜的位置。侧脸托腮能营造等餐或发呆的电影感。",
    "badge": "坐姿",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "侧脸甜点",
      "坐姿",
      "托腮",
      "侧脸",
      "甜点",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "侧脸甜点",
      "咖啡馆日常场景，拍侧脸甜点照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1032_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "托腮拍照",
    "tip": "推荐咖啡馆、甜品店场景，拍托腮拍照照片",
    "description": "双肘伏桌托腮看手机侧脸轮廓对准窗光手机竖屏靠近脸侧适合窗边桌面和手机入镜。托腮看屏幕能形成自然的故事瞬间。",
    "badge": "坐姿",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "托腮拍照",
      "坐姿",
      "手机",
      "托腮",
      "侧脸",
      "拍照",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "托腮拍照",
      "咖啡馆日常场景，拍托腮拍照照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1033_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "帽檐端杯",
    "tip": "推荐咖啡馆、甜品店场景，拍帽檐端杯照片",
    "description": "帽檐压低只露杯口一手端小黑杯居中围巾和袖口自然叠放适合冷天咖啡馆穿搭。帽檐、围巾与小杯子组合，遮脸但姿势很明确。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "帽檐端杯",
      "半身",
      "遮脸",
      "端杯",
      "帽檐",
      "围巾",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "帽檐端杯",
      "咖啡馆日常场景，拍帽檐端杯照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1034_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "樱桃甜饮",
    "tip": "推荐咖啡馆、甜品店场景，拍樱桃甜饮照片",
    "description": "一手扶眼镜一手收在身侧蓝色甜饮放在正前方身体微微前倾对镜头适合甜品饮料同框。蓝色饮品在前，人物动作轻巧，画面更活泼。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "樱桃甜饮",
      "半身",
      "扶眼镜",
      "前倾",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "樱桃甜饮",
      "咖啡馆日常场景，拍樱桃甜饮照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1035_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "抬臂遮脸",
    "tip": "推荐咖啡馆、甜品店场景，拍抬臂遮脸照片",
    "description": "手臂抬起横向遮脸另一手撑住帽檐附近橙色饮品放在下方中心适合靠墙小桌和饮品特写。抬臂遮脸能制造随性抓拍感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "抬臂遮脸",
      "半身",
      "遮脸",
      "帽檐",
      "抬臂",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "抬臂遮脸",
      "咖啡馆日常场景，拍抬臂遮脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1036_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "杯前眨眼",
    "tip": "推荐咖啡馆、甜品店场景，拍杯前眨眼照片",
    "description": "杯子贴近嘴唇挡住下脸一只眼睛看向镜头手指抓稳杯柄姿势清晰适合工业风或大窗咖啡馆。杯子遮住下脸，眼神和帽檐是画面重点。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #5b493e 0%, #d6aa74 100%)",
    "searchKeywords": [
      "咖啡馆遮脸日常",
      "杯前眨眼",
      "半身",
      "帽檐",
      "眨眼",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "咖啡探店",
      "室内人像",
      "杯前眨眼",
      "咖啡馆日常场景，拍杯前眨眼照片"
    ],
    "width": 1536,
    "height": 2048
  }
]

const importedPoseIds = importedPoseRecords.map((record) => record.id)
const importedPoseMetadataOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, {
  categoryId: record.categoryId,
  categoryName: record.categoryName,
  name: record.name,
  tip: record.tip,
  description: record.description,
  badge: record.badge,
  guideImage: `/static/pose_pairs/${record.id.split('_')[0]}/${record.id}_contour.png`,
  gradient: record.gradient
}]))
const importedPoseSearchKeywordOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, record.searchKeywords]))
const importedPoseSceneKeywordOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, record.sceneKeywords]))
const importedGuideImageSizes = Object.fromEntries(importedPoseRecords.map((record) => [
  `/static/pose_pairs/${record.id.split('_')[0]}/${record.id}_contour.png`,
  { width: record.width, height: record.height }
]))

module.exports = {
  importedPoseIds,
  importedPoseMetadataOverrides,
  importedPoseSearchKeywordOverrides,
  importedPoseSceneKeywordOverrides,
  importedGuideImageSizes
}
