// Generated from the three themed HTML imports in /Users/bytedance/Downloads/tobecheck.
const importedPoseRecords = [
  {
    "id": "custom973_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "托腮甜笑",
    "tip": "推荐咖啡馆、甜品店场景，拍托腮甜笑照片",
    "description": "手肘贴桌，手掌轻托下颌肩膀放松，身体微微前倾视线看镜头，嘴角自然上扬适合窗边或圆桌前拍清甜日常照。用桌面作前景，人物上半身占画面中心，整体更有亲近感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "托腮甜笑",
      "半身",
      "托腮",
      "前倾",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "托腮甜笑",
      "咖啡馆日常场景，拍托腮甜笑照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom974_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "指尖嘟嘴",
    "tip": "推荐咖啡馆、甜品店场景，拍指尖嘟嘴照片",
    "description": "双手食指轻点脸颊两侧镜框保持水平，脸正对镜头手臂自然收拢，不遮住下巴适合朋友聚会时拍俏皮近景。动作小巧，适合用柔光和暖色背景突出少女感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "指尖嘟嘴",
      "半身",
      "指尖",
      "嘟嘴",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "指尖嘟嘴",
      "咖啡馆日常场景，拍指尖嘟嘴照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom975_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "歪头托腮",
    "tip": "推荐咖啡馆、甜品店场景，拍歪头托腮照片",
    "description": "一侧手背轻托脸侧肩线稍微倾斜，头向手边靠另一只手自然拿手机或放桌上适合靠窗座位和下午茶场景。歪头能让画面更松弛，搭配甜点会更有故事感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "歪头托腮",
      "半身",
      "托腮",
      "托脸",
      "歪头",
      "手机",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "歪头托腮",
      "咖啡馆日常场景，拍歪头托腮照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom976_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "勺尖凝视",
    "tip": "推荐咖啡馆、甜品店场景，拍勺尖凝视照片",
    "description": "双手靠近脸侧，勺子停在唇边上半身端坐，肩膀略内收眼神看镜头，表情保持安静适合拍安静精致的咖啡馆人像。小道具能引导视线，画面气质更干净。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "勺尖凝视",
      "半身",
      "凝视",
      "勺子",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "勺尖凝视",
      "咖啡馆日常场景，拍勺尖凝视照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom977_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "叉尖入口",
    "tip": "推荐咖啡馆、甜品店场景，拍叉尖入口照片",
    "description": "一手举叉靠近嘴边身体坐直，另一手自然放低脸部正对镜头，眼神稳定适合甜品店打卡照。动作像刚准备品尝甜点，画面有自然生活感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "叉尖入口",
      "半身",
      "甜品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "叉尖入口",
      "咖啡馆日常场景，拍叉尖入口照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom978_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "窗边托脸",
    "tip": "推荐咖啡馆、甜品店场景，拍窗边托脸照片",
    "description": "一手托腮，身体向桌面微靠肩膀斜向镜头，头部略偏饮品和蛋糕放在身前偏侧适合窗边咖啡馆的温柔氛围照。侧身构图能突出慵懒感，也适合拍半身特写。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "窗边托脸",
      "半身",
      "托腮",
      "托脸",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "窗边托脸",
      "咖啡馆日常场景，拍窗边托脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom979_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "遮嘴自拍",
    "tip": "推荐咖啡馆、甜品店场景，拍遮嘴自拍照片",
    "description": "一手拿手机靠近桌面另一手袖口遮住嘴角头微低，眼神向下或看屏幕适合自拍感强的日常记录。遮嘴动作显得害羞自然，适合轻松社交平台照片。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "遮嘴自拍",
      "半身",
      "自拍",
      "手机",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "遮嘴自拍",
      "咖啡馆日常场景，拍遮嘴自拍照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom980_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "低头玩机",
    "tip": "推荐咖啡馆、甜品店场景，拍低头玩机照片",
    "description": "双手握手机，视线落在屏幕上半身略前倾，手臂靠近桌缘咖啡杯放在正前方形成支点适合夜晚咖啡馆或聊天间隙抓拍。低头看手机能营造沉浸感，画面更生活化。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "低头玩机",
      "半身",
      "手机",
      "低头",
      "前倾",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "低头玩机",
      "咖啡馆日常场景，拍低头玩机照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom981_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "双手托脸",
    "tip": "推荐咖啡馆、甜品店场景，拍双手托脸照片",
    "description": "两手掌贴脸颊，手肘落桌头部保持正中，肩膀自然下沉饮品握在前方，手腕放松适合桌前近景和可爱风照片。双手托脸能缩短视觉距离，适合表现发呆氛围。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "双手托脸",
      "半身",
      "托脸",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "双手托脸",
      "咖啡馆日常场景，拍双手托脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom982_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "手比爱心",
    "tip": "推荐咖啡馆、甜品店场景，拍手比爱心照片",
    "description": "双手在眼前合成爱心身体正对镜头，手臂抬到脸前饮品放中间，吸管作为前景线适合朋友帮拍的甜美互动照。爱心手势很醒目，适合用作封面或九宫格中心图。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "手比爱心",
      "半身",
      "爱心",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "手比爱心",
      "咖啡馆日常场景，拍手比爱心照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom983_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "低头看杯",
    "tip": "推荐咖啡馆、甜品店场景，拍低头看杯照片",
    "description": "身体侧向窗边，头低看桌面手臂靠近杯子，肩颈保持放松饮品放在人物视线落点适合拍安静文艺的侧身照。低头动作能弱化镜头感，咖啡杯让姿势更有落点。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "低头看杯",
      "半身",
      "低头",
      "饮品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "低头看杯",
      "咖啡馆日常场景，拍低头看杯照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom984_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "侧靠托腮",
    "tip": "推荐咖啡馆、甜品店场景，拍侧靠托腮照片",
    "description": "单手支在下巴旁，另一臂搭桌肩膀一高一低，身体微微侧坐眼神看镜头，表情保持柔和适合浅色咖啡馆环境。侧靠能突出锁骨和肩线，适合温柔轻熟风。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "侧靠托腮",
      "半身",
      "托腮",
      "侧靠",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "侧靠托腮",
      "咖啡馆日常场景，拍侧靠托腮照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom985_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "捧脸浅笑",
    "tip": "推荐咖啡馆、甜品店场景，拍捧脸浅笑照片",
    "description": "双掌贴脸，手肘撑在桌边脸居中，肩膀向内收一点餐盘和咖啡在前景保持完整适合早餐或甜品桌前拍元气照。捧脸动作亲和力强，适合轻松日常主题。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "捧脸浅笑",
      "半身",
      "捧脸",
      "甜品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "捧脸浅笑",
      "咖啡馆日常场景，拍捧脸浅笑照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom986_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "手机贴脸",
    "tip": "推荐咖啡馆、甜品店场景，拍手机贴脸照片",
    "description": "一手举手机靠近脸侧另一只手托住脸或衣领头部微低，眼神看向镜头适合自拍与他拍结合的咖啡馆照。手机作为道具能增加真实感，也适合表达等人氛围。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "手机贴脸",
      "半身",
      "自拍",
      "手机",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "手机贴脸",
      "咖啡馆日常场景，拍手机贴脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom987_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "端盘微笑",
    "tip": "推荐咖啡馆、甜品店场景，拍端盘微笑照片",
    "description": "一手托盘，身体站在柜台前肩膀打开，脸朝镜头微笑盘中甜点保持水平，手腕稳住适合咖啡馆柜台或甜品展示区。端盘动作更有服务感和探店感，适合拍全身或半身。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "端盘微笑",
      "半身",
      "端盘",
      "微笑",
      "甜品",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "端盘微笑",
      "咖啡馆日常场景，拍端盘微笑照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom988_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "捧杯侧望",
    "tip": "推荐咖啡馆、甜品店场景，拍捧杯侧望照片",
    "description": "双手捧杯靠近嘴边脸向窗外侧转，眼神不看镜头手指贴住杯身，肘部自然收拢适合窗边暖光人像。捧杯动作很安静，适合表现休息、发呆和午后咖啡感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #6b5140 0%, #d7b987 100%)",
    "searchKeywords": [
      "咖啡馆日常",
      "捧杯侧望",
      "半身",
      "捧杯",
      "侧望",
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像"
    ],
    "sceneKeywords": [
      "咖啡馆",
      "甜品店",
      "窗边",
      "下午茶",
      "探店",
      "室内人像",
      "捧杯侧望",
      "咖啡馆日常场景，拍捧杯侧望照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom989_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "俯拍拌面",
    "tip": "推荐餐厅、面馆场景，拍俯拍拌面照片",
    "description": "俯拍角度略高，脸向镜头抬起左手靠近桌边，右手自然夹面碗盘和桌面保留在画面下方适合坐在日式小店靠窗或吧台位拍开场照。用俯拍突出餐桌氛围，人物眼神直接抓镜头。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "俯拍拌面",
      "半身",
      "夹面",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "俯拍拌面",
      "餐厅美食探店场景，拍俯拍拌面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom990_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "捧碗微笑",
    "tip": "推荐餐厅、面馆场景，拍捧碗微笑照片",
    "description": "身体微微前倾，肩线放松一手托碗边，一手夹筷横向伸出脸部轻轻歪向碗，保持甜笑适合端上热汤面后的第一张打卡。画面温柔亲近，适合展示拉面和人物表情。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "捧碗微笑",
      "半身",
      "拉面",
      "捧碗",
      "微笑",
      "前倾",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "捧碗微笑",
      "餐厅美食探店场景，拍捧碗微笑照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom991_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "双指指面",
    "tip": "推荐餐厅、面馆场景，拍双指指面照片",
    "description": "双手食指在胸前形成指向上半身正对镜头，肩膀端平面碗放在下方，筷子斜放增强层次适合菜单推荐或“这碗必点”的种草画面。人物正面清晰，适合做封面卡片。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "双指指面",
      "半身",
      "筷子",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "双指指面",
      "餐厅美食探店场景，拍双指指面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom992_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "托盘嘟嘴",
    "tip": "推荐餐厅、面馆场景，拍托盘嘟嘴照片",
    "description": "双手托住小碗，手掌向镜头展开脸微微前探，嘟嘴表情更可爱甜品碗抬到胸口高度适合甜品、冰淇淋或饭后小食展示。动作有互动感，适合朋友互拍。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "托盘嘟嘴",
      "半身",
      "嘟嘴",
      "甜品",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "托盘嘟嘴",
      "餐厅美食探店场景，拍托盘嘟嘴照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom993_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "毛帽咬筷",
    "tip": "推荐餐厅、面馆场景，拍毛帽咬筷照片",
    "description": "帽子和脸部居中，眼神看镜头筷子横向靠近嘴边，夹食物形成焦点身体贴近桌面，碗放画面底部适合冬日面馆或木质餐厅氛围。帽子增加记忆点，画面有暖呼呼的吃饭感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "毛帽咬筷",
      "半身",
      "筷子",
      "毛帽",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "毛帽咬筷",
      "餐厅美食探店场景，拍毛帽咬筷照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom994_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "夹面低头",
    "tip": "推荐餐厅、面馆场景，拍夹面低头照片",
    "description": "头部微低，视线落在筷子和面上双筷分别形成交叉线条面条悬在碗上方，不要挡住脸太多适合拍真实开吃瞬间。低头动作自然，适合表达“认真吃面”的生活感。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "夹面低头",
      "半身",
      "筷子",
      "夹面",
      "低头",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "夹面低头",
      "餐厅美食探店场景，拍夹面低头照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom995_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "草帽嗦面",
    "tip": "推荐餐厅、面馆场景，拍草帽嗦面照片",
    "description": "草帽轮廓保留完整，脸在帽檐下方筷子横向托住面条，嘴部轻轻靠近面碗居中，身体正向桌面适合户外座位或明亮日式小馆。草帽和面碗共同营造清爽夏日氛围。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "草帽嗦面",
      "半身",
      "筷子",
      "嗦面",
      "草帽",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "草帽嗦面",
      "餐厅美食探店场景，拍草帽嗦面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom996_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "黑裙拉面",
    "tip": "推荐餐厅、面馆场景，拍黑裙拉面照片",
    "description": "坐姿正对镜头，双手分别持筷和碗边面条从筷尖垂落到碗中上半身挺直，眼神微低更有食欲感适合浓汤拉面、蘸面或大碗主食展示。动作完整，适合记录一人食打卡。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "黑裙拉面",
      "半身",
      "拉面",
      "坐姿",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "黑裙拉面",
      "餐厅美食探店场景，拍黑裙拉面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom997_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "托腮等面",
    "tip": "推荐餐厅、面馆场景，拍托腮等面照片",
    "description": "一手托腮，手肘自然靠桌另一手拿筷子停在侧边脸部侧向留出柔和表情适合等餐、饭前自拍或安静小馆氛围。姿势简单，很适合不想大动作的拍法。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "托腮等面",
      "半身",
      "托腮",
      "筷子",
      "自拍",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "托腮等面",
      "餐厅美食探店场景，拍托腮等面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom998_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "眨眼夹面",
    "tip": "推荐餐厅、面馆场景，拍眨眼夹面照片",
    "description": "一手托脸遮住半侧，形成眨眼表情另一手横向夹起面条身体靠近桌边，红碗放在下方适合活泼可爱的探店照片。眨眼和夹面结合，画面更像社交平台随手拍。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "眨眼夹面",
      "半身",
      "托脸",
      "夹面",
      "眨眼",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "眨眼夹面",
      "餐厅美食探店场景，拍眨眼夹面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom999_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "张口尝面",
    "tip": "推荐餐厅、面馆场景，拍张口尝面照片",
    "description": "嘴部微张，筷子夹食物靠近嘴边另一只手扶住碗边或餐具肩膀斜向镜头，保持自然转身适合拍第一口尝鲜瞬间。动作有剧情感，适合做“开吃啦”的过渡画面。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "张口尝面",
      "半身",
      "筷子",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "张口尝面",
      "餐厅美食探店场景，拍张口尝面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom1000_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "叉面侧望",
    "tip": "推荐餐厅、面馆场景，拍叉面侧望照片",
    "description": "身体微侧，目光看向画面外叉子挑起面条，停在嘴边前方盘子完整放在桌面中央适合西式日料融合店或意面打卡。侧望动作更松弛，适合拍朋友视角。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "叉面侧望",
      "半身",
      "叉子",
      "侧望",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "叉面侧望",
      "餐厅美食探店场景，拍叉面侧望照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom1001_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "眼镜举勺",
    "tip": "推荐餐厅、面馆场景，拍眼镜举勺照片",
    "description": "脸部靠近镜头，眼镜轮廓要清晰一手举勺靠近肩侧另一手拿筷子或扶碗适合近景自拍和暖光小店。眼镜、勺子和碗形成生活化细节，亲切感强。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "眼镜举勺",
      "半身",
      "勺子",
      "筷子",
      "自拍",
      "眼镜",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "眼镜举勺",
      "餐厅美食探店场景，拍眼镜举勺照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom1002_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "双筷挑面",
    "tip": "推荐餐厅、面馆场景，拍双筷挑面照片",
    "description": "双手分别持筷，面条位于脸前身体正坐，肩线保持稳定碗盘放在下方中央，筷子形成交叉适合大份炒面或拉面上桌后的展示。双手动作丰富，画面更有“开动感”。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "双筷挑面",
      "半身",
      "筷子",
      "挑面",
      "拉面",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "双筷挑面",
      "餐厅美食探店场景，拍双筷挑面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom1003_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "歪头挑面",
    "tip": "推荐餐厅、面馆场景，拍歪头挑面照片",
    "description": "头部向一侧倾斜，脸靠近筷子筷子横向抬高，面条自然下垂手臂进入前景但不要遮住五官适合拍俏皮角度和轻松探店照。歪头让画面更灵动，适合连续分镜里的变化姿势。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "歪头挑面",
      "半身",
      "歪头",
      "筷子",
      "挑面",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "歪头挑面",
      "餐厅美食探店场景，拍歪头挑面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom1004_r01_g01",
    "categoryId": "props-action",
    "categoryName": "咖啡馆/道具",
    "name": "近景拉面",
    "tip": "推荐餐厅、面馆场景，拍近景拉面照片",
    "description": "上半身靠近镜头，脸在右侧留出表情筷子高高挑起面条，形成竖向线条碗放在底部前景，面条连接碗口适合拍最有食欲的近景收尾。拉起的面条占满画面，特别适合短视频封面或结尾。",
    "badge": "半身",
    "gradient": "linear-gradient(150deg, #9a3d2b 0%, #e0ad62 100%)",
    "searchKeywords": [
      "餐厅美食探店",
      "近景拉面",
      "半身",
      "筷子",
      "拉面",
      "面条",
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像"
    ],
    "sceneKeywords": [
      "餐厅",
      "面馆",
      "拉面店",
      "美食探店",
      "桌边",
      "室内人像",
      "近景拉面",
      "餐厅美食探店场景，拍近景拉面照片"
    ],
    "width": 768,
    "height": 1024
  },
  {
    "id": "custom1005_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "树荫叉腰",
    "tip": "推荐上海街头、梧桐区场景，拍树荫叉腰照片",
    "description": "双脚靠近并微内扣，重心自然落在中线。双手叉腰但手肘放松，肩膀打开更显精神。镜头略低于胸口，保留树荫和街面纵深。适合梧桐树下的元气开场照。画面重点是叉腰姿态和树影街道，适合表现清爽校园风穿搭。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "树荫叉腰",
      "全身",
      "叉腰",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "树荫叉腰",
      "上海街头穿搭场景，拍树荫叉腰照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1006_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "墙边直立",
    "tip": "推荐上海街头、梧桐区场景，拍墙边直立照片",
    "description": "身体正对镜头，肩线放平，双臂自然下垂。脚尖微分开，裤脚垂直线要拍清楚。机位保持平视，让墙面和路面形成干净背景。适合安静墙边或弄堂口的日常穿搭记录。构图干净，能突出条纹上衣和阔腿裤的直线感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "墙边直立",
      "全身",
      "直立",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "墙边直立",
      "上海街头穿搭场景，拍墙边直立照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1007_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "街栏侧立",
    "tip": "推荐上海街头、梧桐区场景，拍街栏侧立照片",
    "description": "身体三分之二侧向，前脚轻点地更显俏皮。一手扶栏杆，另一手提包，动作要有停顿。红帽和红鞋可作为画面亮点，别被栏杆遮住。适合城市道路旁的活泼街拍。栏杆、马路和红色配饰一起形成很强的街头节奏。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "街栏侧立",
      "全身",
      "侧立",
      "扶栏",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "街栏侧立",
      "上海街头穿搭场景，拍街栏侧立照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1008_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "弄堂提袋",
    "tip": "推荐上海街头、梧桐区场景，拍弄堂提袋照片",
    "description": "身体微向镜头，提袋手臂自然下坠。双腿一前一后，膝盖放松形成日常步态。帽檐略压低，脸部仍需有光。适合背光弄堂里的软萌全身照。提袋和短裙让动作更生活化，适合轻松出片。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "弄堂提袋",
      "全身",
      "提袋",
      "全身照",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "弄堂提袋",
      "上海街头穿搭场景，拍弄堂提袋照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1009_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "栏杆轻扶",
    "tip": "推荐上海街头、梧桐区场景，拍栏杆轻扶照片",
    "description": "双手轻扶两侧栏杆，身体保持居中。裙摆和袜鞋要完整入镜，脚底贴近画面下缘。镜头平视，栏杆只作支撑线不要抢主体。适合咖啡店外或栏杆边的甜美站姿。背景简单时，扶栏动作能让画面更稳定。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "栏杆轻扶",
      "全身",
      "扶栏",
      "站姿",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "栏杆轻扶",
      "上海街头穿搭场景，拍栏杆轻扶照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1010_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "路牌微笑",
    "tip": "推荐上海街头、梧桐区场景，拍路牌微笑照片",
    "description": "站在路牌下方，身体正面但头微偏。双手自然放在裙侧，保持清爽学生感。机位稍远，留出龙江路牌和墙绘信息。适合路牌、墙绘、街区标识旁打卡。姿势简单，重点突出龙江路的地点记忆。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "路牌微笑",
      "全身",
      "微笑",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "路牌微笑",
      "上海街头穿搭场景，拍路牌微笑照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1011_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "街角前倾",
    "tip": "推荐上海街头、梧桐区场景，拍街角前倾照片",
    "description": "上身前倾，头部轻歪，笑容是动作重点。双手在身前拿包，形成低位视觉中心。肩膀顺着斜线放松，避免耸肩。适合街角近景半身到全身过渡。前倾动作亲和力强，适合作为一组图里的情绪照片。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "街角前倾",
      "全身",
      "前倾",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "街角前倾",
      "上海街头穿搭场景，拍街角前倾照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1012_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "门柱侧靠",
    "tip": "推荐上海街头、梧桐区场景，拍门柱侧靠照片",
    "description": "一手高扶门柱，另一手拎包自然下垂。身体斜靠但腰胯不要塌，形成长线条。脚步一前一后，裤裙比例要拍清楚。适合老门柱、铁门、门牌旁的复古街拍。身体斜线能让静态门墙更有动态感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "门柱侧靠",
      "全身",
      "侧靠",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "门柱侧靠",
      "上海街头穿搭场景，拍门柱侧靠照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1013_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "林荫捧脸",
    "tip": "推荐上海街头、梧桐区场景，拍林荫捧脸照片",
    "description": "双手捧脸，手肘向内收，制造甜感。身体略侧站，单肩包垂在身体外侧。在林荫路中拍摄，树冠只留氛围不抢人。适合林荫道路的甜感穿搭照。捧脸动作明确，适合拍成清新、轻松的生活记录。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "林荫捧脸",
      "全身",
      "捧脸",
      "单肩包",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "林荫捧脸",
      "上海街头穿搭场景，拍林荫捧脸照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1014_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "砖墙倚杆",
    "tip": "推荐上海街头、梧桐区场景，拍砖墙倚杆照片",
    "description": "背靠电杆，单手扶发，另一手拿饮品。一条腿交叉前伸，脚尖方向要明显。黑白条纹上衣适合用侧光突出轮廓。适合砖墙、铁栏、电杆等街头元素。倚靠和屈腿让画面更松弛，适合酷感穿搭。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "砖墙倚杆",
      "全身",
      "倚靠",
      "饮品",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "砖墙倚杆",
      "上海街头穿搭场景，拍砖墙倚杆照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1015_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "街铺举杯",
    "tip": "推荐上海街头、梧桐区场景，拍街铺举杯照片",
    "description": "一手举杯贴近头顶，另一手握伞柄。笑眼闭合时，头部角度要自然向光。外套敞开，裙腰线保持清楚。适合便利店、街铺或转角店面前拍摄。举杯动作有故事感，适合做城市漫步瞬间。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "街铺举杯",
      "全身",
      "举杯",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "街铺举杯",
      "上海街头穿搭场景，拍街铺举杯照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1016_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "红墙交腿",
    "tip": "推荐上海街头、梧桐区场景，拍红墙交腿照片",
    "description": "双手在身前轻握，双腿交叉靠近墙面。白裙要完整拍出，鞋尖贴地保持稳定。红砖弧墙是核心背景，人物站在转角光里。适合红砖墙和弧形建筑前的干净全身照。交腿站姿温柔，能拉出修长比例。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "红墙交腿",
      "全身",
      "交腿",
      "站姿",
      "全身照",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "红墙交腿",
      "上海街头穿搭场景，拍红墙交腿照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1017_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "老屋直视",
    "tip": "推荐上海街头、梧桐区场景，拍老屋直视照片",
    "description": "正面站立，双手自然拎包，肩膀保持对称。双腿靠拢，运动鞋落点要清晰。老屋墙面保留边界，突出上海街区质感。适合老洋房、社区小路等明亮户外。正面站姿稳妥，适合展示日常简约穿搭。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "老屋直视",
      "全身",
      "站姿",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "老屋直视",
      "上海街头穿搭场景，拍老屋直视照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1018_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "电杆屈膝",
    "tip": "推荐上海街头、梧桐区场景，拍电杆屈膝照片",
    "description": "背靠窄墙，单腿屈膝踩近立柱。一手扶帽檐，另一手插袋或垂放。镜头竖直拍，保留涂鸦和电杆的街头感。适合涂鸦墙、电杆、小巷交界处。屈膝倚靠更有街头态度，适合暗色系搭配。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "电杆屈膝",
      "全身",
      "倚靠",
      "屈膝",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "电杆屈膝",
      "上海街头穿搭场景，拍电杆屈膝照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1019_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "弄口扶杆",
    "tip": "推荐上海街头、梧桐区场景，拍弄口扶杆照片",
    "description": "一手扶杆，身体斜向街口形成延展。前腿轻抬，脚尖点地，包带自然下垂。弄堂建筑保留透视线，人物不要被柱子挡脸。适合弄堂入口或街角转弯处。扶杆与抬腿让人物像在行走，画面更有旅行感。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "弄口扶杆",
      "全身",
      "扶杆",
      "抬腿",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "弄口扶杆",
      "上海街头穿搭场景，拍弄口扶杆照片"
    ],
    "width": 1536,
    "height": 2048
  },
  {
    "id": "custom1020_r01_g01",
    "categoryId": "street-commute",
    "categoryName": "出门街拍",
    "name": "花店回眸",
    "tip": "推荐上海街头、梧桐区场景，拍花店回眸照片",
    "description": "身体侧倾回眸，后腿抬起形成俏皮曲线。一手拎饮料，一手背包带放松。花店门口色彩丰富，人物需站在光线均匀处。适合花店、门头招牌和绿植前。回眸抬腿很轻快，适合作为整组照片的收尾。",
    "badge": "全身",
    "gradient": "linear-gradient(150deg, #314b43 0%, #c9876f 100%)",
    "searchKeywords": [
      "上海街头穿搭",
      "花店回眸",
      "全身",
      "回眸",
      "抬腿",
      "背包",
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游"
    ],
    "sceneKeywords": [
      "上海街头",
      "梧桐区",
      "弄堂",
      "老洋房",
      "街边",
      "城市漫游",
      "花店回眸",
      "上海街头穿搭场景，拍花店回眸照片"
    ],
    "width": 1536,
    "height": 2048
  }
]

const importedPoseIds = importedPoseRecords.map((record) => record.id)
const importedPoseMetadataOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, {
  categoryId: record.categoryId,
  categoryName: record.categoryName,
  name: record.name,
  tip: record.tip,
  description: record.description,
  badge: record.badge,
  guideImage: `/static/pose_pairs/${record.id.split('_')[0]}/${record.id}_contour.png`,
  gradient: record.gradient
}]))
const importedPoseSearchKeywordOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, record.searchKeywords]))
const importedPoseSceneKeywordOverrides = Object.fromEntries(importedPoseRecords.map((record) => [record.id, record.sceneKeywords]))
const importedGuideImageSizes = Object.fromEntries(importedPoseRecords.map((record) => [
  `/static/pose_pairs/${record.id.split('_')[0]}/${record.id}_contour.png`,
  { width: record.width, height: record.height }
]))

module.exports = {
  importedPoseIds,
  importedPoseMetadataOverrides,
  importedPoseSearchKeywordOverrides,
  importedPoseSceneKeywordOverrides,
  importedGuideImageSizes
}
