const SCENE_TOPIC_DETAIL_KEY = 'sceneAdvisorPlanDetail'
const LANDMARK_TOPIC_IDS = new Set(["changsha-orange-island", "imported-changcheng1", "imported-gulou", "imported-heshun", "imported-mangshi", "imported-rehai", "imported-tengchong", "imported-tiananmen", "imported-tiandan", "imported-xihu", "imported-yinta", "shanghai-bund"])

const isLandmarkTopic = (topicId = '') => LANDMARK_TOPIC_IDS.has(topicId)

const makeScenePlan = (poseId, title, badge, reason, composition, camera, avoid) => ({
  poseId,
  title,
  badge,
  reason,
  composition,
  camera,
  avoid
})

const sceneTopics = [
  {
    id: "imported-huahai",
    title: "花海花田怎么拍",
    shortTitle: "花海花田",
    painPoint: "花海、花田和花园场景容易只拍成游客站照，人物和花丛关系不够明确。",
    promise: "用伸展、回眸、嗅花、递花和花园互动，让花海照片更有动作变化。",
    shareTitle: "花海花田拍照作业：花海、花园和花丛照着这些姿势拍",
    categoryId: "park-garden",
    coverPoseId: "pair-custom704-r01-g01",
    morePoseIds: [
      "pair-custom704-r01-g01",
      "pair-custom691-r01-g01",
      "pair-custom692-r01-g01",
      "pair-custom693-r01-g01",
      "pair-custom694-r01-g01",
      "pair-custom695-r01-g01",
      "pair-custom696-r01-g01",
      "pair-custom697-r01-g01",
      "pair-custom698-r01-g01",
      "pair-custom699-r01-g01",
      "pair-custom705-r01-g01",
      "pair-custom706-r01-g01",
      "pair-custom707-r01-g01",
      "pair-custom708-r01-g01",
      "pair-custom709-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom704-r01-g01",
        "花前轻嗅",
        "半身",
        "把花束抬到鼻尖附近，肩膀自然下沉，视线越过花瓣看向镜头。",
        "人物上半身靠近花丛或小径边，让花束放在脸侧形成清新浪漫焦点。",
        "手机平视半身拍，保留花束、脸部和肩颈线条，不要压得太近。",
        "不要让花完全挡住脸，也不要把手肘撑得太开。"
      ),
      makeScenePlan(
        "pair-custom691-r01-g01",
        "拥抱整片花海",
        "背影",
        "背对镜头张开双臂，让身体动作和花海范围一起打开。",
        "人物放在花丛中间或略偏一侧，手臂展开，保留大片花海和天空。",
        "手机平视或略低竖拍，把花海延展方向和人物背影一起拍完整。",
        "不要裁掉手臂，也不要让人物站得太靠边。"
      ),
      makeScenePlan(
        "pair-custom692-r01-g01",
        "花间回眸",
        "半身",
        "站在花丛旁侧身回头，既能露脸又能交代花海环境。",
        "人物上半身靠近花丛，肩膀侧开，花朵作为前景或侧边背景。",
        "手机平视半身拍，留出花丛层次，不要只拍成大头照。",
        "不要让花遮住整张脸，回头幅度也不要太僵。"
      )
    ]
  },
  {
    id: "old-town-street",
    title: "古镇街巷怎么拍",
    shortTitle: "古镇街巷",
    painPoint: "古镇老街、石板巷和木门庭院容易只拍成站立打卡照，人物和街巷关系不够明确。",
    promise: "用石巷奔跑、回眸撩发、茶舍探身和门框倚靠，把古镇里的行走感和故事感拍出来。",
    shareTitle: "古镇街巷拍照作业：老街小巷照着这些姿势拍",
    categoryId: "old-town-street",
    coverPoseId: "pair-custom340-r01-g01",
    morePoseIds: [
      "pair-custom340-r01-g01",
      "pair-custom337-r01-g01",
      "pair-custom341-r01-g01",
      "pair-custom336-r01-g01",
      "pair-custom338-r01-g01",
      "pair-custom339-r01-g01",
      "pair-custom342-r01-g01",
      "pair-custom343-r01-g01",
      "pair-custom344-r01-g01",
      "pair-custom345-r01-g01",
      "pair-custom346-r01-g01",
      "pair-custom347-r01-g01",
      "pair-custom348-r01-g01",
      "pair-custom349-r01-g01",
      "pair-custom350-r01-g01",
      "pair-custom351-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom340-r01-g01",
        "石巷提裙奔跑",
        "行走",
        "沿石板巷向镜头轻跑，双手轻提裙摆，保留脚步展开的动态。",
        "人物放在巷道中轴或略偏一侧，让石板路和墙面线条带出纵深。",
        "手机略低竖拍连拍，等裙摆和脚步同时打开时按下快门。",
        "不要把脚裁掉，也不要让背景行人压到人物轮廓。"
      ),
      makeScenePlan(
        "pair-custom337-r01-g01",
        "回眸轻撩发",
        "全身",
        "身体侧向古巷或木门，肩膀先转开，再回头看镜头并轻触头发。",
        "让木门、转角或巷口占一侧背景，人物站在另一侧留出回眸方向。",
        "手机平视拍全身，抓侧身到回头之间的瞬间，动作会更自然。",
        "不要扭腰过度，手肘也不要挡住脸。"
      ),
      makeScenePlan(
        "pair-custom341-r01-g01",
        "茶舍探身",
        "半身",
        "在茶舍招牌或临街窗口旁微微探身，一手扶包，表情像正在发现镜头。",
        "人物靠近门窗边缘，让招牌、木窗和街景形成前后层次。",
        "手机平视或略高拍半身，保留手部、包和茶舍环境信息。",
        "不要探身太用力，也不要让招牌遮住头部。"
      )
    ]
  },
  {
    id: "imported-heshun",
    title: "和顺古镇怎么拍",
    shortTitle: "和顺古镇",
    painPoint: "和顺古镇水边、庭院和石桥点位很多，动作容易拆散成多个入口不好找。",
    promise: "用水边戏水、庭院坐姿、背影望桥和石阶扶额等动作，快速拍出有古镇关系的照片。",
    shareTitle: "和顺古镇拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom384-r01-g01",
    morePoseIds: [
      "pair-custom352-r01-g01",
      "pair-custom353-r01-g01",
      "pair-custom354-r01-g01",
      "pair-custom355-r01-g01",
      "pair-custom356-r01-g01",
      "pair-custom357-r01-g01",
      "pair-custom358-r01-g01",
      "pair-custom359-r01-g01",
      "pair-custom360-r01-g01",
      "pair-custom361-r01-g01",
      "pair-custom362-r01-g01",
      "pair-custom363-r01-g01",
      "pair-custom364-r01-g01",
      "pair-custom365-r01-g01",
      "pair-custom366-r01-g01",
      "pair-custom367-r01-g01",
      "pair-custom368-r01-g01",
      "pair-custom369-r01-g01",
      "pair-custom370-r01-g01",
      "pair-custom371-r01-g01",
      "pair-custom372-r01-g01",
      "pair-custom373-r01-g01",
      "pair-custom374-r01-g01",
      "pair-custom375-r01-g01",
      "pair-custom376-r01-g01",
      "pair-custom377-r01-g01",
      "pair-custom378-r01-g01",
      "pair-custom379-r01-g01",
      "pair-custom380-r01-g01",
      "pair-custom381-r01-g01",
      "pair-custom382-r01-g01",
      "pair-custom383-r01-g01",
      "pair-custom384-r01-g01",
      "pair-custom385-r01-g01",
      "pair-custom386-r01-g01",
      "pair-custom387-r01-g01",
      "pair-custom388-r01-g01",
      "pair-custom389-r01-g01",
      "pair-custom390-r01-g01",
      "pair-custom391-r01-g01",
      "pair-custom392-r01-g01",
    ],
    plans: [
      makeScenePlan(
        "pair-custom384-r01-g01",
        "背影望桥",
        "背影",
        "人物背对镜头站在水边，身体微向石桥方向打开，别把肩膀绷直",
        "左手自然垂在身侧，右手靠近裙摆，动作要轻不要抢桥景",
        "适合古镇水巷、石桥和花丛同框的安静背影照。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom385-r01-g01",
        "临水坐望",
        "坐姿",
        "坐在石沿边缘，双腿并向一侧垂落，身体朝水面微微转开",
        "一手搭在身旁借力，另一手轻扶头发，形成松弛的侧身线",
        "适合桥边、溪畔、花木包围的小景位，营造午后发呆感。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom386-r01-g01",
        "石阶扶额",
        "全身",
        "站在石阶旁身体前倾，重心压向前脚，另一脚自然跟上",
        "右手抬到额前像遮阳，左臂顺着身体下垂，避免两手都僵硬",
        "适合石阶、门楼、古建筑入口等有高度差的位置。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-hongqiang",
    title: "红墙古建怎么拍",
    shortTitle: "红墙古建",
    painPoint: "红墙古建现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用抬头看天空、双手合十和走路抓拍这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "红墙古建拍照作业：照着这些姿势拍更自然",
    categoryId: "art-city",
    coverPoseId: "pair-custom393-r01-g01",
    morePoseIds: [
      "pair-custom393-r01-g01",
      "pair-custom394-r01-g01",
      "pair-custom395-r01-g01",
      "pair-custom396-r01-g01",
      "pair-custom397-r01-g01",
      "pair-custom398-r01-g01",
      "pair-custom399-r01-g01",
      "pair-custom400-r01-g01",
      "pair-custom401-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom393-r01-g01",
        "抬头看天空",
        "全身",
        "身体轻靠红墙侧站，头部顺着墙面方向向上看，拉长脖颈线条",
        "双手收进口袋或自然贴近身体，减少手部杂乱感",
        "适合红墙大面积留白构图，突出侧脸和脖颈线条",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom394-r01-g01",
        "双手合十",
        "全身",
        "双手合十放在胸前或下巴附近，手指并拢，动作要轻不要用力",
        "身体正面略微侧转，避免合十动作显得像证件照",
        "适合寺庙、红墙、古建旁的温柔祈愿感照片",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom395-r01-g01",
        "走路抓拍",
        "全身",
        "先沿红墙平行方向慢走，摄影师连拍抓取脚步交错瞬间",
        "前脚落地、后脚抬起时按快门，腿部线条最自然",
        "适合红墙边的街拍式动态照片，画面更自然不摆拍",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-jietou",
    title: "城市街头怎么拍",
    shortTitle: "城市街头",
    painPoint: "城市街头现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用行走扶镜、彩线回眸和斑马迈步这几种动作，快速拍出更有街拍动感的照片。",
    shareTitle: "城市街头拍照作业：照着这些姿势拍更自然",
    categoryId: "street-commute",
    coverPoseId: "pair-custom421-r01-g01",
    morePoseIds: [
      "pair-custom421-r01-g01",
      "pair-custom420-r01-g01",
      "pair-custom422-r01-g01",
      "pair-custom402-r01-g01",
      "pair-custom403-r01-g01",
      "pair-custom404-r01-g01",
      "pair-custom405-r01-g01",
      "pair-custom406-r01-g01",
      "pair-custom407-r01-g01",
      "pair-custom410-r01-g01",
      "pair-custom411-r01-g01",
      "pair-custom412-r01-g01",
      "pair-custom413-r01-g01",
      "pair-custom414-r01-g01",
      "pair-custom415-r01-g01",
      "pair-custom416-r01-g01",
      "pair-custom417-r01-g01",
      "pair-custom418-r01-g01",
      "pair-custom419-r01-g01",
      "pair-custom423-r01-g01",
      "pair-custom424-r01-g01",
      "pair-custom425-r01-g01",
      "pair-custom426-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom421-r01-g01",
        "彩线回眸",
        "背影",
        "背对镜头站在彩色斑马线中央，上半身向左肩方向大幅拧转",
        "双脚分开站稳，手机自然握在身前，视线越过肩膀看向镜头",
        "适合彩虹斑马线、涂鸦路口和地面有高饱和色块的十字路口。",
        "人物站在画面中轴，地面线条要完整收进前景。"
      ),
      makeScenePlan(
        "pair-custom420-r01-g01",
        "行走扶镜",
        "全身",
        "身体侧对镜头保持行走姿态，头部向镜头方向轻转，手指轻扶墨镜边框",
        "前脚脚跟先落地，后脚脚尖点地，保留跨步瞬间的腿部线条",
        "适合红砖墙住宅街、停有轿车的老式胡同或社区门口。",
        "机位略低，完整保留脚步和街道纵深。"
      ),
      makeScenePlan(
        "pair-custom422-r01-g01",
        "斑马迈步",
        "全身",
        "身体正面朝镜头，重心略向后倾，定格正在过马路的迈步瞬间",
        "一手自然下垂，一手抬到胸前随步伐摆动，表情放松看镜头",
        "适合斑马线、老欧式建筑和可见地标塔的都市大街口。",
        "低机位正面拍摄，让斑马线从脚下延伸到远处。"
      )
    ]
  },
  {
    id: "imported-kafei",
    title: "咖啡馆探店怎么拍",
    shortTitle: "咖啡馆探店",
    painPoint: "咖啡馆探店现场动作容易重复，坐下后手和道具不知道怎么放。",
    promise: "用托腮品饮、举杯做鬼脸、双手捧盘和窗边侧身等动作，快速拍出生活感照片。",
    shareTitle: "咖啡馆探店拍照作业：照着这些姿势拍更自然",
    categoryId: "props-action",
    coverPoseId: "pair-custom666-r01-g01",
    morePoseIds: [
      "pair-custom666-r01-g01",
      "pair-custom667-r01-g01",
      "pair-custom668-r01-g01",
      "pair-custom669-r01-g01",
      "pair-custom670-r01-g01",
      "pair-custom671-r01-g01",
      "pair-custom672-r01-g01",
      "pair-custom673-r01-g01",
      "pair-custom674-r01-g01",
      "pair-custom675-r01-g01",
      "pair-custom676-r01-g01",
      "pair-custom677-r01-g01",
      "pair-custom678-r01-g01",
      "pair-custom679-r01-g01",
      "pair-custom680-r01-g01",
      "pair-custom681-r01-g01",
      "pair-custom427-r01-g01",
      "pair-custom428-r01-g01",
      "pair-custom429-r01-g01",
      "pair-custom430-r01-g01",
      "pair-custom431-r01-g01",
      "pair-custom432-r01-g01",
      "pair-custom433-r01-g01",
      "pair-custom434-r01-g01",
      "pair-custom435-r01-g01",
      "pair-custom436-r01-g01",
      "pair-custom437-r01-g01",
      "pair-custom438-r01-g01",
      "pair-custom439-r01-g01",
      "pair-custom440-r01-g01",
      "pair-custom441-r01-g01",
      "pair-custom442-r01-g01",
      "pair-custom84-r01-g01",
      "pair-custom51-r01-g01",
      "pair-custom76-r01-g01",
      "pair-custom78-r01-g01",
      "pair-custom64-r01-g01",
      "pair-custom75-r01-g01",
      "pair-custom79-r01-g01",
      "pair-custom88-r01-g01",
      "pair-custom80-r01-g01",
      "pair-custom81-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom666-r01-g01",
        "托腮品饮",
        "半身",
        "身体微前倾，双肘自然撑在桌面上，动作安静但不僵硬。",
        "一只手托腮，另一只手轻扶饮品杯，让杯子和桌面都进入画面。",
        "手机平视或略高，视线看向镜头或微微下垂，营造慵懒感。",
        "不要裁掉手部、杯子和桌面道具。"
      ),
      makeScenePlan(
        "pair-custom427-r01-g01",
        "举杯做鬼脸",
        "半身",
        "举杯动作能解决手空问题，表情夸张一点更像探店抓拍。",
        "右手握住玻璃杯举到嘴角旁，杯身微微前倾对准镜头。",
        "手机平视拍半身，保留杯子、桌面和身后的咖啡馆环境。",
        "不要裁掉杯子，也不要让杯子挡住整张脸。"
      ),
      makeScenePlan(
        "pair-custom668-r01-g01",
        "双手捧盘",
        "全身",
        "把甜品盘作为道具端到胸前，适合咖啡馆门口或桌边展示氛围。",
        "双手自然捧起甜品盘，身体微微前倾，视线看向镜头。",
        "竖构图拍全身或七分身，露出肩线和咖啡馆背景。",
        "不要裁掉盘子、手部和脚部姿态。"
      )
    ]
  },
  {
    id: "imported-mangshi",
    title: "芒市大金塔怎么拍",
    shortTitle: "芒市大金塔",
    painPoint: "芒市大金塔现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用金墙仰望、塔前静立和佛前侧坐这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "芒市大金塔拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom443-r01-g01",
    morePoseIds: [
      "pair-custom443-r01-g01",
      "pair-custom444-r01-g01",
      "pair-custom445-r01-g01",
      "pair-custom446-r01-g01",
      "pair-custom447-r01-g01",
      "pair-custom448-r01-g01",
      "pair-custom449-r01-g01",
      "pair-custom450-r01-g01",
      "pair-custom451-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom443-r01-g01",
        "金墙仰望",
        "全身",
        "身体贴近金色护墙侧站，头向塔檐方向抬起，拉长颈部线条",
        "双手轻扶腰侧或裙边，手臂贴近身体，避免遮住红色上衣",
        "适合金塔护栏、浮雕墙和阳光很足的金色建筑边。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom444-r01-g01",
        "塔前静立",
        "全身",
        "站在台阶正中偏下位置，身体侧向镜头，双手自然交叠在身前",
        "脚尖并拢或微错开，让长裙保持直线，不抢后方大金塔",
        "适合大金塔正门、长台阶和对称建筑前的到此一游照。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom445-r01-g01",
        "佛前侧坐",
        "坐姿",
        "侧坐在金色台沿前，身体朝镜头转半身，双手向后轻扶支撑",
        "一条腿自然收起，另一条顺着台沿延伸，注意裙摆铺开层次",
        "适合佛像、金色栏墙和低台阶组合的近景。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-rehai",
    title: "腾冲热海司莫拉怎么拍",
    shortTitle: "腾冲热海司莫拉",
    painPoint: "腾冲热海司莫拉现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用桥上举串拍零食、热海墙前展臂和图腾柱前踢腿这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "腾冲热海司莫拉拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom452-r01-g01",
    morePoseIds: [
      "pair-custom452-r01-g01",
      "pair-custom453-r01-g01",
      "pair-custom454-r01-g01",
      "pair-custom455-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom452-r01-g01",
        "桥上举串拍零食",
        "全身",
        "左手高高举起提着草绳串食物，手臂完全伸直让食物高于头顶",
        "右手五指自然张开微微离开身体，保持站姿不呆板",
        "地热景区木桥或栈道处手持当地特色食物打卡拍摄",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom453-r01-g01",
        "热海墙前展臂",
        "全身",
        "双臂向身体两侧完全平伸张开，手掌翻转朝上呈拥抱姿态",
        "左腿直立撑重心，右腿向左前方跨出一步脚尖点地形成交叉步",
        "景区标志性文字墙或石刻前展开身体的打卡定番姿势",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom454-r01-g01",
        "图腾柱前踢腿",
        "全身",
        "右腿作支撑腿站稳，左腿向侧后方踢起脚尖绷直呈动态弧线",
        "左手自然举着奶茶杯保持在胸前高度，右手拎包垂于身侧",
        "少数民族文化陈列馆或木雕建筑前的活泼动态打卡",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-senlin",
    title: "森林树林怎么拍",
    shortTitle: "森林树林",
    painPoint: "森林、果园和花树枝头都容易背景杂乱，站着拍不容易突出人物和枝叶关系。",
    promise: "用花间凝望、摘果互动、枝头仰望和倒木捧花，把林间照片拍得更自然。",
    shareTitle: "森林树林拍照作业：枝叶、花树、果园和树桩都能拍",
    categoryId: "travel-back",
    coverPoseId: "pair-custom456-r01-g01",
    morePoseIds: [
      "pair-custom220-r01-g01",
      "pair-custom221-r01-g01",
      "pair-custom222-r01-g01",
      "pair-custom223-r01-g01",
      "pair-custom224-r01-g01",
      "pair-custom225-r01-g01",
      "pair-custom252-r01-g01",
      "pair-custom253-r01-g01",
      "pair-custom254-r01-g01",
      "pair-custom255-r01-g01",
      "pair-custom256-r01-g01",
      "pair-custom257-r01-g01",
      "pair-custom258-r01-g01",
      "pair-custom259-r01-g01",
      "pair-custom260-r01-g01",
      "pair-custom261-r01-g01",
      "pair-custom262-r01-g01",
      "pair-custom263-r01-g01",
      "pair-custom264-r01-g01",
      "pair-custom456-r01-g01",
      "pair-custom457-r01-g01",
      "pair-custom458-r01-g01",
      "pair-custom459-r01-g01",
      "pair-custom460-r01-g01",
      "pair-custom461-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom456-r01-g01",
        "花间凝望",
        "蹲姿",
        "侧身蹲坐在雏菊花丛中，身体朝向画面左侧形成侧颜轮廓",
        "双手十指交叉合拢抬至下巴正前方，指尖轻触唇下营造沉思感",
        "适合林间雏菊花丛或低矮野花地带，利用花朵做前景虚化框住半身",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom457-r01-g01",
        "倒木捧花",
        "坐姿",
        "坐在横倒的粗树干上，臀部靠近树干中段，双脚自然垂下踩地",
        "双手在腿上捧住白色百合花束，花朵朝向镜头方向",
        "适合森林中横倒的树干或粗木桩，利用原木纹理做天然坐椅",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom458-r01-g01",
        "举果俏皮",
        "坐姿",
        "盘腿坐在林间草地上，裙摆铺散在地面形成圆形轮廓",
        "右手举起半切番石榴贴近右脸颊，手臂弯曲呈直角",
        "适合林间空地或草坪，背景选择阳光穿透树冠的逆光位置",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-tengchong",
    title: "腾冲火山热气球怎么拍",
    shortTitle: "腾冲火山热气球",
    painPoint: "腾冲火山热气球现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用抱膝望镜、扶栏回眸和夹花托腮这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "腾冲火山热气球拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom471-r01-g01",
    morePoseIds: [
      "pair-custom471-r01-g01",
      "pair-custom472-r01-g01",
      "pair-custom473-r01-g01",
      "pair-custom474-r01-g01",
      "pair-custom475-r01-g01",
      "pair-custom476-r01-g01",
      "pair-custom477-r01-g01",
      "pair-custom478-r01-g01",
      "pair-custom479-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom471-r01-g01",
        "抱膝望镜",
        "坐姿",
        "整个身体正侧对镜头坐在石墙上，双腿并膝屈起脚踩墙面",
        "双臂环抱在屈起的双膝前方，手掌自然叠放贴在小腿上",
        "适合正对腾冲热海气球群的观景石墙一侧，让背景群山和多只彩色气球平铺在画面左半边",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom472-r01-g01",
        "扶栏回眸",
        "背影",
        "整个身体背对镜头站立，左手扶在木栏杆立柱上做支点",
        "重心压在后腿上前腿脚尖点地，臀线自然翘出",
        "适合观景台带木栏杆的角落，让斜切的栏杆做前景引导线",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom473-r01-g01",
        "夹花托腮",
        "坐姿",
        "盘腿坐在石墙上正面朝镜头，双腿盘成小三角",
        "右手举到右脸颊做托腮，虎口夹住一朵小雏菊贴在颧骨上",
        "适合石墙加低机位仰拍，让人物略微俯视镜头看起来腿更长",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-tiananmen",
    title: "天安门怎么拍",
    shortTitle: "天安门",
    painPoint: "天安门现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用手持红旗微微侧身、微微歪头双手环抱和举起红旗眼看红旗这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "天安门拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom480-r01-g01",
    morePoseIds: [
      "pair-custom480-r01-g01",
      "pair-custom481-r01-g01",
      "pair-custom482-r01-g01",
      "pair-custom483-r01-g01",
      "pair-custom484-r01-g01",
      "pair-custom485-r01-g01",
      "pair-custom486-r01-g01",
      "pair-custom487-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom480-r01-g01",
        "手持红旗微微侧身",
        "半身",
        "身体斜向站立，肩膀不要完全正对镜头，红旗放在身体外侧形成延展线",
        "拿旗的手臂自然弯曲，旗面略高于腰线，避免挡住脸和上半身",
        "适合天安门广场红旗打卡，突出纪念感和轻盈侧身线条",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom481-r01-g01",
        "微微歪头双手环抱",
        "全身",
        "双臂环抱时手肘不要夹太紧，留出肩颈和手臂轮廓",
        "头部轻轻向一侧倾斜，下巴微收，避免脸部仰得过高",
        "适合红墙或广场前的安静站姿照，表达乖巧、端正的纪念氛围",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom482-r01-g01",
        "举起红旗眼看红旗",
        "全身",
        "举旗手臂向斜上方伸展，手腕放松，让旗面自然展开",
        "脸部和视线跟随红旗方向，不必看镜头，营造互动感",
        "适合表现和红旗互动的动态画面，画面更有仪式感",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-tiandan",
    title: "天坛怎么拍",
    shortTitle: "天坛",
    painPoint: "天坛现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用侧头通话、侧身插兜和正面端立这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "天坛拍照作业：照着这些姿势拍更自然",
    categoryId: "art-city",
    coverPoseId: "pair-custom488-r01-g01",
    morePoseIds: [
      "pair-custom488-r01-g01",
      "pair-custom489-r01-g01",
      "pair-custom490-r01-g01",
      "pair-custom491-r01-g01",
      "pair-custom492-r01-g01",
      "pair-custom493-r01-g01",
      "pair-custom494-r01-g01",
      "pair-custom495-r01-g01",
      "pair-custom496-r01-g01",
      "pair-custom497-r01-g01",
      "pair-custom498-r01-g01",
      "pair-custom499-r01-g01",
      "pair-custom500-r01-g01",
      "pair-custom501-r01-g01",
      "pair-custom502-r01-g01",
      "pair-custom503-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom488-r01-g01",
        "侧头通话",
        "全身",
        "一手举到耳边做接电话动作，身体正面站直，头向手侧轻靠",
        "另一手自然下垂，肩膀放松，避免黑裙与身体贴成一块",
        "适合祈年殿正面广场、人少且背景对称的位置。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom489-r01-g01",
        "侧身插兜",
        "全身",
        "身体侧向镜头站立，一手插裤袋，一手垂在身前形成简洁线条",
        "头部回看镜头，肩膀不要耸起，保持利落的侧脸轮廓",
        "适合简洁穿搭与古建筑同框的街拍式照片。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom490-r01-g01",
        "正面端立",
        "全身",
        "正对镜头站在建筑中轴线上，双手自然落在身体两侧",
        "两脚微分开站稳，肩膀打开，避免身体被大建筑压得没气场",
        "适合祈年殿、对称栏杆和需要正式纪念照的场景。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-xihu",
    title: "杭州西湖怎么拍",
    shortTitle: "杭州西湖",
    painPoint: "杭州西湖现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用背影举机拍湖、长椅张臂欢呼和侧身微倾浅笑这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "杭州西湖拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom504-r01-g01",
    morePoseIds: [
      "pair-custom504-r01-g01",
      "pair-custom505-r01-g01",
      "pair-custom506-r01-g01",
      "pair-custom507-r01-g01",
      "pair-custom508-r01-g01",
      "pair-custom509-r01-g01",
      "pair-custom510-r01-g01",
      "pair-custom511-r01-g01",
      "pair-custom512-r01-g01",
      "pair-custom513-r01-g01",
      "pair-custom514-r01-g01",
      "pair-custom515-r01-g01",
      "pair-custom516-r01-g01",
      "pair-custom517-r01-g01",
      "pair-custom518-r01-g01",
      "pair-custom519-r01-g01",
      "pair-custom520-r01-g01",
      "pair-custom521-r01-g01",
      "pair-custom522-r01-g01",
      "pair-custom523-r01-g01",
      "pair-custom524-r01-g01",
      "pair-custom525-r01-g01",
      "pair-custom526-r01-g01",
      "pair-custom527-r01-g01",
      "pair-custom528-r01-g01",
      "pair-custom529-r01-g01",
      "pair-custom530-r01-g01",
      "pair-custom531-r01-g01",
      "pair-custom532-r01-g01",
      "pair-custom533-r01-g01",
      "pair-custom534-r01-g01",
      "pair-custom535-r01-g01",
      "pair-custom536-r01-g01",
      "pair-custom537-r01-g01",
      "pair-custom538-r01-g01",
      "pair-custom539-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom504-r01-g01",
        "背影举机拍湖",
        "背影",
        "取背影全身，人物坐在木栈道边缘（可垫脚跟或半蹲状），画面中人物只露后脑与外套背面",
        "双手一起把手机横向举到耳侧高度、镜头对准远方湖心，肘部微向外张开自然张开",
        "适合冬春交界枯枝残柳的湖边木栈道，天空色调清冷时最出氛围",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom505-r01-g01",
        "长椅张臂欢呼",
        "背影",
        "背对镜头坐在临湖木长椅上，肩背贴椅背保持挺直",
        "双臂同时高举、向左右斜上方45度打开成大V字，掌心自然朝前",
        "适合春季垂柳新绿的湖边长椅，前景抓一束下垂柳条压顶",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom506-r01-g01",
        "侧身微倾浅笑",
        "半身",
        "身体略侧站在栈道靠水一侧，上半身微微前倾10–15度指向镜头",
        "肩线放松下沉，一只肩比另一只稍低，形成非对称柔软线条",
        "适合日落金光时的湖边栈道，让侧光打在半张脸和衬衫褶皱上",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-xiyang",
    title: "海边夕阳怎么拍",
    shortTitle: "海边夕阳",
    painPoint: "海边夕阳现场动作容易重复，站着拍不容易突出场景特点。",
    promise: "用举V迎光、背手静立和举机拍日这几种动作，快速拍出有场景关系的照片。",
    shareTitle: "海边夕阳拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom540-r01-g01",
    morePoseIds: [
      "pair-custom540-r01-g01",
      "pair-custom541-r01-g01",
      "pair-custom542-r01-g01",
      "pair-custom543-r01-g01",
      "pair-custom544-r01-g01",
      "pair-custom545-r01-g01",
      "pair-custom546-r01-g01",
      "pair-custom547-r01-g01",
      "pair-custom548-r01-g01",
      "pair-custom549-r01-g01",
      "pair-custom550-r01-g01",
      "pair-custom551-r01-g01",
      "pair-custom552-r01-g01",
      "pair-custom553-r01-g01",
      "pair-custom554-r01-g01",
      "pair-custom555-r01-g01",
      "pair-custom556-r01-g01",
      "pair-custom557-r01-g01",
      "pair-custom558-r01-g01",
      "pair-custom559-r01-g01",
      "pair-custom560-r01-g01",
      "pair-custom561-r01-g01",
      "pair-custom562-r01-g01",
      "pair-custom563-r01-g01",
      "pair-custom564-r01-g01",
      "pair-custom565-r01-g01",
      "pair-custom566-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom540-r01-g01",
        "举V迎光",
        "背影",
        "背对镜头站立，重心稳落双脚，双腿自然并拢",
        "右臂由肩部向斜上方伸直，手指比出V手势指向天空右上方",
        "海边落日剪影氛围留念，凸显轻盈少女感",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom541-r01-g01",
        "背手静立",
        "背影",
        "背对镜头，双脚微微没入水中并拢站立",
        "双手在腰后自然交握，肘部微弯让肩背线条舒展",
        "适合长吊带裙/连衣裙的静谧感海边独照",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom542-r01-g01",
        "举机拍日",
        "全身",
        "身体侧对镜头，重心落在后脚，前脚微点沙面",
        "双手横向平举手机于面前，手肘架起腋下留空",
        "假装拍夕阳的抓拍生活感照片",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: "imported-yinta",
    title: "芒市银塔怎么拍",
    shortTitle: "芒市银塔",
    painPoint: "芒市银塔水边、白塔广场和拱门点位分散，分成多个入口不方便连续查看。",
    promise: "用镜畔轻坐、回眸倚塔和侧坐凝光等水镜动作，快速拍出银塔镜面氛围照片。",
    shareTitle: "芒市银塔拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom710-r01-g01",
    morePoseIds: [
      "pair-custom710-r01-g01",
      "pair-custom711-r01-g01",
      "pair-custom712-r01-g01",
      "pair-custom713-r01-g01",
      "pair-custom714-r01-g01",
      "pair-custom715-r01-g01",
      "pair-custom716-r01-g01",
      "pair-custom717-r01-g01",
      "pair-custom718-r01-g01",
      "pair-custom611-r01-g01",
      "pair-custom462-r01-g01",
      "pair-custom463-r01-g01",
      "pair-custom464-r01-g01",
      "pair-custom465-r01-g01",
      "pair-custom466-r01-g01",
      "pair-custom467-r01-g01",
      "pair-custom468-r01-g01",
      "pair-custom469-r01-g01",
      "pair-custom470-r01-g01",
      "pair-custom567-r01-g01",
      "pair-custom568-r01-g01",
      "pair-custom569-r01-g01",
      "pair-custom570-r01-g01",
      "pair-custom571-r01-g01",
      "pair-custom572-r01-g01",
      "pair-custom573-r01-g01",
      "pair-custom574-r01-g01",
      "pair-custom575-r01-g01",
      "pair-custom576-r01-g01",
      "pair-custom577-r01-g01",
      "pair-custom578-r01-g01",
      "pair-custom579-r01-g01",
      "pair-custom580-r01-g01",
      "pair-custom581-r01-g01",
      "pair-custom582-r01-g01",
      "pair-custom583-r01-g01",
      "pair-custom584-r01-g01",
      "pair-custom585-r01-g01",
      "pair-custom586-r01-g01",
      "pair-custom587-r01-g01",
      "pair-custom588-r01-g01",
      "pair-custom589-r01-g01",
      "pair-custom590-r01-g01",
      "pair-custom591-r01-g01",
      "pair-custom592-r01-g01",
      "pair-custom593-r01-g01",
      "pair-custom594-r01-g01",
      "pair-custom595-r01-g01",
      "pair-custom596-r01-g01",
      "pair-custom597-r01-g01",
      "pair-custom598-r01-g01",
      "pair-custom599-r01-g01",
      "pair-custom600-r01-g01",
      "pair-custom601-r01-g01",
      "pair-custom602-r01-g01",
      "pair-custom603-r01-g01",
      "pair-custom604-r01-g01",
      "pair-custom605-r01-g01",
      "pair-custom606-r01-g01",
      "pair-custom607-r01-g01",
      "pair-custom608-r01-g01",
      "pair-custom609-r01-g01",
      "pair-custom610-r01-g01",
      "pair-custom612-r01-g01",
      "pair-custom613-r01-g01",
      "pair-custom614-r01-g01",
      "pair-custom615-r01-g01",
      "pair-custom616-r01-g01",
      "pair-custom617-r01-g01",
      "pair-custom618-r01-g01",
      "pair-custom619-r01-g01",
      "pair-custom620-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom710-r01-g01",
        "镜畔轻坐",
        "坐姿",
        "低机位贴近镜面水面，人物屈膝侧坐，后手撑地稳定身体",
        "肩线放松，脸微微转向镜头，让银白服饰和白塔色调呼应",
        "适合银塔近景、水镜倒影和蓝天强对比画面。",
        "机位尽量贴近水面，保留人物、银塔和倒影的三层关系。"
      ),
      makeScenePlan(
        "pair-custom711-r01-g01",
        "回眸倚塔",
        "坐姿",
        "人物放在画面右侧，双腿交叠坐稳，一只手撑地形成支点",
        "下颌微抬，视线越过镜头，让塔身细节和水面层次一起入画",
        "适合银塔塔身细节丰富的中近景和午后侧光。",
        "构图保留塔身边线，不要让人物压住建筑主体。"
      ),
      makeScenePlan(
        "pair-custom712-r01-g01",
        "侧坐凝光",
        "坐姿",
        "侧身落座，背部挺直，前腿屈起，后腿自然收拢",
        "用塔身中轴稳定构图，手部自然落在膝前，整体动作安静克制",
        "适合水镜、白塔和银白服饰统一的东方写真画面。",
        "画面保持干净留白，避免裁掉裙摆和水面倒影。"
      )
    ]
  },
  {
    id: "imported-yinxing1",
    title: "银杏秋叶公园怎么拍",
    shortTitle: "银杏秋叶",
    painPoint: "银杏和秋叶公园现场动作容易重复，站着拍不容易突出金黄落叶和林间纵深。",
    promise: "用叶海捧花、围巾回眸、林下侧立和手持秋叶等动作，快速拍出秋日氛围照片。",
    shareTitle: "银杏秋叶公园拍照作业：照着这些姿势拍更自然",
    categoryId: "travel-back",
    coverPoseId: "pair-custom621-r01-g01",
    morePoseIds: [
      "pair-custom621-r01-g01",
      "pair-custom622-r01-g01",
      "pair-custom623-r01-g01",
      "pair-custom624-r01-g01",
      "pair-custom625-r01-g01",
      "pair-custom626-r01-g01",
      "pair-custom627-r01-g01",
      "pair-custom628-r01-g01",
      "pair-custom629-r01-g01",
      "pair-custom630-r01-g01",
      "pair-custom631-r01-g01",
      "pair-custom632-r01-g01",
      "pair-custom633-r01-g01",
      "pair-custom634-r01-g01",
      "pair-custom635-r01-g01",
      "pair-custom636-r01-g01",
      "pair-custom637-r01-g01",
      "pair-custom638-r01-g01",
      "pair-custom639-r01-g01",
      "pair-custom640-r01-g01",
      "pair-custom641-r01-g01",
      "pair-custom642-r01-g01",
      "pair-custom643-r01-g01",
      "pair-custom644-r01-g01",
      "pair-custom645-r01-g01",
      "pair-custom646-r01-g01",
      "pair-custom647-r01-g01",
      "pair-custom648-r01-g01",
      "pair-custom649-r01-g01",
      "pair-custom650-r01-g01",
      "pair-custom651-r01-g01",
      "pair-custom652-r01-g01",
      "pair-custom653-r01-g01",
      "pair-custom654-r01-g01",
      "pair-custom655-r01-g01",
      "pair-custom656-r01-g01",
      "pair-custom657-r01-g01",
      "pair-custom658-r01-g01",
      "pair-custom659-r01-g01",
      "pair-custom660-r01-g01",
      "pair-custom661-r01-g01",
      "pair-custom662-r01-g01",
      "pair-custom663-r01-g01",
      "pair-custom664-r01-g01",
      "pair-custom665-r01-g01"
    ],
    plans: [
      makeScenePlan(
        "pair-custom621-r01-g01",
        "叶海捧花",
        "蹲姿",
        "蹲坐或低身靠近落叶地面，双手捧起银杏叶放在身前",
        "头部微微侧向镜头，围巾贴近脸部，表情柔和",
        "适合银杏落叶很厚的地面、树下近景和暖色秋日人像。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom622-r01-g01",
        "围巾回眸",
        "全身",
        "侧身站在银杏树下，头部回看镜头，围巾自然垂在胸前",
        "双手轻扶围巾或衣襟，肩膀放松，不要挡住脸",
        "适合银杏大道、逆光树荫和半身到七分身构图。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      ),
      makeScenePlan(
        "pair-custom623-r01-g01",
        "林下侧立",
        "全身",
        "站在银杏林中身体侧向镜头，一手扶围巾，一手自然垂下",
        "头部轻轻回看，身体保持竖直，腿部不要站成一条线",
        "适合银杏路、树林纵深和阳光穿过树叶的场景。",
        "不要裁掉手脚和关键道具，背景也不要压过人物。"
      )
    ]
  },
  {
    id: 'imported-changcheng1',
    title: '长城怎么拍',
    shortTitle: '长城',
    painPoint: '长城墙体高、游客多，只站在城墙边容易拍成普通到此一游。',
    promise: '用垛口欢呼、伸手邀请、城道坐姿和城垛回望，把城墙线条和人物动作一起拍出来。',
    shareTitle: '长城拍照作业：城墙、城垛和烽火台这样拍更有气势',
    categoryId: 'travel-back',
    coverPoseId: 'pair-custom309-r01-g01',
    morePoseIds: [
      'pair-custom293-r01-g01',
      'pair-custom294-r01-g01',
      'pair-custom295-r01-g01',
      'pair-custom296-r01-g01',
      'pair-custom297-r01-g01',
      'pair-custom298-r01-g01',
      'pair-custom299-r01-g01',
      'pair-custom300-r01-g01',
      'pair-custom301-r01-g01',
      'pair-custom302-r01-g01',
      'pair-custom303-r01-g01',
      'pair-custom304-r01-g01',
      'pair-custom305-r01-g01',
      'pair-custom306-r01-g01',
      'pair-custom307-r01-g01',
      'pair-custom308-r01-g01',
      'pair-custom309-r01-g01',
      'pair-custom310-r01-g01',
      'pair-custom311-r01-g01',
      'pair-custom312-r01-g01',
      'pair-custom313-r01-g01',
      'pair-custom314-r01-g01',
      'pair-custom315-r01-g01',
      'pair-custom316-r01-g01',
      'pair-custom317-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom309-r01-g01',
        '城墙前伸手邀请',
        '全身互动',
        '站在长城步道上向镜头伸手，像邀请拍摄者一起往前走。',
        '人物全身入镜，伸出的手形成前景，身后的城墙和山线保留完整。',
        '手机略低或平视，顺着城墙延伸方向拍出纵深。',
        '不要裁掉伸出的手和脚部，城墙线条也不要拍歪。'
      ),
      makeScenePlan(
        'pair-custom310-r01-g01',
        '城道坐地伸腿',
        '坐姿线条',
        '坐在城道地面上能压低重心，伸腿动作顺着砖路拉长线条。',
        '身体微微后撑，双腿向前伸展，脚部和城墙两侧都保留。',
        '手机略低从侧前方拍，利用地砖和墙体做透视。',
        '不要从膝盖或脚踝裁切，坐姿支撑手也要入镜。'
      ),
      makeScenePlan(
        'pair-custom317-r01-g01',
        '城垛侧倚回望',
        '地标回眸',
        '借城垛支撑身体，侧倚回望比正面站立更松弛，也能交代长城环境。',
        '人物靠在城垛旁侧身回看，右侧留出远处长城和天空。',
        '手机平视或略低，沿墙体方向构图，人物不要贴边。',
        '不要让城垛挡住脸，也不要把远景全部裁掉。'
      )
    ]
  },
  {
    id: 'imported-gulou',
    title: '北京鼓楼怎么拍',
    shortTitle: '北京鼓楼',
    painPoint: '鼓楼红墙、路牌和街巷元素多，只站着拍容易背景抢人。',
    promise: '用指牌、远指楼檐和红墙回身，把鼓楼地标和街巷氛围一起拍清楚。',
    shareTitle: '北京鼓楼拍照作业：红墙、路牌和楼檐这样拍更有地点感',
    categoryId: 'art-city',
    coverPoseId: 'pair-custom327-r01-g01',
    morePoseIds: [
      'pair-custom327-r01-g01',
      'pair-custom328-r01-g01',
      'pair-custom329-r01-g01',
      'pair-custom330-r01-g01',
      'pair-custom331-r01-g01',
      'pair-custom332-r01-g01',
      'pair-custom333-r01-g01',
      'pair-custom334-r01-g01',
      'pair-custom335-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom327-r01-g01',
        '举手指牌',
        '地标全身',
        '抬手指向路牌能直接交代地点，另一只手拿道具让动作更自然。',
        '人物站在路牌下方全身入镜，路牌放在画面上方，鼓楼背景保持完整。',
        '手机平视或略低，先对齐路牌和人物，再保留街道纵深。',
        '不要裁掉路牌和手臂，也不要让人物完全挡住鼓楼。'
      ),
      makeScenePlan(
        'pair-custom328-r01-g01',
        '远指楼檐',
        '红墙全身',
        '指向楼檐能把人物动作和古建背景连起来，比单纯靠墙更有方向。',
        '人物侧身站在红墙前，一手指向檐角，另一手扶帽或轻靠头部。',
        '手机略低竖拍，保留红墙、灰瓦和人物全身比例。',
        '不要把手指方向裁掉，建筑线条也不要明显倾斜。'
      ),
      makeScenePlan(
        'pair-custom333-r01-g01',
        '红墙回身',
        '街巷回眸',
        '沿红墙行走再回头，能拍出胡同街巷里的停留感。',
        '身体斜向前方，头部回望镜头，双手抱住糖葫芦或小道具放在身前。',
        '顺着红墙线条平视拍，给人物前方和街巷方向留空间。',
        '不要贴墙太近，回眸时肩颈不要缩起来。'
      )
    ]
  },
  {
    id: 'changsha-orange-island',
    title: '长沙橘子洲头怎么拍',
    shortTitle: '橘子洲头',
    painPoint: '雕塑前人多背景大，只站着合影容易像普通游客照。',
    promise: '用背影比心、红帽侧望和夕阳抱臂，把雕塑打卡拍得更有互动感。',
    shareTitle: '长沙橘子洲头拍照作业：青年毛泽东雕塑前照着这些姿势拍',
    categoryId: 'travel-back',
    coverPoseId: 'pair-custom184-r01-g01',
    morePoseIds: [
      'pair-custom132-r01-g01',
      'pair-custom133-r01-g01',
      'pair-custom134-r01-g01',
      'pair-custom135-r01-g01',
      'pair-custom176-r01-g01',
      'pair-custom177-r01-g01',
      'pair-custom178-r01-g01',
      'pair-custom179-r01-g01',
      'pair-custom180-r01-g01',
      'pair-custom181-r01-g01',
      'pair-custom182-r01-g01',
      'pair-custom183-r01-g01',
      'pair-custom184-r01-g01',
      'pair-custom185-r01-g01',
      'pair-custom186-r01-g01',
      'pair-custom187-r01-g01',
      'pair-custom188-r01-g01',
      'pair-custom189-r01-g01',
      'pair-custom190-r01-g01',
      'pair-custom191-r01-g01'
    ],
    plans: [
      {
        poseId: 'pair-custom184-r01-g01',
        title: '侧后方比爱心',
        badge: '背影互动',
        reason: '双手比心直接和雕塑产生关系，比普通到此一游更有记忆点。',
        composition: '背对雕塑微侧身，双手举到雕塑脸部前方，比心和雕塑同时入镜。',
        camera: '手机略低拍，保留草地前景和雕塑头部，人物不要贴画面边缘。',
        avoid: '比心不要偏离雕塑脸部，手臂和头部都不要被裁掉。'
      },
      {
        poseId: 'pair-custom185-r01-g01',
        title: '红帽插兜侧望',
        badge: '全身侧望',
        reason: '红帽提供亮色记忆点，插兜和侧望能避开直视镜头的尴尬。',
        composition: '人物全身入镜，身体侧向雕塑方向，草地和花海作为前景层次。',
        camera: '手机平视或略低，留出雕塑和天空空间，保证帽子和脚部完整。',
        avoid: '不要把脚裁掉，也不要让红帽和雕塑重叠太乱。'
      },
      {
        poseId: 'pair-custom186-r01-g01',
        title: '夕阳抱臂站立',
        badge: '逆光半身',
        reason: '夕阳侧逆光和抱臂动作能拍出更稳的气场，适合亮色穿搭。',
        composition: '半身或大半身入镜，双臂交叉抱胸，夕阳和天空作为背景。',
        camera: '手机平视，稍微压暗背景保住夕阳层次，脸部不要完全黑掉。',
        avoid: '抱臂不要耸肩，夕阳也不要被头部完全挡住。'
      }
    ]
  },
  {
    id: 'shanghai-bund',
    title: '上海外滩怎么拍',
    shortTitle: '上海外滩',
    painPoint: '外滩人多、建筑高，普通正面合影容易背景乱、动作僵。',
    promise: '用托塔、扶栏、回眸和塔下蹲拍，把东方明珠和江景拍进动作里。',
    shareTitle: '上海外滩拍照作业：东方明珠和江景这样拍更有互动感',
    categoryId: 'art-city',
    coverPoseId: 'pair-custom151-r01-g01',
    morePoseIds: [
      'pair-custom151-r01-g01',
      'pair-custom152-r01-g01',
      'pair-custom153-r01-g01',
      'pair-custom154-r01-g01',
      'pair-custom155-r01-g01',
      'pair-custom156-r01-g01',
      'pair-custom157-r01-g01',
      'pair-custom158-r01-g01',
      'pair-custom159-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom151-r01-g01',
        '街头托塔',
        '地标互动',
        '手掌托住东方明珠，能把地标变成动作的一部分。',
        '人物半身入镜，手掌放到塔身下方，背景保留完整塔体。',
        '手机略低，边看屏幕边微调手掌和塔的位置。',
        '手掌不要离塔太远，否则互动关系会断。'
      ),
      makeScenePlan(
        'pair-custom154-r01-g01',
        '扶栏拨发',
        '江景半身',
        '栏杆给手部动作落点，拨发能让夜景人像更自然。',
        '人物靠近栏杆，侧身拨发，江面和灯光作为背景。',
        '手机平视，从侧前方拍，保留栏杆线条。',
        '不要让栏杆横线切到脸部。'
      ),
      makeScenePlan(
        'pair-custom158-r01-g01',
        '背影走塔',
        '城市背影',
        '背影走向地标比原地站立更有旅行故事感。',
        '人物背影全身入镜，路面、栏杆和东方明珠形成纵深。',
        '手机略低连拍，抓迈步自然的一张。',
        '不要把脚裁掉，塔也不要只剩半截。'
      )
    ]
  },
  {
    id: 'imported-caodi',
    title: '公园草地怎么拍',
    shortTitle: '公园草地',
    painPoint: '草地场景看起来选择多，但坐下容易塌、站着容易空，手和腿不知道怎么摆。',
    promise: '用俯身看书、树旁回眸和抱膝微笑，把草地照片拍出文艺午后和松弛生活感。',
    shareTitle: '公园草地拍照作业：坐姿、躺姿、野餐和行走动作照着拍',
    categoryId: 'sitting-life',
    coverPoseId: 'pair-custom274-r01-g01',
    morePoseIds: [
      'pair-custom274-r01-g01',
      'pair-custom275-r01-g01',
      'pair-custom276-r01-g01',
      'pair-custom35-r01-g01',
      'pair-custom45-r01-g01',
      'pair-custom47-r01-g01',
      'pair-custom50-r01-g01',
      'pair-custom55-r01-g01',
      'pair-custom58-r01-g01',
      'pair-custom74-r01-g01',
      'pair-custom95-r01-g01',
      'pair-custom118-r01-g01',
      'pair-custom125-r01-g01',
      'pair-custom261-r01-g01',
      'pair-custom262-r01-g01',
      'pair-custom263-r01-g01',
      'pair-custom264-r01-g01',
      'pair-custom265-r01-g01',
      'pair-custom266-r01-g01',
      'pair-custom267-r01-g01',
      'pair-custom268-r01-g01',
      'pair-custom269-r01-g01',
      'pair-custom270-r01-g01',
      'pair-custom271-r01-g01',
      'pair-custom272-r01-g01',
      'pair-custom273-r01-g01',
      'pair-custom277-r01-g01',
      'pair-custom278-r01-g01',
      'pair-custom279-r01-g01',
      'pair-custom280-r01-g01',
      'pair-custom281-r01-g01',
      'pair-custom282-r01-g01',
      'pair-custom283-r01-g01',
      'pair-custom284-r01-g01',
      'pair-custom285-r01-g01',
      'pair-custom286-r01-g01',
      'pair-custom287-r01-g01',
      'pair-custom288-r01-g01',
      'pair-custom289-r01-g01',
      'pair-custom290-r01-g01',
      'pair-custom291-r01-g01',
      'pair-custom292-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom274-r01-g01',
        '俯身看书',
        '草地趴姿',
        '身体俯趴在草地上，手肘稳定支撑上半身，书本放在身前。',
        '小腿向后弯起、脚尖轻轻上翘，视线看向镜头，动作要轻松不要塌肩。',
        '贴近草坪的低机位能突出悠闲午后感和书本互动。',
        '不要裁掉书本、脚尖和手肘支撑点。'
      ),
      makeScenePlan(
        'pair-custom275-r01-g01',
        '树旁回眸',
        '草地全身',
        '身体贴近树干侧站，肩线微微转开，单肩背包自然下垂。',
        '回头看向镜头微笑，手臂放松，裙摆和发丝保持轻盈。',
        '竖构图保留树干、草坪和人物全身层次。',
        '不要让树干遮住身体，也不要裁掉脚部。'
      ),
      makeScenePlan(
        'pair-custom276-r01-g01',
        '抱膝微笑',
        '草地坐姿',
        '坐在草地上收紧双腿，让膝盖靠近身体，双手托住下巴。',
        '手肘落在膝上形成稳定三角形，表情放松看镜头。',
        '平视或略高机位突出表情，背景保留树荫和草地留白。',
        '不要把膝盖拍得过大，托下巴的手不要挡住整张脸。'
      )
    ]
  },
  {
    id: 'bamboo-creek',
    title: '竹林溪边怎么拍',
    shortTitle: '竹林溪边',
    painPoint: '竹林和溪水颜色接近，站着拍容易没有动作重点。',
    promise: '用遮光、坐姿伸展、蓝伞和瀑布抓拍，把绿色场景拍得更有层次。',
    shareTitle: '竹林溪边拍照作业：照着这些姿势拍出清透旅行感',
    categoryId: 'travel-back',
    coverPoseId: 'pair-custom142-r01-g01',
    morePoseIds: [
      'pair-custom136-r01-g01',
      'pair-custom137-r01-g01',
      'pair-custom138-r01-g01',
      'pair-custom139-r01-g01',
      'pair-custom140-r01-g01',
      'pair-custom141-r01-g01',
      'pair-custom142-r01-g01',
      'pair-custom143-r01-g01',
      'pair-custom144-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom142-r01-g01',
        '蓝伞侧立',
        '道具侧身',
        '蓝伞能从绿色背景里跳出来，侧身站更显线条。',
        '人物全身入镜，伞面和竹林同时保留，身体微侧。',
        '手机平视或略低，避开伞面挡脸。',
        '不要把伞裁掉，也不要让伞完全压住肩颈。'
      ),
      makeScenePlan(
        'pair-custom136-r01-g01',
        '仰头遮光',
        '清透半身',
        '抬手遮光能解决手部空着的问题，也能和林间光线呼应。',
        '人物半身入镜，一手抬到额前，脸部微仰。',
        '手机平视，利用树影做前景层次。',
        '手不要压住眼睛，脸部不要被阴影盖住。'
      ),
      makeScenePlan(
        'pair-custom141-r01-g01',
        '瀑旁拍照',
        '旅行抓拍',
        '拿手机拍景的动作比直站更自然，也能交代溪边瀑布环境。',
        '人物七分身入镜，手机、瀑布和身体动作都保留。',
        '从侧后方拍，保留水流方向。',
        '不要裁掉手里的手机。'
      )
    ]
  },
  {
    id: 'beach-vacation',
    title: '海边沙滩怎么拍',
    shortTitle: '海边沙滩',
    painPoint: '海边风大、背景空，动作容易重复，手和道具也不知道怎么放。',
    promise: '用踢水花、捧脸坐姿、举椰欢呼和海边回眸，把沙滩拍出清爽度假感。',
    shareTitle: '海边沙滩拍照作业：照着这些动作拍出松弛度假感',
    categoryId: 'travel-back',
    coverPoseId: 'pair-custom160-r01-g01',
    morePoseIds: [
      'pair-custom160-r01-g01',
      'pair-custom682-r01-g01',
      'pair-custom683-r01-g01',
      'pair-custom684-r01-g01',
      'pair-custom685-r01-g01',
      'pair-custom686-r01-g01',
      'pair-custom687-r01-g01',
      'pair-custom688-r01-g01',
      'pair-custom689-r01-g01',
      'pair-custom690-r01-g01',
      'pair-custom145-r01-g01',
      'pair-custom146-r01-g01',
      'pair-custom147-r01-g01',
      'pair-custom148-r01-g01',
      'pair-custom149-r01-g01',
      'pair-custom150-r01-g01',
      'pair-custom161-r01-g01',
      'pair-custom162-r01-g01',
      'pair-custom163-r01-g01',
      'pair-custom164-r01-g01',
      'pair-custom165-r01-g01',
      'pair-custom166-r01-g01',
      'pair-custom167-r01-g01',
      'pair-custom168-r01-g01',
      'pair-custom169-r01-g01',
      'pair-custom170-r01-g01',
      'pair-custom171-r01-g01',
      'pair-custom172-r01-g01',
      'pair-custom173-r01-g01',
      'pair-custom174-r01-g01',
      'pair-custom175-r01-g01',
      'pair-custom244-r01-g01',
      'pair-custom245-r01-g01',
      'pair-custom246-r01-g01',
      'pair-custom17-r01-g01',
      'pair-custom44-r01-g01',
      'pair-custom48-r01-g01',
      'pair-custom52-r01-g01',
      'pair-custom53-r01-g01',
      'pair-custom57-r01-g01',
      'pair-custom96-r01-g01',
      'pair-custom99-r01-g01',
      'pair-custom100-r01-g01',
      'pair-custom122-r01-g01',
      'pair-custom247-r01-g01',
      'pair-custom248-r01-g01',
      'pair-custom249-r01-g01',
      'pair-custom250-r01-g01',
      'pair-custom251-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom160-r01-g01',
        '踢水花',
        '浅滩动态',
        '单腿向前踢起水花，动作明快，很适合做海边沙滩首图。',
        '人物全身入镜，双臂自然展开保持平衡，脚边水花和海面都要保留。',
        '手机略低连拍，抓水花最高、表情最自然的一张。',
        '不要裁掉脚边水花，也不要让海平线明显倾斜。'
      ),
      makeScenePlan(
        'pair-custom682-r01-g01',
        '粉色格纹捧脸',
        '沙滩坐姿',
        '坐在铺开的沙滩布或毛巾上，动作小但和场景关系明确。',
        '人物正面入镜，双手抬到脸颊两侧，保留沙滩布和身前空间。',
        '机位与视线齐平或略高，正面构图，眼神微微向下。',
        '不要裁掉手脚、沙滩布和身边道具。'
      ),
      makeScenePlan(
        'pair-custom683-r01-g01',
        '举椰欢呼',
        '道具全身',
        '椰子和抬手动作能解决手空问题，也能把海边度假感拍出来。',
        '全身入镜，一条腿向后勾起，右手托举青椰，左手斜向上打开。',
        '手机放低到腰线以下微仰拍，把腿部线条和蓝天一起框进来。',
        '不要裁掉椰子、手臂和脚部动作。'
      )
    ]
  },
  {
    id: 'lotus-pond',
    title: '荷塘荷花怎么拍',
    shortTitle: '荷塘荷花',
    painPoint: '荷叶多、花也多，动作太小会被背景吃掉。',
    promise: '用荷叶当伞、执扇端坐、荷花近景和背影摸叶，拍出夏日古风感。',
    shareTitle: '荷塘荷花拍照作业：荷叶、团扇和花都能用起来',
    categoryId: 'travel-back',
    coverPoseId: 'pair-custom193-r01-g01',
    morePoseIds: [
      'pair-custom192-r01-g01',
      'pair-custom193-r01-g01',
      'pair-custom194-r01-g01',
      'pair-custom195-r01-g01',
      'pair-custom196-r01-g01',
      'pair-custom197-r01-g01',
      'pair-custom198-r01-g01',
      'pair-custom199-r01-g01',
      'pair-custom200-r01-g01',
      'pair-custom201-r01-g01',
      'pair-custom202-r01-g01',
      'pair-custom203-r01-g01',
      'pair-custom204-r01-g01',
      'pair-custom205-r01-g01',
      'pair-custom206-r01-g01',
      'pair-custom207-r01-g01',
      'pair-custom208-r01-g01',
      'pair-custom209-r01-g01',
      'pair-custom210-r01-g01',
      'pair-custom211-r01-g01',
      'pair-custom212-r01-g01',
      'pair-custom213-r01-g01',
      'pair-custom214-r01-g01',
      'pair-custom215-r01-g01',
      'pair-custom216-r01-g01',
      'pair-custom217-r01-g01',
      'pair-custom218-r01-g01',
      'pair-custom219-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom195-r01-g01',
        '荷叶当伞',
        '荷叶道具',
        '把荷叶举到头顶能立刻形成夏日识别点，也解决手部动作。',
        '人物半身入镜，荷叶在头顶偏一侧，脸部露出来。',
        '手机平视，背景荷塘虚一点，人物和荷叶清晰。',
        '荷叶不要完全遮脸。'
      ),
      makeScenePlan(
        'pair-custom193-r01-g01',
        '执扇端坐',
        '古风坐姿',
        '团扇和坐姿更适合荷塘的安静氛围，画面不容易乱。',
        '人物坐姿入镜，团扇放在胸前或脸侧，保留荷叶背景。',
        '手机略高一点拍，避免腿部和裙摆变形。',
        '团扇不要挡住五官。'
      ),
      makeScenePlan(
        'pair-custom203-r01-g01',
        '背影摸叶',
        '背影氛围',
        '背影伸手摸荷叶，能把人物和荷塘关系拍清楚。',
        '人物背影七分身入镜，一手伸向荷叶，水面和叶片保留。',
        '从身后稍侧拍，保持手和叶片不重叠。',
        '不要只拍背，手碰荷叶的动作要看得见。'
      )
    ]
  },
  {
    id: 'rapeseed-field',
    title: '油菜花田怎么拍',
    shortTitle: '油菜花田',
    painPoint: '花海太满，人物动作不明显时容易被黄色背景淹没。',
    promise: '用挥手、抛帽、提帽遮阳和花丛蹲拍，让花田照片有明确动作。',
    shareTitle: '油菜花田拍照作业：帽子和花海这样拍更出片',
    categoryId: 'travel-back',
    coverPoseId: 'pair-custom237-r01-g01',
    morePoseIds: [
      'pair-custom235-r01-g01',
      'pair-custom236-r01-g01',
      'pair-custom237-r01-g01',
      'pair-custom238-r01-g01',
      'pair-custom239-r01-g01',
      'pair-custom240-r01-g01',
      'pair-custom241-r01-g01',
      'pair-custom242-r01-g01',
      'pair-custom243-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom237-r01-g01',
        '抛帽仰头',
        '动态花海',
        '抛帽动作能从花海里跳出来，画面更有动势。',
        '人物全身或七分身入镜，帽子抛到头顶上方，花海保留到腰部。',
        '手机略低连拍，抓帽子刚离手的一张。',
        '不要把帽子裁出画面。'
      ),
      makeScenePlan(
        'pair-custom238-r01-g01',
        '提帽遮阳',
        '帽子道具',
        '提帽遮阳适合强光花田，也能让手部动作自然。',
        '人物半身入镜，一手提帽檐，脸微侧。',
        '手机平视，注意脸部不要过曝。',
        '帽檐不要压住眼睛。'
      ),
      makeScenePlan(
        'pair-custom242-r01-g01',
        '花丛蹲拍',
        '低位花海',
        '蹲下来能让花海包围人物，适合近距离拍层次。',
        '人物蹲在花丛边，手靠近花朵，脸部露出。',
        '手机略低或平视，让前景花朵虚一点。',
        '不要让花完全挡住脸。'
      )
    ]
  },
  {
    id: 'outdoor-sport',
    title: '户外运动怎么拍',
    shortTitle: '户外运动',
    painPoint: '运动风照片只站着会像装备照，动作不够有能量。',
    promise: '用登山、挥拍、跑动、骑行、扶帽和伸展动作，拍出更有力量的户外感。',
    shareTitle: '户外运动拍照作业：跑动、挥拍、骑行和伸展这样拍',
    categoryId: 'outfit-standing',
    coverPoseId: 'pair-custom249-r01-g01',
    morePoseIds: [
      'pair-custom33-r01-g01',
      'pair-custom42-r01-g01',
      'pair-custom54-r01-g01',
      'pair-custom58-r01-g01',
      'pair-custom66-r01-g01',
      'pair-custom119-r01-g01',
      'pair-custom247-r01-g01',
      'pair-custom248-r01-g01',
      'pair-custom249-r01-g01',
      'pair-custom250-r01-g01',
      'pair-custom251-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom249-r01-g01',
        '双臂高举伸展',
        '能量伸展',
        '高举双臂能拉开身体线条，适合户外开阔背景。',
        '人物全身入镜，双臂向上打开，脚下地面保留完整。',
        '手机略低拍，天空留白多一点。',
        '不要裁掉手臂和脚。'
      ),
      makeScenePlan(
        'pair-custom42-r01-g01',
        '羽毛球挥拍弓步',
        '挥拍动态',
        '挥拍和弓步自带发力感，适合球场、操场或开阔草地。',
        '人物全身入镜，球拍举到画面上方，前后腿形成斜线。',
        '手机平视或略低，连拍抓住挥拍最高点。',
        '不要裁掉球拍和后脚，手臂也不要贴住身体。'
      ),
      makeScenePlan(
        'pair-custom54-r01-g01',
        '跑动挥手活力',
        '跑动抓拍',
        '跑动和挥手能让运动风更有感染力，适合公园、操场和校园路面。',
        '人物从画面一侧跑向镜头，给前进方向留空间。',
        '手机平视连拍，优先挑双脚离地或手臂打开的一张。',
        '不要用太慢快门，脸和脚都容易糊。'
      )
    ]
  },
  {
    id: 'pipe-sitting',
    title: '台阶坐姿怎么拍',
    shortTitle: '台阶坐姿',
    painPoint: '坐在管道、台阶或低矮装置上时，身体容易塌，手也不知道放哪。',
    promise: '用倚坐、托膝、撑臂后仰和扶手动作，把坐姿拍得更有线条。',
    shareTitle: '台阶坐姿拍照作业：低矮装置和楼梯上照着这些动作拍',
    categoryId: 'sitting-life',
    coverPoseId: 'pair-custom226-r01-g01',
    morePoseIds: [
      'pair-custom226-r01-g01',
      'pair-custom227-r01-g01',
      'pair-custom228-r01-g01',
      'pair-custom229-r01-g01',
      'pair-custom230-r01-g01',
      'pair-custom231-r01-g01',
      'pair-custom232-r01-g01',
      'pair-custom233-r01-g01',
      'pair-custom234-r01-g01',
      'pair-custom101-r01-g01',
      'pair-custom40-r01-g01',
      'pair-custom64-r01-g01',
      'pair-custom92-r01-g01',
      'pair-custom121-r01-g01'
    ],
    plans: [
      makeScenePlan(
        'pair-custom226-r01-g01',
        '慵懒倚坐',
        '松弛坐姿',
        '身体轻靠能让坐姿更放松，不会像端坐证件照。',
        '人物坐在管道或台面边，身体向一侧倚，腿部自然伸展。',
        '手机略低，从侧前方拍出腿部线条。',
        '不要弓背塌腰，脚部不要被裁掉。'
      ),
      makeScenePlan(
        'pair-custom229-r01-g01',
        '静坐托膝',
        '托膝构图',
        '托膝能给手一个落点，也能让坐姿更安静。',
        '人物坐姿入镜，一手或双手落在膝盖附近，身体微侧。',
        '手机平视，保留坐具边缘和腿部方向。',
        '膝盖不要顶到画面最前面造成变形。'
      ),
      makeScenePlan(
        'pair-custom231-r01-g01',
        '撑臂后仰',
        '身体线条',
        '撑臂后仰能打开肩颈，坐姿更有力量感。',
        '人物坐在边缘，双臂向后支撑，上半身微微后仰。',
        '手机略低侧拍，拍清手臂支撑点。',
        '不要后仰过度，手臂和肩颈线条要自然。'
      )
    ]
  },
  {
    id: 'lake-riverside',
    title: '湖边河畔怎么拍',
    shortTitle: '湖边河畔',
    painPoint: '湖边河边没有海浪和沙滩，动作太大容易违和，站着又显得普通。',
    promise: '用白莲点水、浅水踢鞋和码头坐姿，把普通水边拍出安静松弛感。',
    shareTitle: '湖边河畔拍照作业：没有海边也能照着这 3 个动作拍',
    categoryId: 'travel-back',
    coverPoseId: 'pair-custom129-r01-g01',
    morePoseIds: [
      'pair-custom13-r01-g01',
      'pair-custom26-r01-g01',
      'pair-custom71-r01-g01',
      'pair-custom73-r01-g01',
      'pair-custom102-r01-g01',
      'pair-custom103-r01-g01',
      'pair-custom4-r01-g01',
      'pair-custom74-r01-g01',
      'pair-custom61-r01-g01',
      'pair-custom65-r01-g01',
      'pair-custom123-r01-g01'
    ],
    plans: [
      {
        poseId: 'pair-custom129-r01-g01',
        title: '白莲点水站姿',
        badge: '湖面点水',
        reason: '白莲轻触水面很有普通湖边的识别度，比单纯站在岸边更有动作记忆点。',
        composition: '全身或七分身入镜，保留脚边水面、白莲和远处湖面。',
        camera: '手机平视或略低，人物微侧，花茎顺着身体线条向下延伸。',
        avoid: '不要裁掉花头和脚边水面，点水动作会看不出来。'
      },
      {
        poseId: 'pair-custom69-r01-g01',
        title: '湖边提鞋踢水',
        badge: '浅水互动',
        reason: '提鞋和轻踢水面更像湖边河边的夏日互动，不会和海边踢浪混淆。',
        composition: '全身入镜，保留手里的鞋、裙摆和脚边水花。',
        camera: '手机平视连拍，抓脚尖刚踢起水面的一瞬间。',
        avoid: '不要让水花和脚被裁掉，互动感会变弱。'
      },
      {
        poseId: 'pair-custom29-r01-g01',
        title: '码头整理辫子',
        badge: '码头坐姿',
        reason: '木码头和低头整理辫子很安静，适合河边码头、湖边栈桥这类普通水边场景。',
        composition: '全身背影或七分身入镜，保留码头边缘和水面。',
        camera: '手机平视，从侧后方拍，人物不要坐得太贴画面边缘。',
        avoid: '不要只拍上半身，脚边水面和码头线条是重点。'
      }
    ]
  },
  {
    id: 'flower-street',
    title: '花束街拍怎么拍',
    shortTitle: '花束街拍',
    painPoint: '拿到花束后只会抱在胸前，照片容易像证件照加道具。',
    promise: '用小巷旋转、捧花飞裙和暖光正站，让花束自然参与动作。',
    shareTitle: '花束街拍拍照作业：这 3 个动作比抱花站着更出片',
    categoryId: 'street-commute',
    coverPoseId: 'pair-custom127-r01-g01',
    morePoseIds: [
      'pair-custom113-r01-g01',
      'pair-custom120-r01-g01',
      'pair-custom123-r01-g01',
      'pair-custom126-r01-g01',
      'pair-custom128-r01-g01',
      'pair-custom130-r01-g01',
      'pair-custom118-r01-g01',
      'pair-custom121-r01-g01',
      'pair-custom124-r01-g01',
      'pair-custom125-r01-g01'
    ],
    plans: [
      {
        poseId: 'pair-custom127-r01-g01',
        title: '玫瑰小巷旋转',
        badge: '小巷旋转',
        reason: '小巷纵深和玫瑰花束很有氛围，裙摆动作比原地站更有画面感。',
        composition: '全身入镜，保留小巷两侧墙面和脚下路面。',
        camera: '手机略低，连拍抓裙摆展开的一瞬间。',
        avoid: '不要裁掉裙摆和花束。'
      },
      {
        poseId: 'pair-custom126-r01-g01',
        title: '捧花旋转飞裙',
        badge: '动态花束',
        reason: '花束和裙摆一起形成动态，比普通抱花站姿更像拍照作业。',
        composition: '全身入镜，保留花束、裙摆和脚下路面。',
        camera: '手机略低连拍，抓裙摆打开的一张。',
        avoid: '不要裁掉裙摆和手里的花。'
      },
      {
        poseId: 'pair-custom128-r01-g01',
        title: '郁金香暖光正站',
        badge: '暖光花束',
        reason: '暖光街景和红色郁金香很有氛围，适合作为花束专题的安静款。',
        composition: '全身入镜，花束放在身体中线但不要挡住脸。',
        camera: '手机平视，背景街灯和路面纵深保留一点。',
        avoid: '不要让花束压住腰线。'
      }
    ]
  },
  {
    id: 'mirror-selfie',
    title: '镜前自拍怎么拍',
    shortTitle: '镜前自拍',
    painPoint: '对镜自拍很容易遮脸、显腿短，动作也容易重复。',
    promise: '用酷感站姿、蹲姿和侧立，让镜前自拍更像穿搭大片。',
    shareTitle: '镜前自拍拍照作业：这 3 个姿势照着拍更显比例',
    categoryId: 'selfie',
    coverPoseId: 'pair-custom107-r01-g01',
    morePoseIds: [
      'pair-custom110-r01-g01',
      'pair-custom115-r01-g01',
      'pair-custom75-r01-g01',
      'pair-custom79-r01-g01',
      'pair-custom34-r01-g01',
      'pair-custom108-r01-g01'
    ],
    plans: [
      {
        poseId: 'pair-custom107-r01-g01',
        title: '酷感对镜自拍',
        badge: '镜前穿搭',
        reason: '对镜构图完整，适合展示全身穿搭和姿态比例。',
        composition: '镜子里全身入镜，手机不要挡住脸部重点。',
        camera: '手机放在胸口附近，镜头略向下但不要俯拍过重。',
        avoid: '不要把脚裁掉，对镜照会立刻显矮。'
      },
      {
        poseId: 'pair-custom110-r01-g01',
        title: '单膝蹲姿自拍',
        badge: '酷感蹲姿',
        reason: '蹲姿比普通站姿更有态度，适合做镜前自拍里的强风格参考。',
        composition: '全身入镜，帽子、鞋和包都保留。',
        camera: '手机放在脸侧，镜头略向下但不要把腿拍短。',
        avoid: '不要让手机完全挡住脸。'
      },
      {
        poseId: 'pair-custom112-r01-g01',
        title: '倚墙侧立自拍',
        badge: '显腿线条',
        reason: '靠墙侧立能稳定身体，腿部交错更显比例。',
        composition: '全身入镜，保留包和脚部姿态。',
        camera: '手机平视或略低，人物身体侧向镜子。',
        avoid: '不要让手机挡住上半身轮廓。'
      }
    ]
  }
]

const SCENE_TOPIC_ALIASES = {
  'cafe-window': 'imported-kafei',
  'city-stairs': 'pipe-sitting',
  'imported-cafe': 'imported-kafei',
  'imported-caodi1': 'imported-caodi',
  'imported-changcheng2': 'imported-changcheng1',
  'imported-haitan-a': 'beach-vacation',
  'imported-heshun2': 'imported-heshun',
  'imported-heshun3': 'imported-heshun',
  'imported-taizhuang': 'imported-yinta',
  'imported-yinta2': 'imported-yinta',
  'imported-yinta3': 'imported-yinta',
  'imported-yinta4': 'imported-yinta',
  'imported-yinta5': 'imported-yinta',
  'imported-yinxing2': 'imported-yinxing1',
  'imported-yinxing3': 'imported-yinxing1',
  'imported-yinxing4': 'imported-yinxing1',
  'imported-yinxing5': 'imported-yinxing1',
  'orchard-vine': 'imported-senlin',
  'flower-tree': 'imported-senlin'
}

const getSceneTopic = (topicId) => {
  const resolvedTopicId = SCENE_TOPIC_ALIASES[topicId] || topicId
  return sceneTopics.find((topic) => topic.id === resolvedTopicId) || sceneTopics[0]
}

module.exports = {
  SCENE_TOPIC_DETAIL_KEY,
  sceneTopics,
  getSceneTopic,
  isLandmarkTopic
}
